# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AlgorithmLaunchSpec
#' @description AlgorithmLaunchSpec Class
#' @format An \code{R6Class} generator object
#' @field algorithm_name  character 
#'
#' @field media_ids  list( integer ) [optional]
#'
#' @field media_query  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AlgorithmLaunchSpec <- R6::R6Class(
  'AlgorithmLaunchSpec',
  public = list(
    `algorithm_name` = NULL,
    `media_ids` = NULL,
    `media_query` = NULL,
    initialize = function(`algorithm_name`, `media_ids`=NULL, `media_query`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`algorithm_name`)) {
        stopifnot(is.character(`algorithm_name`), length(`algorithm_name`) == 1)
        self$`algorithm_name` <- `algorithm_name`
      }
      if (!is.null(`media_ids`)) {
        stopifnot(is.vector(`media_ids`), length(`media_ids`) != 0)
        sapply(`media_ids`, function(x) stopifnot(is.character(x)))
        self$`media_ids` <- `media_ids`
      }
      if (!is.null(`media_query`)) {
        stopifnot(is.character(`media_query`), length(`media_query`) == 1)
        self$`media_query` <- `media_query`
      }
    },
    toJSON = function() {
      AlgorithmLaunchSpecObject <- list()
      if (!is.null(self$`algorithm_name`)) {
        AlgorithmLaunchSpecObject[['algorithm_name']] <-
          self$`algorithm_name`
      }
      if (!is.null(self$`media_ids`)) {
        AlgorithmLaunchSpecObject[['media_ids']] <-
          self$`media_ids`
      }
      if (!is.null(self$`media_query`)) {
        AlgorithmLaunchSpecObject[['media_query']] <-
          self$`media_query`
      }

      AlgorithmLaunchSpecObject
    },
    fromJSON = function(AlgorithmLaunchSpecJson) {
      AlgorithmLaunchSpecObject <- jsonlite::fromJSON(AlgorithmLaunchSpecJson)
      if (!is.null(AlgorithmLaunchSpecObject$`algorithm_name`)) {
        self$`algorithm_name` <- AlgorithmLaunchSpecObject$`algorithm_name`
      }
      if (!is.null(AlgorithmLaunchSpecObject$`media_ids`)) {
        self$`media_ids` <- ApiClient$new()$deserializeObj(AlgorithmLaunchSpecObject$`media_ids`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(AlgorithmLaunchSpecObject$`media_query`)) {
        self$`media_query` <- AlgorithmLaunchSpecObject$`media_query`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`algorithm_name`)) {
        sprintf(
        '"algorithm_name":
          "%s"
                ',
        self$`algorithm_name`
        )},
        if (!is.null(self$`media_ids`)) {
        sprintf(
        '"media_ids":
           [%s]
        ',
        paste(unlist(lapply(self$`media_ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`media_query`)) {
        sprintf(
        '"media_query":
          "%s"
                ',
        self$`media_query`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AlgorithmLaunchSpecJson) {
      AlgorithmLaunchSpecObject <- jsonlite::fromJSON(AlgorithmLaunchSpecJson)
      self$`algorithm_name` <- AlgorithmLaunchSpecObject$`algorithm_name`
      self$`media_ids` <- ApiClient$new()$deserializeObj(AlgorithmLaunchSpecObject$`media_ids`, "array[integer]", loadNamespace("tator"))
      self$`media_query` <- AlgorithmLaunchSpecObject$`media_query`
      self
    }
  )
)
