# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AlgorithmLaunch
#' @description AlgorithmLaunch Class
#' @format An \code{R6Class} generator object
#' @field group_id  character [optional]
#'
#' @field message  character [optional]
#'
#' @field run_uids  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AlgorithmLaunch <- R6::R6Class(
  'AlgorithmLaunch',
  public = list(
    `group_id` = NULL,
    `message` = NULL,
    `run_uids` = NULL,
    #' @description Create a new instance of AlgorithmLaunch
    #' @param group_id (character) A uuid1 string identifying the group of jobs started.
    #' @param message (character) Message indicating successful launch.
    #' @param run_uids (vector) A list of uuid1 strings identifying each job started.
    #' @param ... (list) local.optional.var
    initialize = function(`group_id`=NULL, `message`=NULL, `run_uids`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`group_id`)) {
        stopifnot(is.character(`group_id`), length(`group_id`) == 1)
        self$`group_id` <- `group_id`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`run_uids`)) {
        stopifnot(is.vector(`run_uids`), length(`run_uids`) != 0)
        sapply(`run_uids`, function(x) stopifnot(is.character(x)))
        self$`run_uids` <- `run_uids`
      }
    },
    #' @description Convert an instance of AlgorithmLaunch to an R list object
    toJSON = function() {
      AlgorithmLaunchObject <- list()
      if (!is.null(self$`group_id`)) {
        AlgorithmLaunchObject[['group_id']] <-
          self$`group_id`
      }
      if (!is.null(self$`message`)) {
        AlgorithmLaunchObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`run_uids`)) {
        AlgorithmLaunchObject[['run_uids']] <-
          self$`run_uids`
      }

      AlgorithmLaunchObject
    },
    #' @description Convert an R JSON object to an R list type
    #' @param AlgorithmLaunchJson (character) A JSON string representing an AlgorithmLaunch
    fromJSON = function(AlgorithmLaunchJson) {
      AlgorithmLaunchObject <- jsonlite::fromJSON(AlgorithmLaunchJson)
      if (!is.null(AlgorithmLaunchObject$`group_id`)) {
        self$`group_id` <- AlgorithmLaunchObject$`group_id`
      }
      if (!is.null(AlgorithmLaunchObject$`message`)) {
        self$`message` <- AlgorithmLaunchObject$`message`
      }
      if (!is.null(AlgorithmLaunchObject$`run_uids`)) {
        self$`run_uids` <- ApiClient$new()$deserializeObj(AlgorithmLaunchObject$`run_uids`, "array[character]", loadNamespace("tator"))
      }
    },
    #' @description Convert an instance of AlgorithmLaunch to a JSON string
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`group_id`)) {
        sprintf(
        '"group_id":
          "%s"
                ',
        self$`group_id`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`run_uids`)) {
        sprintf(
        '"run_uids":
           [%s]
        ',
        paste(unlist(lapply(self$`run_uids`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    #' @description Create an instance of AlgorithmLaunch from a JSON string
    #' @param AlgorithmLaunchJson (character) A JSON string representing an AlgorithmLaunch
    fromJSONString = function(AlgorithmLaunchJson) {
      AlgorithmLaunchObject <- jsonlite::fromJSON(AlgorithmLaunchJson)
      self$`group_id` <- AlgorithmLaunchObject$`group_id`
      self$`message` <- AlgorithmLaunchObject$`message`
      self$`run_uids` <- ApiClient$new()$deserializeObj(AlgorithmLaunchObject$`run_uids`, "array[character]", loadNamespace("tator"))
      self
    }
  )
)
