# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Algorithm
#' @description Algorithm Class
#' @format An \code{R6Class} generator object
#' @field description  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Algorithm <- R6::R6Class(
  'Algorithm',
  public = list(
    `description` = NULL,
    `id` = NULL,
    `name` = NULL,
    initialize = function(`description`=NULL, `id`=NULL, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      AlgorithmObject <- list()
      if (!is.null(self$`description`)) {
        AlgorithmObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`id`)) {
        AlgorithmObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        AlgorithmObject[['name']] <-
          self$`name`
      }

      AlgorithmObject
    },
    fromJSON = function(AlgorithmJson) {
      AlgorithmObject <- jsonlite::fromJSON(AlgorithmJson)
      if (!is.null(AlgorithmObject$`description`)) {
        self$`description` <- AlgorithmObject$`description`
      }
      if (!is.null(AlgorithmObject$`id`)) {
        self$`id` <- AlgorithmObject$`id`
      }
      if (!is.null(AlgorithmObject$`name`)) {
        self$`name` <- AlgorithmObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AlgorithmJson) {
      AlgorithmObject <- jsonlite::fromJSON(AlgorithmJson)
      self$`description` <- AlgorithmObject$`description`
      self$`id` <- AlgorithmObject$`id`
      self$`name` <- AlgorithmObject$`name`
      self
    }
  )
)
