# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AnalysisSpec
#' @description AnalysisSpec Class
#' @format An \code{R6Class} generator object
#' @field data_query  character 
#'
#' @field name  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AnalysisSpec <- R6::R6Class(
  'AnalysisSpec',
  public = list(
    `data_query` = NULL,
    `name` = NULL,
    #' @description Create a new instance of AnalysisSpec
    #' @param data_query (character) Lucene query string used to retrieve entities to analyze.
    #' @param name (character) Name of analysis.
    #' @param ... (list) local.optional.var
    initialize = function(`data_query`, `name`, ...){
      local.optional.var <- list(...)
      if (!missing(`data_query`)) {
        stopifnot(is.character(`data_query`), length(`data_query`) == 1)
        self$`data_query` <- `data_query`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    #' @description Convert an instance of AnalysisSpec to an R list object
    toJSON = function() {
      AnalysisSpecObject <- list()
      if (!is.null(self$`data_query`)) {
        AnalysisSpecObject[['data_query']] <-
          self$`data_query`
      }
      if (!is.null(self$`name`)) {
        AnalysisSpecObject[['name']] <-
          self$`name`
      }

      AnalysisSpecObject
    },
    #' @description Convert an R JSON object to an R list type
    #' @param AnalysisSpecJson (character) A JSON string representing an AnalysisSpec
    fromJSON = function(AnalysisSpecJson) {
      AnalysisSpecObject <- jsonlite::fromJSON(AnalysisSpecJson)
      if (!is.null(AnalysisSpecObject$`data_query`)) {
        self$`data_query` <- AnalysisSpecObject$`data_query`
      }
      if (!is.null(AnalysisSpecObject$`name`)) {
        self$`name` <- AnalysisSpecObject$`name`
      }
    },
    #' @description Convert an instance of AnalysisSpec to a JSON string
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data_query`)) {
        sprintf(
        '"data_query":
          "%s"
                ',
        self$`data_query`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    #' @description Create an instance of AnalysisSpec from a JSON string
    #' @param AnalysisSpecJson (character) A JSON string representing an AnalysisSpec
    fromJSONString = function(AnalysisSpecJson) {
      AnalysisSpecObject <- jsonlite::fromJSON(AnalysisSpecJson)
      self$`data_query` <- AnalysisSpecObject$`data_query`
      self$`name` <- AnalysisSpecObject$`name`
      self
    }
  )
)
