# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Analysis
#' @description Analysis Class
#' @format An \code{R6Class} generator object
#' @field data_query  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Analysis <- R6::R6Class(
  'Analysis',
  public = list(
    `data_query` = NULL,
    `id` = NULL,
    `name` = NULL,
    initialize = function(`data_query`='*', `id`=NULL, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`data_query`)) {
        stopifnot(is.character(`data_query`), length(`data_query`) == 1)
        self$`data_query` <- `data_query`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      AnalysisObject <- list()
      if (!is.null(self$`data_query`)) {
        AnalysisObject[['data_query']] <-
          self$`data_query`
      }
      if (!is.null(self$`id`)) {
        AnalysisObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        AnalysisObject[['name']] <-
          self$`name`
      }

      AnalysisObject
    },
    fromJSON = function(AnalysisJson) {
      AnalysisObject <- jsonlite::fromJSON(AnalysisJson)
      if (!is.null(AnalysisObject$`data_query`)) {
        self$`data_query` <- AnalysisObject$`data_query`
      }
      if (!is.null(AnalysisObject$`id`)) {
        self$`id` <- AnalysisObject$`id`
      }
      if (!is.null(AnalysisObject$`name`)) {
        self$`name` <- AnalysisObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data_query`)) {
        sprintf(
        '"data_query":
          "%s"
                ',
        self$`data_query`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AnalysisJson) {
      AnalysisObject <- jsonlite::fromJSON(AnalysisJson)
      self$`data_query` <- AnalysisObject$`data_query`
      self$`id` <- AnalysisObject$`id`
      self$`name` <- AnalysisObject$`name`
      self
    }
  )
)
