# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AttributeBulkUpdate
#' @description AttributeBulkUpdate Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AttributeBulkUpdate <- R6::R6Class(
  'AttributeBulkUpdate',
  public = list(
    `attributes` = NULL,
    initialize = function(`attributes`, ...){
      local.optional.var <- list(...)
      if (!missing(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
    },
    toJSON = function() {
      AttributeBulkUpdateObject <- list()
      if (!is.null(self$`attributes`)) {
        AttributeBulkUpdateObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }

      AttributeBulkUpdateObject
    },
    fromJSON = function(AttributeBulkUpdateJson) {
      AttributeBulkUpdateObject <- jsonlite::fromJSON(AttributeBulkUpdateJson)
      if (!is.null(AttributeBulkUpdateObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(AttributeBulkUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AttributeBulkUpdateJson) {
      AttributeBulkUpdateObject <- jsonlite::fromJSON(AttributeBulkUpdateJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(AttributeBulkUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self
    }
  )
)
