# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AttributeType
#' @description AttributeType Class
#' @format An \code{R6Class} generator object
#' @field autocomplete  \link{AutocompleteService} [optional]
#'
#' @field choices  list( character ) [optional]
#'
#' @field default  \link{AnyType} [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character [optional]
#'
#' @field labels  list( character ) [optional]
#'
#' @field maximum  numeric [optional]
#'
#' @field minimum  numeric [optional]
#'
#' @field name  character [optional]
#'
#' @field order  integer [optional]
#'
#' @field required  character [optional]
#'
#' @field use_current  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AttributeType <- R6::R6Class(
  'AttributeType',
  public = list(
    `autocomplete` = NULL,
    `choices` = NULL,
    `default` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `labels` = NULL,
    `maximum` = NULL,
    `minimum` = NULL,
    `name` = NULL,
    `order` = NULL,
    `required` = NULL,
    `use_current` = NULL,
    initialize = function(`autocomplete`=NULL, `choices`=NULL, `default`=NULL, `description`='', `dtype`=NULL, `labels`=NULL, `maximum`=NULL, `minimum`=NULL, `name`=NULL, `order`=0, `required`=FALSE, `use_current`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`autocomplete`)) {
        stopifnot(R6::is.R6(`autocomplete`))
        self$`autocomplete` <- `autocomplete`
      }
      if (!is.null(`choices`)) {
        stopifnot(is.vector(`choices`), length(`choices`) != 0)
        sapply(`choices`, function(x) stopifnot(is.character(x)))
        self$`choices` <- `choices`
      }
      if (!is.null(`default`)) {
        allowed <- (is.logical(`default`)||is.numeric(`default`)||is.character(`default`)||is.vector(`default`))
        stopifnot(allowed)
        self$`default` <- `default`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!is.null(`labels`)) {
        stopifnot(is.vector(`labels`), length(`labels`) != 0)
        sapply(`labels`, function(x) stopifnot(is.character(x)))
        self$`labels` <- `labels`
      }
      if (!is.null(`maximum`)) {
        self$`maximum` <- `maximum`
      }
      if (!is.null(`minimum`)) {
        self$`minimum` <- `minimum`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`order`)) {
        stopifnot(is.numeric(`order`), length(`order`) == 1)
        self$`order` <- `order`
      }
      if (!is.null(`required`)) {
        self$`required` <- `required`
      }
      if (!is.null(`use_current`)) {
        self$`use_current` <- `use_current`
      }
    },
    toJSON = function() {
      AttributeTypeObject <- list()
      if (!is.null(self$`autocomplete`)) {
        AttributeTypeObject[['autocomplete']] <-
          self$`autocomplete`$toJSON()
      }
      if (!is.null(self$`choices`)) {
        AttributeTypeObject[['choices']] <-
          self$`choices`
      }
      if (!is.null(self$`default`)) {
        AttributeTypeObject[['default']] <-
          self$`default`
      }
      if (!is.null(self$`description`)) {
        AttributeTypeObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        AttributeTypeObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`labels`)) {
        AttributeTypeObject[['labels']] <-
          self$`labels`
      }
      if (!is.null(self$`maximum`)) {
        AttributeTypeObject[['maximum']] <-
          self$`maximum`
      }
      if (!is.null(self$`minimum`)) {
        AttributeTypeObject[['minimum']] <-
          self$`minimum`
      }
      if (!is.null(self$`name`)) {
        AttributeTypeObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`order`)) {
        AttributeTypeObject[['order']] <-
          self$`order`
      }
      if (!is.null(self$`required`)) {
        AttributeTypeObject[['required']] <-
          self$`required`
      }
      if (!is.null(self$`use_current`)) {
        AttributeTypeObject[['use_current']] <-
          self$`use_current`
      }

      AttributeTypeObject
    },
    fromJSON = function(AttributeTypeJson) {
      AttributeTypeObject <- jsonlite::fromJSON(AttributeTypeJson)
      if (!is.null(AttributeTypeObject$`autocomplete`)) {
        autocompleteObject <- AutocompleteService$new()
        autocompleteObject$fromJSON(jsonlite::toJSON(AttributeTypeObject$autocomplete, auto_unbox = TRUE, digits = NA))
        self$`autocomplete` <- autocompleteObject
      }
      if (!is.null(AttributeTypeObject$`choices`)) {
        self$`choices` <- ApiClient$new()$deserializeObj(AttributeTypeObject$`choices`, "array[character]", loadNamespace("tator"))
      }
      if (!is.null(AttributeTypeObject$`default`)) {
        defaultObject <- AnyType$new()
        defaultObject$fromJSON(jsonlite::toJSON(AttributeTypeObject$default, auto_unbox = TRUE, digits = NA))
        self$`default` <- defaultObject
      }
      if (!is.null(AttributeTypeObject$`description`)) {
        self$`description` <- AttributeTypeObject$`description`
      }
      if (!is.null(AttributeTypeObject$`dtype`)) {
        self$`dtype` <- AttributeTypeObject$`dtype`
      }
      if (!is.null(AttributeTypeObject$`labels`)) {
        self$`labels` <- ApiClient$new()$deserializeObj(AttributeTypeObject$`labels`, "array[character]", loadNamespace("tator"))
      }
      if (!is.null(AttributeTypeObject$`maximum`)) {
        self$`maximum` <- AttributeTypeObject$`maximum`
      }
      if (!is.null(AttributeTypeObject$`minimum`)) {
        self$`minimum` <- AttributeTypeObject$`minimum`
      }
      if (!is.null(AttributeTypeObject$`name`)) {
        self$`name` <- AttributeTypeObject$`name`
      }
      if (!is.null(AttributeTypeObject$`order`)) {
        self$`order` <- AttributeTypeObject$`order`
      }
      if (!is.null(AttributeTypeObject$`required`)) {
        self$`required` <- AttributeTypeObject$`required`
      }
      if (!is.null(AttributeTypeObject$`use_current`)) {
        self$`use_current` <- AttributeTypeObject$`use_current`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`autocomplete`)) {
        sprintf(
        '"autocomplete":
        %s
        ',
        jsonlite::toJSON(self$`autocomplete`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`choices`)) {
        sprintf(
        '"choices":
           [%s]
        ',
        paste(unlist(lapply(self$`choices`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`default`)) {
        sprintf(
        '"default":
        %s
        ',
        jsonlite::toJSON(self$`default`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`labels`)) {
        sprintf(
        '"labels":
           [%s]
        ',
        paste(unlist(lapply(self$`labels`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`maximum`)) {
        sprintf(
        '"maximum":
          %d
                ',
        self$`maximum`
        )},
        if (!is.null(self$`minimum`)) {
        sprintf(
        '"minimum":
          %d
                ',
        self$`minimum`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`order`)) {
        sprintf(
        '"order":
          %d
                ',
        self$`order`
        )},
        if (!is.null(self$`required`)) {
        sprintf(
        '"required":
          "%s"
                ',
        self$`required`
        )},
        if (!is.null(self$`use_current`)) {
        sprintf(
        '"use_current":
          "%s"
                ',
        self$`use_current`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AttributeTypeJson) {
      AttributeTypeObject <- jsonlite::fromJSON(AttributeTypeJson)
      self$`autocomplete` <- AutocompleteService$new()$fromJSON(jsonlite::toJSON(AttributeTypeObject$autocomplete, auto_unbox = TRUE, digits = NA))
      self$`choices` <- ApiClient$new()$deserializeObj(AttributeTypeObject$`choices`, "array[character]", loadNamespace("tator"))
      self$`default` <- AnyType$new()$fromJSON(jsonlite::toJSON(AttributeTypeObject$default, auto_unbox = TRUE, digits = NA))
      self$`description` <- AttributeTypeObject$`description`
      self$`dtype` <- AttributeTypeObject$`dtype`
      self$`labels` <- ApiClient$new()$deserializeObj(AttributeTypeObject$`labels`, "array[character]", loadNamespace("tator"))
      self$`maximum` <- AttributeTypeObject$`maximum`
      self$`minimum` <- AttributeTypeObject$`minimum`
      self$`name` <- AttributeTypeObject$`name`
      self$`order` <- AttributeTypeObject$`order`
      self$`required` <- AttributeTypeObject$`required`
      self$`use_current` <- AttributeTypeObject$`use_current`
      self
    }
  )
)
