# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AudioDefinition
#' @description AudioDefinition Class
#' @format An \code{R6Class} generator object
#' @field codec  character 
#'
#' @field codec_description  character [optional]
#'
#' @field codec_mime  character [optional]
#'
#' @field host  character [optional]
#'
#' @field http_auth  character [optional]
#'
#' @field path  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AudioDefinition <- R6::R6Class(
  'AudioDefinition',
  public = list(
    `codec` = NULL,
    `codec_description` = NULL,
    `codec_mime` = NULL,
    `host` = NULL,
    `http_auth` = NULL,
    `path` = NULL,
    initialize = function(`codec`, `codec_description`=NULL, `codec_mime`=NULL, `host`=NULL, `http_auth`=NULL, `path`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`codec`)) {
        stopifnot(is.character(`codec`), length(`codec`) == 1)
        self$`codec` <- `codec`
      }
      if (!is.null(`codec_description`)) {
        stopifnot(is.character(`codec_description`), length(`codec_description`) == 1)
        self$`codec_description` <- `codec_description`
      }
      if (!is.null(`codec_mime`)) {
        stopifnot(is.character(`codec_mime`), length(`codec_mime`) == 1)
        self$`codec_mime` <- `codec_mime`
      }
      if (!is.null(`host`)) {
        stopifnot(is.character(`host`), length(`host`) == 1)
        self$`host` <- `host`
      }
      if (!is.null(`http_auth`)) {
        stopifnot(is.character(`http_auth`), length(`http_auth`) == 1)
        self$`http_auth` <- `http_auth`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
    },
    toJSON = function() {
      AudioDefinitionObject <- list()
      if (!is.null(self$`codec`)) {
        AudioDefinitionObject[['codec']] <-
          self$`codec`
      }
      if (!is.null(self$`codec_description`)) {
        AudioDefinitionObject[['codec_description']] <-
          self$`codec_description`
      }
      if (!is.null(self$`codec_mime`)) {
        AudioDefinitionObject[['codec_mime']] <-
          self$`codec_mime`
      }
      if (!is.null(self$`host`)) {
        AudioDefinitionObject[['host']] <-
          self$`host`
      }
      if (!is.null(self$`http_auth`)) {
        AudioDefinitionObject[['http_auth']] <-
          self$`http_auth`
      }
      if (!is.null(self$`path`)) {
        AudioDefinitionObject[['path']] <-
          self$`path`
      }

      AudioDefinitionObject
    },
    fromJSON = function(AudioDefinitionJson) {
      AudioDefinitionObject <- jsonlite::fromJSON(AudioDefinitionJson)
      if (!is.null(AudioDefinitionObject$`codec`)) {
        self$`codec` <- AudioDefinitionObject$`codec`
      }
      if (!is.null(AudioDefinitionObject$`codec_description`)) {
        self$`codec_description` <- AudioDefinitionObject$`codec_description`
      }
      if (!is.null(AudioDefinitionObject$`codec_mime`)) {
        self$`codec_mime` <- AudioDefinitionObject$`codec_mime`
      }
      if (!is.null(AudioDefinitionObject$`host`)) {
        self$`host` <- AudioDefinitionObject$`host`
      }
      if (!is.null(AudioDefinitionObject$`http_auth`)) {
        self$`http_auth` <- AudioDefinitionObject$`http_auth`
      }
      if (!is.null(AudioDefinitionObject$`path`)) {
        self$`path` <- AudioDefinitionObject$`path`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`codec`)) {
        sprintf(
        '"codec":
          "%s"
                ',
        self$`codec`
        )},
        if (!is.null(self$`codec_description`)) {
        sprintf(
        '"codec_description":
          "%s"
                ',
        self$`codec_description`
        )},
        if (!is.null(self$`codec_mime`)) {
        sprintf(
        '"codec_mime":
          "%s"
                ',
        self$`codec_mime`
        )},
        if (!is.null(self$`host`)) {
        sprintf(
        '"host":
          "%s"
                ',
        self$`host`
        )},
        if (!is.null(self$`http_auth`)) {
        sprintf(
        '"http_auth":
          "%s"
                ',
        self$`http_auth`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AudioDefinitionJson) {
      AudioDefinitionObject <- jsonlite::fromJSON(AudioDefinitionJson)
      self$`codec` <- AudioDefinitionObject$`codec`
      self$`codec_description` <- AudioDefinitionObject$`codec_description`
      self$`codec_mime` <- AudioDefinitionObject$`codec_mime`
      self$`host` <- AudioDefinitionObject$`host`
      self$`http_auth` <- AudioDefinitionObject$`http_auth`
      self$`path` <- AudioDefinitionObject$`path`
      self
    }
  )
)
