# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title AutocompleteService
#' @description AutocompleteService Class
#' @format An \code{R6Class} generator object
#' @field serviceUrl  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
AutocompleteService <- R6::R6Class(
  'AutocompleteService',
  public = list(
    `serviceUrl` = NULL,
    initialize = function(`serviceUrl`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`serviceUrl`)) {
        stopifnot(is.character(`serviceUrl`), length(`serviceUrl`) == 1)
        self$`serviceUrl` <- `serviceUrl`
      }
    },
    toJSON = function() {
      AutocompleteServiceObject <- list()
      if (!is.null(self$`serviceUrl`)) {
        AutocompleteServiceObject[['serviceUrl']] <-
          self$`serviceUrl`
      }

      AutocompleteServiceObject
    },
    fromJSON = function(AutocompleteServiceJson) {
      AutocompleteServiceObject <- jsonlite::fromJSON(AutocompleteServiceJson)
      if (!is.null(AutocompleteServiceObject$`serviceUrl`)) {
        self$`serviceUrl` <- AutocompleteServiceObject$`serviceUrl`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`serviceUrl`)) {
        sprintf(
        '"serviceUrl":
          "%s"
                ',
        self$`serviceUrl`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(AutocompleteServiceJson) {
      AutocompleteServiceObject <- jsonlite::fromJSON(AutocompleteServiceJson)
      self$`serviceUrl` <- AutocompleteServiceObject$`serviceUrl`
      self
    }
  )
)
