# coding: utf-8

# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech


import pprint
import re  # noqa: F401

import six

from tator.configuration import Configuration


class AutocompleteService(object):
    """
    """

    """
    Attributes:
      openapi_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    openapi_types = {
        'serviceUrl': 'character'
    }

    attribute_map = {
        'serviceUrl': 'serviceUrl'
    }

    def __init__(self, serviceUrl=None, local_vars_configuration=None):  # noqa: E501
        """AutocompleteService - a model defined in OpenAPI"""
        if local_vars_configuration is None:
            local_vars_configuration = Configuration()
        self.local_vars_configuration = local_vars_configuration

        self._serviceUrl = None
        self.discriminator = None

        if serviceUrl is not None:
            self.serviceUrl = serviceUrl

    @property
    def serviceUrl(self):
        """
        URL of the autocomplete service.

        :return: The serviceUrl of this AutocompleteService. 
        :rtype: character
        """
        return self._serviceUrl

    @serviceUrl.setter
    def serviceUrl(self, serviceUrl):
        """
        URL of the autocomplete service.

        :param serviceUrl: The serviceUrl of this AutocompleteService.
        :type: character
        """

        self._serviceUrl = serviceUrl

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.openapi_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AutocompleteService):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, AutocompleteService):
            return True

        return self.to_dict() != other.to_dict()
