# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title BadRequestResponse
#' @description BadRequestResponse Class
#' @format An \code{R6Class} generator object
#' @field details  character [optional]
#'
#' @field message  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
BadRequestResponse <- R6::R6Class(
  'BadRequestResponse',
  public = list(
    `details` = NULL,
    `message` = NULL,
    initialize = function(`details`=NULL, `message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`details`)) {
        stopifnot(is.character(`details`), length(`details`) == 1)
        self$`details` <- `details`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      BadRequestResponseObject <- list()
      if (!is.null(self$`details`)) {
        BadRequestResponseObject[['details']] <-
          self$`details`
      }
      if (!is.null(self$`message`)) {
        BadRequestResponseObject[['message']] <-
          self$`message`
      }

      BadRequestResponseObject
    },
    fromJSON = function(BadRequestResponseJson) {
      BadRequestResponseObject <- jsonlite::fromJSON(BadRequestResponseJson)
      if (!is.null(BadRequestResponseObject$`details`)) {
        self$`details` <- BadRequestResponseObject$`details`
      }
      if (!is.null(BadRequestResponseObject$`message`)) {
        self$`message` <- BadRequestResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`details`)) {
        sprintf(
        '"details":
          "%s"
                ',
        self$`details`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(BadRequestResponseJson) {
      BadRequestResponseObject <- jsonlite::fromJSON(BadRequestResponseJson)
      self$`details` <- BadRequestResponseObject$`details`
      self$`message` <- BadRequestResponseObject$`message`
      self
    }
  )
)
