# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ColorMap
#' @description ColorMap Class
#' @format An \code{R6Class} generator object
#' @field alpha_ranges  named list( \link{array[numeric]} ) [optional]
#'
#' @field default  \link{AnyType} [optional]
#'
#' @field key  character [optional]
#'
#' @field map  named list( \link{AnyType} ) [optional]
#'
#' @field version  named list( \link{AnyType} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ColorMap <- R6::R6Class(
  'ColorMap',
  public = list(
    `alpha_ranges` = NULL,
    `default` = NULL,
    `key` = NULL,
    `map` = NULL,
    `version` = NULL,
    initialize = function(`alpha_ranges`=NULL, `default`=NULL, `key`=NULL, `map`=NULL, `version`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`alpha_ranges`)) {
        stopifnot(is.vector(`alpha_ranges`), length(`alpha_ranges`) != 0)
        sapply(`alpha_ranges`, function(x) stopifnot(is.double(x)))
        self$`alpha_ranges` <- `alpha_ranges`
      }
      if (!is.null(`default`)) {
        stopifnot(is.vector(`default`), length(`default`) != 0)
        self$`default` <- `default`
      }
      if (!is.null(`key`)) {
        stopifnot(is.character(`key`), length(`key`) == 1)
        self$`key` <- `key`
      }
      if (!is.null(`map`)) {
        stopifnot(is.vector(`map`), length(`map`) != 0)
        sapply(`map`, function(x) stopifnot(is.double(x)))
        self$`map` <- `map`
      }
      if (!is.null(`version`)) {
        stopifnot(is.vector(`version`), length(`version`) != 0)
        sapply(`version`, function(x) stopifnot(is.double(x)))
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      ColorMapObject <- list()
      if (!is.null(self$`alpha_ranges`)) {
        ColorMapObject[['alpha_ranges']] <-
          self$`alpha_ranges`
      }
      if (!is.null(self$`default`)) {
        ColorMapObject[['default']] <-
          self$`default`
      }
      if (!is.null(self$`key`)) {
        ColorMapObject[['key']] <-
          self$`key`
      }
      if (!is.null(self$`map`)) {
        ColorMapObject[['map']] <-
          self$`map`
      }
      if (!is.null(self$`version`)) {
        ColorMapObject[['version']] <-
          self$`version`
      }

      ColorMapObject
    },
    fromJSON = function(ColorMapJson) {
      ColorMapObject <- jsonlite::fromJSON(ColorMapJson)
      if (!is.null(ColorMapObject$`alpha_ranges`)) {
        self$`alpha_ranges` <- ApiClient$new()$deserializeObj(ColorMapObject$`alpha_ranges`, "map(Array)", loadNamespace("tator"))
      }
      if (!is.null(ColorMapObject$`default`)) {
        defaultObject <- AnyType$new()
        defaultObject$fromJSON(jsonlite::toJSON(ColorMapObject$default, auto_unbox = TRUE, digits = NA))
        self$`default` <- defaultObject
      }
      if (!is.null(ColorMapObject$`key`)) {
        self$`key` <- ColorMapObject$`key`
      }
      if (!is.null(ColorMapObject$`map`)) {
        self$`map` <- ApiClient$new()$deserializeObj(ColorMapObject$`map`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(ColorMapObject$`version`)) {
        self$`version` <- ApiClient$new()$deserializeObj(ColorMapObject$`version`, "map(AnyType)", loadNamespace("tator"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`alpha_ranges`)) {
        sprintf(
        '"alpha_ranges":
        %s
',
        jsonlite::toJSON(self$`alpha_ranges`, auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`default`)) {
        sprintf(
        '"default":
        %s
        ',
        jsonlite::toJSON(self$`default`, auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`key`)) {
        sprintf(
        '"key":
          "%s"
                ',
        self$`key`
        )},
        if (!is.null(self$`map`)) {
        sprintf(
        '"map":
        %s
',
        jsonlite::toJSON(self$`map`, auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
        %s
',
        jsonlite::toJSON(self$`version`, auto_unbox = TRUE, digits=NA)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ColorMapJson) {
      ColorMapObject <- jsonlite::fromJSON(ColorMapJson)
      self$`alpha_ranges` <- ApiClient$new()$deserializeObj(ColorMapObject$`alpha_ranges`, "map(Array)", loadNamespace("tator"))
      self$`default` <- AnyType$new()$fromJSON(jsonlite::toJSON(ColorMapObject$default, auto_unbox = TRUE, digits = NA))
      self$`key` <- ColorMapObject$`key`
      self$`map` <- ApiClient$new()$deserializeObj(ColorMapObject$`map`, "map(AnyType)", loadNamespace("tator"))
      self$`version` <- ApiClient$new()$deserializeObj(ColorMapObject$`version`, "map(AnyType)", loadNamespace("tator"))
      self
    }
  )
)
