# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreateResponse
#' @description CreateResponse Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field message  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreateResponse <- R6::R6Class(
  'CreateResponse',
  public = list(
    `id` = NULL,
    `message` = NULL,
    initialize = function(`id`=NULL, `message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      CreateResponseObject <- list()
      if (!is.null(self$`id`)) {
        CreateResponseObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`message`)) {
        CreateResponseObject[['message']] <-
          self$`message`
      }

      CreateResponseObject
    },
    fromJSON = function(CreateResponseJson) {
      CreateResponseObject <- jsonlite::fromJSON(CreateResponseJson)
      if (!is.null(CreateResponseObject$`id`)) {
        self$`id` <- CreateResponseObject$`id`
      }
      if (!is.null(CreateResponseObject$`message`)) {
        self$`message` <- CreateResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreateResponseJson) {
      CreateResponseObject <- jsonlite::fromJSON(CreateResponseJson)
      self$`id` <- CreateResponseObject$`id`
      self$`message` <- CreateResponseObject$`message`
      self
    }
  )
)
