# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title CreateListResponse
#' @description CreateListResponse Class
#' @format An \code{R6Class} generator object
#' @field id  list( integer ) [optional]
#'
#' @field message  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
CreateListResponse <- R6::R6Class(
  'CreateListResponse',
  public = list(
    `id` = NULL,
    `message` = NULL,
    initialize = function(`id`=NULL, `message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.vector(`id`), length(`id`) != 0)
        sapply(`id`, function(x) stopifnot(is.character(x)))
        self$`id` <- `id`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      CreateListResponseObject <- list()
      if (!is.null(self$`id`)) {
        CreateListResponseObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`message`)) {
        CreateListResponseObject[['message']] <-
          self$`message`
      }

      CreateListResponseObject
    },
    fromJSON = function(CreateListResponseJson) {
      CreateListResponseObject <- jsonlite::fromJSON(CreateListResponseJson)
      if (!is.null(CreateListResponseObject$`id`)) {
        self$`id` <- ApiClient$new()$deserializeObj(CreateListResponseObject$`id`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(CreateListResponseObject$`message`)) {
        self$`message` <- CreateListResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
           [%s]
        ',
        paste(unlist(lapply(self$`id`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CreateListResponseJson) {
      CreateListResponseObject <- jsonlite::fromJSON(CreateListResponseJson)
      self$`id` <- ApiClient$new()$deserializeObj(CreateListResponseObject$`id`, "array[integer]", loadNamespace("tator"))
      self$`message` <- CreateListResponseObject$`message`
      self
    }
  )
)
