# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Credentials
#' @description Credentials Class
#' @format An \code{R6Class} generator object
#' @field password  character 
#'
#' @field username  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Credentials <- R6::R6Class(
  'Credentials',
  public = list(
    `password` = NULL,
    `username` = NULL,
    initialize = function(`password`, `username`, ...){
      local.optional.var <- list(...)
      if (!missing(`password`)) {
        stopifnot(is.character(`password`), length(`password`) == 1)
        self$`password` <- `password`
      }
      if (!missing(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
    },
    toJSON = function() {
      CredentialsObject <- list()
      if (!is.null(self$`password`)) {
        CredentialsObject[['password']] <-
          self$`password`
      }
      if (!is.null(self$`username`)) {
        CredentialsObject[['username']] <-
          self$`username`
      }

      CredentialsObject
    },
    fromJSON = function(CredentialsJson) {
      CredentialsObject <- jsonlite::fromJSON(CredentialsJson)
      if (!is.null(CredentialsObject$`password`)) {
        self$`password` <- CredentialsObject$`password`
      }
      if (!is.null(CredentialsObject$`username`)) {
        self$`username` <- CredentialsObject$`username`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`password`)) {
        sprintf(
        '"password":
          "%s"
                ',
        self$`password`
        )},
        if (!is.null(self$`username`)) {
        sprintf(
        '"username":
          "%s"
                ',
        self$`username`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(CredentialsJson) {
      CredentialsObject <- jsonlite::fromJSON(CredentialsJson)
      self$`password` <- CredentialsObject$`password`
      self$`username` <- CredentialsObject$`username`
      self
    }
  )
)
