# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ImageSpec
#' @description ImageSpec Class
#' @format An \code{R6Class} generator object
#' @field gid  character 
#'
#' @field md5  character 
#'
#' @field name  character 
#'
#' @field section  character 
#'
#' @field thumbnail_url  character [optional]
#'
#' @field type  integer 
#'
#' @field uid  character 
#'
#' @field url  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ImageSpec <- R6::R6Class(
  'ImageSpec',
  public = list(
    `gid` = NULL,
    `md5` = NULL,
    `name` = NULL,
    `section` = NULL,
    `thumbnail_url` = NULL,
    `type` = NULL,
    `uid` = NULL,
    `url` = NULL,
    initialize = function(`gid`, `md5`, `name`, `section`, `type`, `uid`, `url`, `thumbnail_url`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!missing(`md5`)) {
        stopifnot(is.character(`md5`), length(`md5`) == 1)
        self$`md5` <- `md5`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`section`)) {
        stopifnot(is.character(`section`), length(`section`) == 1)
        self$`section` <- `section`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`uid`)) {
        stopifnot(is.character(`uid`), length(`uid`) == 1)
        self$`uid` <- `uid`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!is.null(`thumbnail_url`)) {
        stopifnot(is.character(`thumbnail_url`), length(`thumbnail_url`) == 1)
        self$`thumbnail_url` <- `thumbnail_url`
      }
    },
    toJSON = function() {
      ImageSpecObject <- list()
      if (!is.null(self$`gid`)) {
        ImageSpecObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`md5`)) {
        ImageSpecObject[['md5']] <-
          self$`md5`
      }
      if (!is.null(self$`name`)) {
        ImageSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`section`)) {
        ImageSpecObject[['section']] <-
          self$`section`
      }
      if (!is.null(self$`thumbnail_url`)) {
        ImageSpecObject[['thumbnail_url']] <-
          self$`thumbnail_url`
      }
      if (!is.null(self$`type`)) {
        ImageSpecObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`uid`)) {
        ImageSpecObject[['uid']] <-
          self$`uid`
      }
      if (!is.null(self$`url`)) {
        ImageSpecObject[['url']] <-
          self$`url`
      }

      ImageSpecObject
    },
    fromJSON = function(ImageSpecJson) {
      ImageSpecObject <- jsonlite::fromJSON(ImageSpecJson)
      if (!is.null(ImageSpecObject$`gid`)) {
        self$`gid` <- ImageSpecObject$`gid`
      }
      if (!is.null(ImageSpecObject$`md5`)) {
        self$`md5` <- ImageSpecObject$`md5`
      }
      if (!is.null(ImageSpecObject$`name`)) {
        self$`name` <- ImageSpecObject$`name`
      }
      if (!is.null(ImageSpecObject$`section`)) {
        self$`section` <- ImageSpecObject$`section`
      }
      if (!is.null(ImageSpecObject$`thumbnail_url`)) {
        self$`thumbnail_url` <- ImageSpecObject$`thumbnail_url`
      }
      if (!is.null(ImageSpecObject$`type`)) {
        self$`type` <- ImageSpecObject$`type`
      }
      if (!is.null(ImageSpecObject$`uid`)) {
        self$`uid` <- ImageSpecObject$`uid`
      }
      if (!is.null(ImageSpecObject$`url`)) {
        self$`url` <- ImageSpecObject$`url`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`md5`)) {
        sprintf(
        '"md5":
          "%s"
                ',
        self$`md5`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`section`)) {
        sprintf(
        '"section":
          "%s"
                ',
        self$`section`
        )},
        if (!is.null(self$`thumbnail_url`)) {
        sprintf(
        '"thumbnail_url":
          "%s"
                ',
        self$`thumbnail_url`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )},
        if (!is.null(self$`uid`)) {
        sprintf(
        '"uid":
          "%s"
                ',
        self$`uid`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ImageSpecJson) {
      ImageSpecObject <- jsonlite::fromJSON(ImageSpecJson)
      self$`gid` <- ImageSpecObject$`gid`
      self$`md5` <- ImageSpecObject$`md5`
      self$`name` <- ImageSpecObject$`name`
      self$`section` <- ImageSpecObject$`section`
      self$`thumbnail_url` <- ImageSpecObject$`thumbnail_url`
      self$`type` <- ImageSpecObject$`type`
      self$`uid` <- ImageSpecObject$`uid`
      self$`url` <- ImageSpecObject$`url`
      self
    }
  )
)
