# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Leaf
#' @description Leaf Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field id  integer [optional]
#'
#' @field name  character [optional]
#'
#' @field parent  integer [optional]
#'
#' @field path  character [optional]
#'
#' @field project  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Leaf <- R6::R6Class(
  'Leaf',
  public = list(
    `attributes` = NULL,
    `id` = NULL,
    `name` = NULL,
    `parent` = NULL,
    `path` = NULL,
    `project` = NULL,
    initialize = function(`attributes`=NULL, `id`=NULL, `name`=NULL, `parent`=NULL, `path`=NULL, `project`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`parent`)) {
        stopifnot(is.numeric(`parent`), length(`parent`) == 1)
        self$`parent` <- `parent`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
    },
    toJSON = function() {
      LeafObject <- list()
      if (!is.null(self$`attributes`)) {
        LeafObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`id`)) {
        LeafObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        LeafObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`parent`)) {
        LeafObject[['parent']] <-
          self$`parent`
      }
      if (!is.null(self$`path`)) {
        LeafObject[['path']] <-
          self$`path`
      }
      if (!is.null(self$`project`)) {
        LeafObject[['project']] <-
          self$`project`
      }

      LeafObject
    },
    fromJSON = function(LeafJson) {
      LeafObject <- jsonlite::fromJSON(LeafJson)
      if (!is.null(LeafObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(LeafObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(LeafObject$`id`)) {
        self$`id` <- LeafObject$`id`
      }
      if (!is.null(LeafObject$`name`)) {
        self$`name` <- LeafObject$`name`
      }
      if (!is.null(LeafObject$`parent`)) {
        self$`parent` <- LeafObject$`parent`
      }
      if (!is.null(LeafObject$`path`)) {
        self$`path` <- LeafObject$`path`
      }
      if (!is.null(LeafObject$`project`)) {
        self$`project` <- LeafObject$`project`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`parent`)) {
        sprintf(
        '"parent":
          %d
                ',
        self$`parent`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafJson) {
      LeafObject <- jsonlite::fromJSON(LeafJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(LeafObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`id` <- LeafObject$`id`
      self$`name` <- LeafObject$`name`
      self$`parent` <- LeafObject$`parent`
      self$`path` <- LeafObject$`path`
      self$`project` <- LeafObject$`project`
      self
    }
  )
)
