# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LeafUpdate
#' @description LeafUpdate Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LeafUpdate <- R6::R6Class(
  'LeafUpdate',
  public = list(
    `attributes` = NULL,
    `name` = NULL,
    initialize = function(`attributes`=NULL, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      LeafUpdateObject <- list()
      if (!is.null(self$`attributes`)) {
        LeafUpdateObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`name`)) {
        LeafUpdateObject[['name']] <-
          self$`name`
      }

      LeafUpdateObject
    },
    fromJSON = function(LeafUpdateJson) {
      LeafUpdateObject <- jsonlite::fromJSON(LeafUpdateJson)
      if (!is.null(LeafUpdateObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(LeafUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(LeafUpdateObject$`name`)) {
        self$`name` <- LeafUpdateObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafUpdateJson) {
      LeafUpdateObject <- jsonlite::fromJSON(LeafUpdateJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(LeafUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`name` <- LeafUpdateObject$`name`
      self
    }
  )
)
