# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LeafTypeSpec
#' @description LeafTypeSpec Class
#' @format An \code{R6Class} generator object
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field description  character [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LeafTypeSpec <- R6::R6Class(
  'LeafTypeSpec',
  public = list(
    `attribute_types` = NULL,
    `description` = NULL,
    `name` = NULL,
    initialize = function(`attribute_types`=NULL, `description`='', `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      LeafTypeSpecObject <- list()
      if (!is.null(self$`attribute_types`)) {
        LeafTypeSpecObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`description`)) {
        LeafTypeSpecObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`name`)) {
        LeafTypeSpecObject[['name']] <-
          self$`name`
      }

      LeafTypeSpecObject
    },
    fromJSON = function(LeafTypeSpecJson) {
      LeafTypeSpecObject <- jsonlite::fromJSON(LeafTypeSpecJson)
      if (!is.null(LeafTypeSpecObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(LeafTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(LeafTypeSpecObject$`description`)) {
        self$`description` <- LeafTypeSpecObject$`description`
      }
      if (!is.null(LeafTypeSpecObject$`name`)) {
        self$`name` <- LeafTypeSpecObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafTypeSpecJson) {
      LeafTypeSpecObject <- jsonlite::fromJSON(LeafTypeSpecJson)
      self$`attribute_types` <- ApiClient$new()$deserializeObj(LeafTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`description` <- LeafTypeSpecObject$`description`
      self$`name` <- LeafTypeSpecObject$`name`
      self
    }
  )
)
