# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LeafTypeUpdate
#' @description LeafTypeUpdate Class
#' @format An \code{R6Class} generator object
#' @field description  character [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LeafTypeUpdate <- R6::R6Class(
  'LeafTypeUpdate',
  public = list(
    `description` = NULL,
    `name` = NULL,
    initialize = function(`description`='', `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      LeafTypeUpdateObject <- list()
      if (!is.null(self$`description`)) {
        LeafTypeUpdateObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`name`)) {
        LeafTypeUpdateObject[['name']] <-
          self$`name`
      }

      LeafTypeUpdateObject
    },
    fromJSON = function(LeafTypeUpdateJson) {
      LeafTypeUpdateObject <- jsonlite::fromJSON(LeafTypeUpdateJson)
      if (!is.null(LeafTypeUpdateObject$`description`)) {
        self$`description` <- LeafTypeUpdateObject$`description`
      }
      if (!is.null(LeafTypeUpdateObject$`name`)) {
        self$`name` <- LeafTypeUpdateObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafTypeUpdateJson) {
      LeafTypeUpdateObject <- jsonlite::fromJSON(LeafTypeUpdateJson)
      self$`description` <- LeafTypeUpdateObject$`description`
      self$`name` <- LeafTypeUpdateObject$`name`
      self
    }
  )
)
