# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LeafSpec
#' @description LeafSpec Class
#' @format An \code{R6Class} generator object
#' @field name  character 
#'
#' @field parent  integer [optional]
#'
#' @field type  integer 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LeafSpec <- R6::R6Class(
  'LeafSpec',
  public = list(
    `name` = NULL,
    `parent` = NULL,
    `type` = NULL,
    initialize = function(`name`, `type`, `parent`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`parent`)) {
        stopifnot(is.numeric(`parent`), length(`parent`) == 1)
        self$`parent` <- `parent`
      }
    },
    toJSON = function() {
      LeafSpecObject <- list()
      if (!is.null(self$`name`)) {
        LeafSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`parent`)) {
        LeafSpecObject[['parent']] <-
          self$`parent`
      }
      if (!is.null(self$`type`)) {
        LeafSpecObject[['type']] <-
          self$`type`
      }

      LeafSpecObject
    },
    fromJSON = function(LeafSpecJson) {
      LeafSpecObject <- jsonlite::fromJSON(LeafSpecJson)
      if (!is.null(LeafSpecObject$`name`)) {
        self$`name` <- LeafSpecObject$`name`
      }
      if (!is.null(LeafSpecObject$`parent`)) {
        self$`parent` <- LeafSpecObject$`parent`
      }
      if (!is.null(LeafSpecObject$`type`)) {
        self$`type` <- LeafSpecObject$`type`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`parent`)) {
        sprintf(
        '"parent":
          %d
                ',
        self$`parent`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafSpecJson) {
      LeafSpecObject <- jsonlite::fromJSON(LeafSpecJson)
      self$`name` <- LeafSpecObject$`name`
      self$`parent` <- LeafSpecObject$`parent`
      self$`type` <- LeafSpecObject$`type`
      self
    }
  )
)
