# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LeafSuggestion
#' @description LeafSuggestion Class
#' @format An \code{R6Class} generator object
#' @field data  named list( \link{AnyType} ) [optional]
#'
#' @field group  character [optional]
#'
#' @field value  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LeafSuggestion <- R6::R6Class(
  'LeafSuggestion',
  public = list(
    `data` = NULL,
    `group` = NULL,
    `value` = NULL,
    initialize = function(`data`=NULL, `group`=NULL, `value`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`data`)) {
        stopifnot(is.vector(`data`), length(`data`) != 0)
        sapply(`data`, function(x) stopifnot(R6::is.R6(x)))
        self$`data` <- `data`
      }
      if (!is.null(`group`)) {
        stopifnot(is.character(`group`), length(`group`) == 1)
        self$`group` <- `group`
      }
      if (!is.null(`value`)) {
        stopifnot(is.character(`value`), length(`value`) == 1)
        self$`value` <- `value`
      }
    },
    toJSON = function() {
      LeafSuggestionObject <- list()
      if (!is.null(self$`data`)) {
        LeafSuggestionObject[['data']] <-
          lapply(self$`data`, function(x) x$toJSON())
      }
      if (!is.null(self$`group`)) {
        LeafSuggestionObject[['group']] <-
          self$`group`
      }
      if (!is.null(self$`value`)) {
        LeafSuggestionObject[['value']] <-
          self$`value`
      }

      LeafSuggestionObject
    },
    fromJSON = function(LeafSuggestionJson) {
      LeafSuggestionObject <- jsonlite::fromJSON(LeafSuggestionJson)
      if (!is.null(LeafSuggestionObject$`data`)) {
        self$`data` <- ApiClient$new()$deserializeObj(LeafSuggestionObject$`data`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(LeafSuggestionObject$`group`)) {
        self$`group` <- LeafSuggestionObject$`group`
      }
      if (!is.null(LeafSuggestionObject$`value`)) {
        self$`value` <- LeafSuggestionObject$`value`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`data`)) {
        sprintf(
        '"data":
        %s
',
        jsonlite::toJSON(lapply(self$`data`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`group`)) {
        sprintf(
        '"group":
          "%s"
                ',
        self$`group`
        )},
        if (!is.null(self$`value`)) {
        sprintf(
        '"value":
          "%s"
                ',
        self$`value`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafSuggestionJson) {
      LeafSuggestionObject <- jsonlite::fromJSON(LeafSuggestionJson)
      self$`data` <- ApiClient$new()$deserializeObj(LeafSuggestionObject$`data`, "map(AnyType)", loadNamespace("tator"))
      self$`group` <- LeafSuggestionObject$`group`
      self$`value` <- LeafSuggestionObject$`value`
      self
    }
  )
)
