# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LeafType
#' @description LeafType Class
#' @format An \code{R6Class} generator object
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field name  character [optional]
#'
#' @field project  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LeafType <- R6::R6Class(
  'LeafType',
  public = list(
    `attribute_types` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `id` = NULL,
    `name` = NULL,
    `project` = NULL,
    initialize = function(`attribute_types`=NULL, `description`='', `dtype`=NULL, `id`=NULL, `name`=NULL, `project`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
    },
    toJSON = function() {
      LeafTypeObject <- list()
      if (!is.null(self$`attribute_types`)) {
        LeafTypeObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`description`)) {
        LeafTypeObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        LeafTypeObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`id`)) {
        LeafTypeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        LeafTypeObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`project`)) {
        LeafTypeObject[['project']] <-
          self$`project`
      }

      LeafTypeObject
    },
    fromJSON = function(LeafTypeJson) {
      LeafTypeObject <- jsonlite::fromJSON(LeafTypeJson)
      if (!is.null(LeafTypeObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(LeafTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(LeafTypeObject$`description`)) {
        self$`description` <- LeafTypeObject$`description`
      }
      if (!is.null(LeafTypeObject$`dtype`)) {
        self$`dtype` <- LeafTypeObject$`dtype`
      }
      if (!is.null(LeafTypeObject$`id`)) {
        self$`id` <- LeafTypeObject$`id`
      }
      if (!is.null(LeafTypeObject$`name`)) {
        self$`name` <- LeafTypeObject$`name`
      }
      if (!is.null(LeafTypeObject$`project`)) {
        self$`project` <- LeafTypeObject$`project`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LeafTypeJson) {
      LeafTypeObject <- jsonlite::fromJSON(LeafTypeJson)
      self$`attribute_types` <- ApiClient$new()$deserializeObj(LeafTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`description` <- LeafTypeObject$`description`
      self$`dtype` <- LeafTypeObject$`dtype`
      self$`id` <- LeafTypeObject$`id`
      self$`name` <- LeafTypeObject$`name`
      self$`project` <- LeafTypeObject$`project`
      self
    }
  )
)
