# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LocalizationTypeUpdate
#' @description LocalizationTypeUpdate Class
#' @format An \code{R6Class} generator object
#' @field colorMap  \link{ColorMap} [optional]
#'
#' @field description  character [optional]
#'
#' @field line_width  integer [optional]
#'
#' @field name  character [optional]
#'
#' @field visible  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LocalizationTypeUpdate <- R6::R6Class(
  'LocalizationTypeUpdate',
  public = list(
    `colorMap` = NULL,
    `description` = NULL,
    `line_width` = NULL,
    `name` = NULL,
    `visible` = NULL,
    initialize = function(`colorMap`=NULL, `description`=NULL, `line_width`=NULL, `name`=NULL, `visible`=TRUE, ...){
      local.optional.var <- list(...)
      if (!is.null(`colorMap`)) {
        stopifnot(R6::is.R6(`colorMap`))
        self$`colorMap` <- `colorMap`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`line_width`)) {
        stopifnot(is.numeric(`line_width`), length(`line_width`) == 1)
        self$`line_width` <- `line_width`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`visible`)) {
        self$`visible` <- `visible`
      }
    },
    toJSON = function() {
      LocalizationTypeUpdateObject <- list()
      if (!is.null(self$`colorMap`)) {
        LocalizationTypeUpdateObject[['colorMap']] <-
          self$`colorMap`$toJSON()
      }
      if (!is.null(self$`description`)) {
        LocalizationTypeUpdateObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`line_width`)) {
        LocalizationTypeUpdateObject[['line_width']] <-
          self$`line_width`
      }
      if (!is.null(self$`name`)) {
        LocalizationTypeUpdateObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`visible`)) {
        LocalizationTypeUpdateObject[['visible']] <-
          self$`visible`
      }

      LocalizationTypeUpdateObject
    },
    fromJSON = function(LocalizationTypeUpdateJson) {
      LocalizationTypeUpdateObject <- jsonlite::fromJSON(LocalizationTypeUpdateJson)
      if (!is.null(LocalizationTypeUpdateObject$`colorMap`)) {
        colorMapObject <- ColorMap$new()
        colorMapObject$fromJSON(jsonlite::toJSON(LocalizationTypeUpdateObject$colorMap, auto_unbox = TRUE, digits = NA))
        self$`colorMap` <- colorMapObject
      }
      if (!is.null(LocalizationTypeUpdateObject$`description`)) {
        self$`description` <- LocalizationTypeUpdateObject$`description`
      }
      if (!is.null(LocalizationTypeUpdateObject$`line_width`)) {
        self$`line_width` <- LocalizationTypeUpdateObject$`line_width`
      }
      if (!is.null(LocalizationTypeUpdateObject$`name`)) {
        self$`name` <- LocalizationTypeUpdateObject$`name`
      }
      if (!is.null(LocalizationTypeUpdateObject$`visible`)) {
        self$`visible` <- LocalizationTypeUpdateObject$`visible`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`colorMap`)) {
        sprintf(
        '"colorMap":
        %s
        ',
        jsonlite::toJSON(self$`colorMap`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`line_width`)) {
        sprintf(
        '"line_width":
          %d
                ',
        self$`line_width`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`visible`)) {
        sprintf(
        '"visible":
          "%s"
                ',
        self$`visible`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalizationTypeUpdateJson) {
      LocalizationTypeUpdateObject <- jsonlite::fromJSON(LocalizationTypeUpdateJson)
      self$`colorMap` <- ColorMap$new()$fromJSON(jsonlite::toJSON(LocalizationTypeUpdateObject$colorMap, auto_unbox = TRUE, digits = NA))
      self$`description` <- LocalizationTypeUpdateObject$`description`
      self$`line_width` <- LocalizationTypeUpdateObject$`line_width`
      self$`name` <- LocalizationTypeUpdateObject$`name`
      self$`visible` <- LocalizationTypeUpdateObject$`visible`
      self
    }
  )
)
