# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LocalizationType
#' @description LocalizationType Class
#' @format An \code{R6Class} generator object
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field colorMap  \link{ColorMap} [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field line_width  integer [optional]
#'
#' @field media  list( integer ) [optional]
#'
#' @field name  character [optional]
#'
#' @field project  integer [optional]
#'
#' @field visible  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LocalizationType <- R6::R6Class(
  'LocalizationType',
  public = list(
    `attribute_types` = NULL,
    `colorMap` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `id` = NULL,
    `line_width` = NULL,
    `media` = NULL,
    `name` = NULL,
    `project` = NULL,
    `visible` = NULL,
    initialize = function(`attribute_types`=NULL, `colorMap`=NULL, `description`=NULL, `dtype`=NULL, `id`=NULL, `line_width`=NULL, `media`=NULL, `name`=NULL, `project`=NULL, `visible`=TRUE, ...){
      local.optional.var <- list(...)
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`colorMap`)) {
        stopifnot(R6::is.R6(`colorMap`))
        self$`colorMap` <- `colorMap`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`line_width`)) {
        stopifnot(is.numeric(`line_width`), length(`line_width`) == 1)
        self$`line_width` <- `line_width`
      }
      if (!is.null(`media`)) {
        stopifnot(is.vector(`media`), length(`media`) != 0)
        sapply(`media`, function(x) stopifnot(is.character(x)))
        self$`media` <- `media`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`visible`)) {
        self$`visible` <- `visible`
      }
    },
    toJSON = function() {
      LocalizationTypeObject <- list()
      if (!is.null(self$`attribute_types`)) {
        LocalizationTypeObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`colorMap`)) {
        LocalizationTypeObject[['colorMap']] <-
          self$`colorMap`$toJSON()
      }
      if (!is.null(self$`description`)) {
        LocalizationTypeObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        LocalizationTypeObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`id`)) {
        LocalizationTypeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`line_width`)) {
        LocalizationTypeObject[['line_width']] <-
          self$`line_width`
      }
      if (!is.null(self$`media`)) {
        LocalizationTypeObject[['media']] <-
          self$`media`
      }
      if (!is.null(self$`name`)) {
        LocalizationTypeObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`project`)) {
        LocalizationTypeObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`visible`)) {
        LocalizationTypeObject[['visible']] <-
          self$`visible`
      }

      LocalizationTypeObject
    },
    fromJSON = function(LocalizationTypeJson) {
      LocalizationTypeObject <- jsonlite::fromJSON(LocalizationTypeJson)
      if (!is.null(LocalizationTypeObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(LocalizationTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(LocalizationTypeObject$`colorMap`)) {
        colorMapObject <- ColorMap$new()
        colorMapObject$fromJSON(jsonlite::toJSON(LocalizationTypeObject$colorMap, auto_unbox = TRUE, digits = NA))
        self$`colorMap` <- colorMapObject
      }
      if (!is.null(LocalizationTypeObject$`description`)) {
        self$`description` <- LocalizationTypeObject$`description`
      }
      if (!is.null(LocalizationTypeObject$`dtype`)) {
        self$`dtype` <- LocalizationTypeObject$`dtype`
      }
      if (!is.null(LocalizationTypeObject$`id`)) {
        self$`id` <- LocalizationTypeObject$`id`
      }
      if (!is.null(LocalizationTypeObject$`line_width`)) {
        self$`line_width` <- LocalizationTypeObject$`line_width`
      }
      if (!is.null(LocalizationTypeObject$`media`)) {
        self$`media` <- ApiClient$new()$deserializeObj(LocalizationTypeObject$`media`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(LocalizationTypeObject$`name`)) {
        self$`name` <- LocalizationTypeObject$`name`
      }
      if (!is.null(LocalizationTypeObject$`project`)) {
        self$`project` <- LocalizationTypeObject$`project`
      }
      if (!is.null(LocalizationTypeObject$`visible`)) {
        self$`visible` <- LocalizationTypeObject$`visible`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`colorMap`)) {
        sprintf(
        '"colorMap":
        %s
        ',
        jsonlite::toJSON(self$`colorMap`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`line_width`)) {
        sprintf(
        '"line_width":
          %d
                ',
        self$`line_width`
        )},
        if (!is.null(self$`media`)) {
        sprintf(
        '"media":
           [%s]
        ',
        paste(unlist(lapply(self$`media`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )},
        if (!is.null(self$`visible`)) {
        sprintf(
        '"visible":
          "%s"
                ',
        self$`visible`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalizationTypeJson) {
      LocalizationTypeObject <- jsonlite::fromJSON(LocalizationTypeJson)
      self$`attribute_types` <- ApiClient$new()$deserializeObj(LocalizationTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`colorMap` <- ColorMap$new()$fromJSON(jsonlite::toJSON(LocalizationTypeObject$colorMap, auto_unbox = TRUE, digits = NA))
      self$`description` <- LocalizationTypeObject$`description`
      self$`dtype` <- LocalizationTypeObject$`dtype`
      self$`id` <- LocalizationTypeObject$`id`
      self$`line_width` <- LocalizationTypeObject$`line_width`
      self$`media` <- ApiClient$new()$deserializeObj(LocalizationTypeObject$`media`, "array[integer]", loadNamespace("tator"))
      self$`name` <- LocalizationTypeObject$`name`
      self$`project` <- LocalizationTypeObject$`project`
      self$`visible` <- LocalizationTypeObject$`visible`
      self
    }
  )
)
