# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LocalizationSpec
#' @description LocalizationSpec Class
#' @format An \code{R6Class} generator object
#' @field frame  integer 
#'
#' @field height  numeric [optional]
#'
#' @field media_id  integer 
#'
#' @field modified  character [optional]
#'
#' @field parent  numeric [optional]
#'
#' @field type  integer 
#'
#' @field u  numeric [optional]
#'
#' @field v  numeric [optional]
#'
#' @field version  integer [optional]
#'
#' @field width  numeric [optional]
#'
#' @field x  numeric [optional]
#'
#' @field y  numeric [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LocalizationSpec <- R6::R6Class(
  'LocalizationSpec',
  public = list(
    `frame` = NULL,
    `height` = NULL,
    `media_id` = NULL,
    `modified` = NULL,
    `parent` = NULL,
    `type` = NULL,
    `u` = NULL,
    `v` = NULL,
    `version` = NULL,
    `width` = NULL,
    `x` = NULL,
    `y` = NULL,
    initialize = function(`frame`, `media_id`, `type`, `height`=NULL, `modified`=NULL, `parent`=NULL, `u`=NULL, `v`=NULL, `version`=NULL, `width`=NULL, `x`=NULL, `y`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`frame`)) {
        stopifnot(is.numeric(`frame`), length(`frame`) == 1)
        self$`frame` <- `frame`
      }
      if (!missing(`media_id`)) {
        stopifnot(is.numeric(`media_id`), length(`media_id`) == 1)
        self$`media_id` <- `media_id`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`height`)) {
        self$`height` <- `height`
      }
      if (!is.null(`modified`)) {
        self$`modified` <- `modified`
      }
      if (!is.null(`parent`)) {
        self$`parent` <- `parent`
      }
      if (!is.null(`u`)) {
        self$`u` <- `u`
      }
      if (!is.null(`v`)) {
        self$`v` <- `v`
      }
      if (!is.null(`version`)) {
        stopifnot(is.numeric(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!is.null(`width`)) {
        self$`width` <- `width`
      }
      if (!is.null(`x`)) {
        self$`x` <- `x`
      }
      if (!is.null(`y`)) {
        self$`y` <- `y`
      }
    },
    toJSON = function() {
      LocalizationSpecObject <- list()
      if (!is.null(self$`frame`)) {
        LocalizationSpecObject[['frame']] <-
          self$`frame`
      }
      if (!is.null(self$`height`)) {
        LocalizationSpecObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`media_id`)) {
        LocalizationSpecObject[['media_id']] <-
          self$`media_id`
      }
      if (!is.null(self$`modified`)) {
        LocalizationSpecObject[['modified']] <-
          self$`modified`
      }
      if (!is.null(self$`parent`)) {
        LocalizationSpecObject[['parent']] <-
          self$`parent`
      }
      if (!is.null(self$`type`)) {
        LocalizationSpecObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`u`)) {
        LocalizationSpecObject[['u']] <-
          self$`u`
      }
      if (!is.null(self$`v`)) {
        LocalizationSpecObject[['v']] <-
          self$`v`
      }
      if (!is.null(self$`version`)) {
        LocalizationSpecObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`width`)) {
        LocalizationSpecObject[['width']] <-
          self$`width`
      }
      if (!is.null(self$`x`)) {
        LocalizationSpecObject[['x']] <-
          self$`x`
      }
      if (!is.null(self$`y`)) {
        LocalizationSpecObject[['y']] <-
          self$`y`
      }

      LocalizationSpecObject
    },
    fromJSON = function(LocalizationSpecJson) {
      LocalizationSpecObject <- jsonlite::fromJSON(LocalizationSpecJson)
      if (!is.null(LocalizationSpecObject$`frame`)) {
        self$`frame` <- LocalizationSpecObject$`frame`
      }
      if (!is.null(LocalizationSpecObject$`height`)) {
        self$`height` <- LocalizationSpecObject$`height`
      }
      if (!is.null(LocalizationSpecObject$`media_id`)) {
        self$`media_id` <- LocalizationSpecObject$`media_id`
      }
      if (!is.null(LocalizationSpecObject$`modified`)) {
        self$`modified` <- LocalizationSpecObject$`modified`
      }
      if (!is.null(LocalizationSpecObject$`parent`)) {
        self$`parent` <- LocalizationSpecObject$`parent`
      }
      if (!is.null(LocalizationSpecObject$`type`)) {
        self$`type` <- LocalizationSpecObject$`type`
      }
      if (!is.null(LocalizationSpecObject$`u`)) {
        self$`u` <- LocalizationSpecObject$`u`
      }
      if (!is.null(LocalizationSpecObject$`v`)) {
        self$`v` <- LocalizationSpecObject$`v`
      }
      if (!is.null(LocalizationSpecObject$`version`)) {
        self$`version` <- LocalizationSpecObject$`version`
      }
      if (!is.null(LocalizationSpecObject$`width`)) {
        self$`width` <- LocalizationSpecObject$`width`
      }
      if (!is.null(LocalizationSpecObject$`x`)) {
        self$`x` <- LocalizationSpecObject$`x`
      }
      if (!is.null(LocalizationSpecObject$`y`)) {
        self$`y` <- LocalizationSpecObject$`y`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`frame`)) {
        sprintf(
        '"frame":
          %d
                ',
        self$`frame`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`media_id`)) {
        sprintf(
        '"media_id":
          %d
                ',
        self$`media_id`
        )},
        if (!is.null(self$`modified`)) {
        sprintf(
        '"modified":
          "%s"
                ',
        self$`modified`
        )},
        if (!is.null(self$`parent`)) {
        sprintf(
        '"parent":
          %d
                ',
        self$`parent`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )},
        if (!is.null(self$`u`)) {
        sprintf(
        '"u":
          %d
                ',
        self$`u`
        )},
        if (!is.null(self$`v`)) {
        sprintf(
        '"v":
          %d
                ',
        self$`v`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          %d
                ',
        self$`version`
        )},
        if (!is.null(self$`width`)) {
        sprintf(
        '"width":
          %d
                ',
        self$`width`
        )},
        if (!is.null(self$`x`)) {
        sprintf(
        '"x":
          %d
                ',
        self$`x`
        )},
        if (!is.null(self$`y`)) {
        sprintf(
        '"y":
          %d
                ',
        self$`y`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalizationSpecJson) {
      LocalizationSpecObject <- jsonlite::fromJSON(LocalizationSpecJson)
      self$`frame` <- LocalizationSpecObject$`frame`
      self$`height` <- LocalizationSpecObject$`height`
      self$`media_id` <- LocalizationSpecObject$`media_id`
      self$`modified` <- LocalizationSpecObject$`modified`
      self$`parent` <- LocalizationSpecObject$`parent`
      self$`type` <- LocalizationSpecObject$`type`
      self$`u` <- LocalizationSpecObject$`u`
      self$`v` <- LocalizationSpecObject$`v`
      self$`version` <- LocalizationSpecObject$`version`
      self$`width` <- LocalizationSpecObject$`width`
      self$`x` <- LocalizationSpecObject$`x`
      self$`y` <- LocalizationSpecObject$`y`
      self
    }
  )
)
