# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LocalizationUpdate
#' @description LocalizationUpdate Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field frame  integer [optional]
#'
#' @field height  numeric [optional]
#'
#' @field modified  character [optional]
#'
#' @field parent  numeric [optional]
#'
#' @field u  numeric [optional]
#'
#' @field v  numeric [optional]
#'
#' @field width  numeric [optional]
#'
#' @field x  numeric [optional]
#'
#' @field y  numeric [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LocalizationUpdate <- R6::R6Class(
  'LocalizationUpdate',
  public = list(
    `attributes` = NULL,
    `frame` = NULL,
    `height` = NULL,
    `modified` = NULL,
    `parent` = NULL,
    `u` = NULL,
    `v` = NULL,
    `width` = NULL,
    `x` = NULL,
    `y` = NULL,
    initialize = function(`attributes`=NULL, `frame`=NULL, `height`=NULL, `modified`=NULL, `parent`=NULL, `u`=NULL, `v`=NULL, `width`=NULL, `x`=NULL, `y`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`frame`)) {
        stopifnot(is.numeric(`frame`), length(`frame`) == 1)
        self$`frame` <- `frame`
      }
      if (!is.null(`height`)) {
        self$`height` <- `height`
      }
      if (!is.null(`modified`)) {
        self$`modified` <- `modified`
      }
      if (!is.null(`parent`)) {
        self$`parent` <- `parent`
      }
      if (!is.null(`u`)) {
        self$`u` <- `u`
      }
      if (!is.null(`v`)) {
        self$`v` <- `v`
      }
      if (!is.null(`width`)) {
        self$`width` <- `width`
      }
      if (!is.null(`x`)) {
        self$`x` <- `x`
      }
      if (!is.null(`y`)) {
        self$`y` <- `y`
      }
    },
    toJSON = function() {
      LocalizationUpdateObject <- list()
      if (!is.null(self$`attributes`)) {
        LocalizationUpdateObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`frame`)) {
        LocalizationUpdateObject[['frame']] <-
          self$`frame`
      }
      if (!is.null(self$`height`)) {
        LocalizationUpdateObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`modified`)) {
        LocalizationUpdateObject[['modified']] <-
          self$`modified`
      }
      if (!is.null(self$`parent`)) {
        LocalizationUpdateObject[['parent']] <-
          self$`parent`
      }
      if (!is.null(self$`u`)) {
        LocalizationUpdateObject[['u']] <-
          self$`u`
      }
      if (!is.null(self$`v`)) {
        LocalizationUpdateObject[['v']] <-
          self$`v`
      }
      if (!is.null(self$`width`)) {
        LocalizationUpdateObject[['width']] <-
          self$`width`
      }
      if (!is.null(self$`x`)) {
        LocalizationUpdateObject[['x']] <-
          self$`x`
      }
      if (!is.null(self$`y`)) {
        LocalizationUpdateObject[['y']] <-
          self$`y`
      }

      LocalizationUpdateObject
    },
    fromJSON = function(LocalizationUpdateJson) {
      LocalizationUpdateObject <- jsonlite::fromJSON(LocalizationUpdateJson)
      if (!is.null(LocalizationUpdateObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(LocalizationUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(LocalizationUpdateObject$`frame`)) {
        self$`frame` <- LocalizationUpdateObject$`frame`
      }
      if (!is.null(LocalizationUpdateObject$`height`)) {
        self$`height` <- LocalizationUpdateObject$`height`
      }
      if (!is.null(LocalizationUpdateObject$`modified`)) {
        self$`modified` <- LocalizationUpdateObject$`modified`
      }
      if (!is.null(LocalizationUpdateObject$`parent`)) {
        self$`parent` <- LocalizationUpdateObject$`parent`
      }
      if (!is.null(LocalizationUpdateObject$`u`)) {
        self$`u` <- LocalizationUpdateObject$`u`
      }
      if (!is.null(LocalizationUpdateObject$`v`)) {
        self$`v` <- LocalizationUpdateObject$`v`
      }
      if (!is.null(LocalizationUpdateObject$`width`)) {
        self$`width` <- LocalizationUpdateObject$`width`
      }
      if (!is.null(LocalizationUpdateObject$`x`)) {
        self$`x` <- LocalizationUpdateObject$`x`
      }
      if (!is.null(LocalizationUpdateObject$`y`)) {
        self$`y` <- LocalizationUpdateObject$`y`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`frame`)) {
        sprintf(
        '"frame":
          %d
                ',
        self$`frame`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`modified`)) {
        sprintf(
        '"modified":
          "%s"
                ',
        self$`modified`
        )},
        if (!is.null(self$`parent`)) {
        sprintf(
        '"parent":
          %d
                ',
        self$`parent`
        )},
        if (!is.null(self$`u`)) {
        sprintf(
        '"u":
          %d
                ',
        self$`u`
        )},
        if (!is.null(self$`v`)) {
        sprintf(
        '"v":
          %d
                ',
        self$`v`
        )},
        if (!is.null(self$`width`)) {
        sprintf(
        '"width":
          %d
                ',
        self$`width`
        )},
        if (!is.null(self$`x`)) {
        sprintf(
        '"x":
          %d
                ',
        self$`x`
        )},
        if (!is.null(self$`y`)) {
        sprintf(
        '"y":
          %d
                ',
        self$`y`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalizationUpdateJson) {
      LocalizationUpdateObject <- jsonlite::fromJSON(LocalizationUpdateJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(LocalizationUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`frame` <- LocalizationUpdateObject$`frame`
      self$`height` <- LocalizationUpdateObject$`height`
      self$`modified` <- LocalizationUpdateObject$`modified`
      self$`parent` <- LocalizationUpdateObject$`parent`
      self$`u` <- LocalizationUpdateObject$`u`
      self$`v` <- LocalizationUpdateObject$`v`
      self$`width` <- LocalizationUpdateObject$`width`
      self$`x` <- LocalizationUpdateObject$`x`
      self$`y` <- LocalizationUpdateObject$`y`
      self
    }
  )
)
