# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Localization
#' @description Localization Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field email  character [optional]
#'
#' @field frame  integer [optional]
#'
#' @field height  numeric [optional]
#'
#' @field id  integer [optional]
#'
#' @field media  integer [optional]
#'
#' @field meta  integer [optional]
#'
#' @field modified  character [optional]
#'
#' @field parent  numeric [optional]
#'
#' @field project  integer [optional]
#'
#' @field thumbnail_image  character [optional]
#'
#' @field u  numeric [optional]
#'
#' @field v  numeric [optional]
#'
#' @field version  integer [optional]
#'
#' @field width  numeric [optional]
#'
#' @field x  numeric [optional]
#'
#' @field y  numeric [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Localization <- R6::R6Class(
  'Localization',
  public = list(
    `attributes` = NULL,
    `email` = NULL,
    `frame` = NULL,
    `height` = NULL,
    `id` = NULL,
    `media` = NULL,
    `meta` = NULL,
    `modified` = NULL,
    `parent` = NULL,
    `project` = NULL,
    `thumbnail_image` = NULL,
    `u` = NULL,
    `v` = NULL,
    `version` = NULL,
    `width` = NULL,
    `x` = NULL,
    `y` = NULL,
    initialize = function(`attributes`=NULL, `email`=NULL, `frame`=NULL, `height`=NULL, `id`=NULL, `media`=NULL, `meta`=NULL, `modified`=NULL, `parent`=NULL, `project`=NULL, `thumbnail_image`=NULL, `u`=NULL, `v`=NULL, `version`=NULL, `width`=NULL, `x`=NULL, `y`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!is.null(`frame`)) {
        stopifnot(is.numeric(`frame`), length(`frame`) == 1)
        self$`frame` <- `frame`
      }
      if (!is.null(`height`)) {
        self$`height` <- `height`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`media`)) {
        stopifnot(is.numeric(`media`), length(`media`) == 1)
        self$`media` <- `media`
      }
      if (!is.null(`meta`)) {
        stopifnot(is.numeric(`meta`), length(`meta`) == 1)
        self$`meta` <- `meta`
      }
      if (!is.null(`modified`)) {
        self$`modified` <- `modified`
      }
      if (!is.null(`parent`)) {
        self$`parent` <- `parent`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`thumbnail_image`)) {
        stopifnot(is.character(`thumbnail_image`), length(`thumbnail_image`) == 1)
        self$`thumbnail_image` <- `thumbnail_image`
      }
      if (!is.null(`u`)) {
        self$`u` <- `u`
      }
      if (!is.null(`v`)) {
        self$`v` <- `v`
      }
      if (!is.null(`version`)) {
        stopifnot(is.numeric(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
      if (!is.null(`width`)) {
        self$`width` <- `width`
      }
      if (!is.null(`x`)) {
        self$`x` <- `x`
      }
      if (!is.null(`y`)) {
        self$`y` <- `y`
      }
    },
    toJSON = function() {
      LocalizationObject <- list()
      if (!is.null(self$`attributes`)) {
        LocalizationObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`email`)) {
        LocalizationObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`frame`)) {
        LocalizationObject[['frame']] <-
          self$`frame`
      }
      if (!is.null(self$`height`)) {
        LocalizationObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`id`)) {
        LocalizationObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`media`)) {
        LocalizationObject[['media']] <-
          self$`media`
      }
      if (!is.null(self$`meta`)) {
        LocalizationObject[['meta']] <-
          self$`meta`
      }
      if (!is.null(self$`modified`)) {
        LocalizationObject[['modified']] <-
          self$`modified`
      }
      if (!is.null(self$`parent`)) {
        LocalizationObject[['parent']] <-
          self$`parent`
      }
      if (!is.null(self$`project`)) {
        LocalizationObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`thumbnail_image`)) {
        LocalizationObject[['thumbnail_image']] <-
          self$`thumbnail_image`
      }
      if (!is.null(self$`u`)) {
        LocalizationObject[['u']] <-
          self$`u`
      }
      if (!is.null(self$`v`)) {
        LocalizationObject[['v']] <-
          self$`v`
      }
      if (!is.null(self$`version`)) {
        LocalizationObject[['version']] <-
          self$`version`
      }
      if (!is.null(self$`width`)) {
        LocalizationObject[['width']] <-
          self$`width`
      }
      if (!is.null(self$`x`)) {
        LocalizationObject[['x']] <-
          self$`x`
      }
      if (!is.null(self$`y`)) {
        LocalizationObject[['y']] <-
          self$`y`
      }

      LocalizationObject
    },
    fromJSON = function(LocalizationJson) {
      LocalizationObject <- jsonlite::fromJSON(LocalizationJson)
      if (!is.null(LocalizationObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(LocalizationObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(LocalizationObject$`email`)) {
        self$`email` <- LocalizationObject$`email`
      }
      if (!is.null(LocalizationObject$`frame`)) {
        self$`frame` <- LocalizationObject$`frame`
      }
      if (!is.null(LocalizationObject$`height`)) {
        self$`height` <- LocalizationObject$`height`
      }
      if (!is.null(LocalizationObject$`id`)) {
        self$`id` <- LocalizationObject$`id`
      }
      if (!is.null(LocalizationObject$`media`)) {
        self$`media` <- LocalizationObject$`media`
      }
      if (!is.null(LocalizationObject$`meta`)) {
        self$`meta` <- LocalizationObject$`meta`
      }
      if (!is.null(LocalizationObject$`modified`)) {
        self$`modified` <- LocalizationObject$`modified`
      }
      if (!is.null(LocalizationObject$`parent`)) {
        self$`parent` <- LocalizationObject$`parent`
      }
      if (!is.null(LocalizationObject$`project`)) {
        self$`project` <- LocalizationObject$`project`
      }
      if (!is.null(LocalizationObject$`thumbnail_image`)) {
        self$`thumbnail_image` <- LocalizationObject$`thumbnail_image`
      }
      if (!is.null(LocalizationObject$`u`)) {
        self$`u` <- LocalizationObject$`u`
      }
      if (!is.null(LocalizationObject$`v`)) {
        self$`v` <- LocalizationObject$`v`
      }
      if (!is.null(LocalizationObject$`version`)) {
        self$`version` <- LocalizationObject$`version`
      }
      if (!is.null(LocalizationObject$`width`)) {
        self$`width` <- LocalizationObject$`width`
      }
      if (!is.null(LocalizationObject$`x`)) {
        self$`x` <- LocalizationObject$`x`
      }
      if (!is.null(LocalizationObject$`y`)) {
        self$`y` <- LocalizationObject$`y`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`frame`)) {
        sprintf(
        '"frame":
          %d
                ',
        self$`frame`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`media`)) {
        sprintf(
        '"media":
          %d
                ',
        self$`media`
        )},
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
          %d
                ',
        self$`meta`
        )},
        if (!is.null(self$`modified`)) {
        sprintf(
        '"modified":
          "%s"
                ',
        self$`modified`
        )},
        if (!is.null(self$`parent`)) {
        sprintf(
        '"parent":
          %d
                ',
        self$`parent`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )},
        if (!is.null(self$`thumbnail_image`)) {
        sprintf(
        '"thumbnail_image":
          "%s"
                ',
        self$`thumbnail_image`
        )},
        if (!is.null(self$`u`)) {
        sprintf(
        '"u":
          %d
                ',
        self$`u`
        )},
        if (!is.null(self$`v`)) {
        sprintf(
        '"v":
          %d
                ',
        self$`v`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          %d
                ',
        self$`version`
        )},
        if (!is.null(self$`width`)) {
        sprintf(
        '"width":
          %d
                ',
        self$`width`
        )},
        if (!is.null(self$`x`)) {
        sprintf(
        '"x":
          %d
                ',
        self$`x`
        )},
        if (!is.null(self$`y`)) {
        sprintf(
        '"y":
          %d
                ',
        self$`y`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalizationJson) {
      LocalizationObject <- jsonlite::fromJSON(LocalizationJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(LocalizationObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`email` <- LocalizationObject$`email`
      self$`frame` <- LocalizationObject$`frame`
      self$`height` <- LocalizationObject$`height`
      self$`id` <- LocalizationObject$`id`
      self$`media` <- LocalizationObject$`media`
      self$`meta` <- LocalizationObject$`meta`
      self$`modified` <- LocalizationObject$`modified`
      self$`parent` <- LocalizationObject$`parent`
      self$`project` <- LocalizationObject$`project`
      self$`thumbnail_image` <- LocalizationObject$`thumbnail_image`
      self$`u` <- LocalizationObject$`u`
      self$`v` <- LocalizationObject$`v`
      self$`version` <- LocalizationObject$`version`
      self$`width` <- LocalizationObject$`width`
      self$`x` <- LocalizationObject$`x`
      self$`y` <- LocalizationObject$`y`
      self
    }
  )
)
