# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title LocalizationTypeSpec
#' @description LocalizationTypeSpec Class
#' @format An \code{R6Class} generator object
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field colorMap  \link{ColorMap} [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character 
#'
#' @field line_width  integer [optional]
#'
#' @field media_types  list( integer ) 
#'
#' @field name  character 
#'
#' @field visible  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
LocalizationTypeSpec <- R6::R6Class(
  'LocalizationTypeSpec',
  public = list(
    `attribute_types` = NULL,
    `colorMap` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `line_width` = NULL,
    `media_types` = NULL,
    `name` = NULL,
    `visible` = NULL,
    initialize = function(`dtype`, `media_types`, `name`, `attribute_types`=NULL, `colorMap`=NULL, `description`=NULL, `line_width`=NULL, `visible`=TRUE, ...){
      local.optional.var <- list(...)
      if (!missing(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!missing(`media_types`)) {
        stopifnot(is.vector(`media_types`), length(`media_types`) != 0)
        sapply(`media_types`, function(x) stopifnot(is.numeric(x)))
        self$`media_types` <- `media_types`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`colorMap`)) {
        stopifnot(R6::is.R6(`colorMap`))
        self$`colorMap` <- `colorMap`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`line_width`)) {
        stopifnot(is.numeric(`line_width`), length(`line_width`) == 1)
        self$`line_width` <- `line_width`
      }
      if (!is.null(`visible`)) {
        self$`visible` <- `visible`
      }
    },
    toJSON = function() {
      LocalizationTypeSpecObject <- list()
      if (!is.null(self$`attribute_types`)) {
        LocalizationTypeSpecObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`colorMap`)) {
        LocalizationTypeSpecObject[['colorMap']] <-
          self$`colorMap`$toJSON()
      }
      if (!is.null(self$`description`)) {
        LocalizationTypeSpecObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        LocalizationTypeSpecObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`line_width`)) {
        LocalizationTypeSpecObject[['line_width']] <-
          self$`line_width`
      }
      if (!is.null(self$`media_types`)) {
        LocalizationTypeSpecObject[['media_types']] <-
          self$`media_types`
      }
      if (!is.null(self$`name`)) {
        LocalizationTypeSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`visible`)) {
        LocalizationTypeSpecObject[['visible']] <-
          self$`visible`
      }

      LocalizationTypeSpecObject
    },
    fromJSON = function(LocalizationTypeSpecJson) {
      LocalizationTypeSpecObject <- jsonlite::fromJSON(LocalizationTypeSpecJson)
      if (!is.null(LocalizationTypeSpecObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(LocalizationTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(LocalizationTypeSpecObject$`colorMap`)) {
        colorMapObject <- ColorMap$new()
        colorMapObject$fromJSON(jsonlite::toJSON(LocalizationTypeSpecObject$colorMap, auto_unbox = TRUE, digits = NA))
        self$`colorMap` <- colorMapObject
      }
      if (!is.null(LocalizationTypeSpecObject$`description`)) {
        self$`description` <- LocalizationTypeSpecObject$`description`
      }
      if (!is.null(LocalizationTypeSpecObject$`dtype`)) {
        self$`dtype` <- LocalizationTypeSpecObject$`dtype`
      }
      if (!is.null(LocalizationTypeSpecObject$`line_width`)) {
        self$`line_width` <- LocalizationTypeSpecObject$`line_width`
      }
      if (!is.null(LocalizationTypeSpecObject$`media_types`)) {
        self$`media_types` <- ApiClient$new()$deserializeObj(LocalizationTypeSpecObject$`media_types`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(LocalizationTypeSpecObject$`name`)) {
        self$`name` <- LocalizationTypeSpecObject$`name`
      }
      if (!is.null(LocalizationTypeSpecObject$`visible`)) {
        self$`visible` <- LocalizationTypeSpecObject$`visible`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`colorMap`)) {
        sprintf(
        '"colorMap":
        %s
        ',
        jsonlite::toJSON(self$`colorMap`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`line_width`)) {
        sprintf(
        '"line_width":
          %d
                ',
        self$`line_width`
        )},
        if (!is.null(self$`media_types`)) {
        sprintf(
        '"media_types":
           [%s]
        ',
        paste(unlist(lapply(self$`media_types`, function(x) paste0(x))), collapse=",")
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`visible`)) {
        sprintf(
        '"visible":
          %s
                ',
        jsonlite::toJSON(self$`visible`, auto_unbox = TRUE)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(LocalizationTypeSpecJson) {
      LocalizationTypeSpecObject <- jsonlite::fromJSON(LocalizationTypeSpecJson)
      self$`attribute_types` <- ApiClient$new()$deserializeObj(LocalizationTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`colorMap` <- ColorMap$new()$fromJSON(jsonlite::toJSON(LocalizationTypeSpecObject$colorMap, auto_unbox = TRUE, digits = NA))
      self$`description` <- LocalizationTypeSpecObject$`description`
      self$`dtype` <- LocalizationTypeSpecObject$`dtype`
      self$`line_width` <- LocalizationTypeSpecObject$`line_width`
      self$`media_types` <- ApiClient$new()$deserializeObj(LocalizationTypeSpecObject$`media_types`, "array[integer]", loadNamespace("tator"))
      self$`name` <- LocalizationTypeSpecObject$`name`
      self$`visible` <- LocalizationTypeSpecObject$`visible`
      self
    }
  )
)
