# Tator REST API
#
# No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaSpec
#' @description MediaSpec Class
#' @format An \code{R6Class} generator object
#' @field gid  character [optional]
#'
#' @field md5  character 
#'
#' @field name  character 
#'
#' @field progress_name  character [optional]
#'
#' @field section  character 
#'
#' @field thumbnail_url  character [optional]
#'
#' @field type  integer 
#'
#' @field uid  character [optional]
#'
#' @field url  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaSpec <- R6::R6Class(
  'MediaSpec',
  public = list(
    `gid` = NULL,
    `md5` = NULL,
    `name` = NULL,
    `progress_name` = NULL,
    `section` = NULL,
    `thumbnail_url` = NULL,
    `type` = NULL,
    `uid` = NULL,
    `url` = NULL,
    initialize = function(`md5`, `name`, `section`, `type`, `gid`=NULL, `progress_name`=NULL, `thumbnail_url`=NULL, `uid`=NULL, `url`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`md5`)) {
        stopifnot(is.character(`md5`), length(`md5`) == 1)
        self$`md5` <- `md5`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`section`)) {
        stopifnot(is.character(`section`), length(`section`) == 1)
        self$`section` <- `section`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!is.null(`progress_name`)) {
        stopifnot(is.character(`progress_name`), length(`progress_name`) == 1)
        self$`progress_name` <- `progress_name`
      }
      if (!is.null(`thumbnail_url`)) {
        stopifnot(is.character(`thumbnail_url`), length(`thumbnail_url`) == 1)
        self$`thumbnail_url` <- `thumbnail_url`
      }
      if (!is.null(`uid`)) {
        stopifnot(is.character(`uid`), length(`uid`) == 1)
        self$`uid` <- `uid`
      }
      if (!is.null(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
    },
    toJSON = function() {
      MediaSpecObject <- list()
      if (!is.null(self$`gid`)) {
        MediaSpecObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`md5`)) {
        MediaSpecObject[['md5']] <-
          self$`md5`
      }
      if (!is.null(self$`name`)) {
        MediaSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`progress_name`)) {
        MediaSpecObject[['progress_name']] <-
          self$`progress_name`
      }
      if (!is.null(self$`section`)) {
        MediaSpecObject[['section']] <-
          self$`section`
      }
      if (!is.null(self$`thumbnail_url`)) {
        MediaSpecObject[['thumbnail_url']] <-
          self$`thumbnail_url`
      }
      if (!is.null(self$`type`)) {
        MediaSpecObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`uid`)) {
        MediaSpecObject[['uid']] <-
          self$`uid`
      }
      if (!is.null(self$`url`)) {
        MediaSpecObject[['url']] <-
          self$`url`
      }

      MediaSpecObject
    },
    fromJSON = function(MediaSpecJson) {
      MediaSpecObject <- jsonlite::fromJSON(MediaSpecJson)
      if (!is.null(MediaSpecObject$`gid`)) {
        self$`gid` <- MediaSpecObject$`gid`
      }
      if (!is.null(MediaSpecObject$`md5`)) {
        self$`md5` <- MediaSpecObject$`md5`
      }
      if (!is.null(MediaSpecObject$`name`)) {
        self$`name` <- MediaSpecObject$`name`
      }
      if (!is.null(MediaSpecObject$`progress_name`)) {
        self$`progress_name` <- MediaSpecObject$`progress_name`
      }
      if (!is.null(MediaSpecObject$`section`)) {
        self$`section` <- MediaSpecObject$`section`
      }
      if (!is.null(MediaSpecObject$`thumbnail_url`)) {
        self$`thumbnail_url` <- MediaSpecObject$`thumbnail_url`
      }
      if (!is.null(MediaSpecObject$`type`)) {
        self$`type` <- MediaSpecObject$`type`
      }
      if (!is.null(MediaSpecObject$`uid`)) {
        self$`uid` <- MediaSpecObject$`uid`
      }
      if (!is.null(MediaSpecObject$`url`)) {
        self$`url` <- MediaSpecObject$`url`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`md5`)) {
        sprintf(
        '"md5":
          "%s"
                ',
        self$`md5`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`progress_name`)) {
        sprintf(
        '"progress_name":
          "%s"
                ',
        self$`progress_name`
        )},
        if (!is.null(self$`section`)) {
        sprintf(
        '"section":
          "%s"
                ',
        self$`section`
        )},
        if (!is.null(self$`thumbnail_url`)) {
        sprintf(
        '"thumbnail_url":
          "%s"
                ',
        self$`thumbnail_url`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )},
        if (!is.null(self$`uid`)) {
        sprintf(
        '"uid":
          "%s"
                ',
        self$`uid`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaSpecJson) {
      MediaSpecObject <- jsonlite::fromJSON(MediaSpecJson)
      self$`gid` <- MediaSpecObject$`gid`
      self$`md5` <- MediaSpecObject$`md5`
      self$`name` <- MediaSpecObject$`name`
      self$`progress_name` <- MediaSpecObject$`progress_name`
      self$`section` <- MediaSpecObject$`section`
      self$`thumbnail_url` <- MediaSpecObject$`thumbnail_url`
      self$`type` <- MediaSpecObject$`type`
      self$`uid` <- MediaSpecObject$`uid`
      self$`url` <- MediaSpecObject$`url`
      self
    }
  )
)
