# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Media
#' @description Media Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field codec  character [optional]
#'
#' @field created_by  integer [optional]
#'
#' @field created_datetime  character [optional]
#'
#' @field file  character [optional]
#'
#' @field fps  integer [optional]
#'
#' @field height  integer [optional]
#'
#' @field id  integer [optional]
#'
#' @field last_edit_end  character [optional]
#'
#' @field last_edit_start  character [optional]
#'
#' @field md5  character [optional]
#'
#' @field media_files  \link{MediaFiles} [optional]
#'
#' @field meta  integer [optional]
#'
#' @field modified_by  integer [optional]
#'
#' @field modified_datetime  character [optional]
#'
#' @field name  character [optional]
#'
#' @field num_frames  integer [optional]
#'
#' @field original  character [optional]
#'
#' @field project  integer [optional]
#'
#' @field segment_info  character [optional]
#'
#' @field thumbnail  character [optional]
#'
#' @field thumbnail_gif  character [optional]
#'
#' @field width  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Media <- R6::R6Class(
  'Media',
  public = list(
    `attributes` = NULL,
    `codec` = NULL,
    `created_by` = NULL,
    `created_datetime` = NULL,
    `file` = NULL,
    `fps` = NULL,
    `height` = NULL,
    `id` = NULL,
    `last_edit_end` = NULL,
    `last_edit_start` = NULL,
    `md5` = NULL,
    `media_files` = NULL,
    `meta` = NULL,
    `modified_by` = NULL,
    `modified_datetime` = NULL,
    `name` = NULL,
    `num_frames` = NULL,
    `original` = NULL,
    `project` = NULL,
    `segment_info` = NULL,
    `thumbnail` = NULL,
    `thumbnail_gif` = NULL,
    `width` = NULL,
    initialize = function(`attributes`=NULL, `codec`=NULL, `created_by`=NULL, `created_datetime`=NULL, `file`=NULL, `fps`=NULL, `height`=NULL, `id`=NULL, `last_edit_end`=NULL, `last_edit_start`=NULL, `md5`=NULL, `media_files`=NULL, `meta`=NULL, `modified_by`=NULL, `modified_datetime`=NULL, `name`=NULL, `num_frames`=NULL, `original`=NULL, `project`=NULL, `segment_info`=NULL, `thumbnail`=NULL, `thumbnail_gif`=NULL, `width`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`codec`)) {
        stopifnot(is.character(`codec`), length(`codec`) == 1)
        self$`codec` <- `codec`
      }
      if (!is.null(`created_by`)) {
        stopifnot(is.numeric(`created_by`), length(`created_by`) == 1)
        self$`created_by` <- `created_by`
      }
      if (!is.null(`created_datetime`)) {
        stopifnot(is.character(`created_datetime`), length(`created_datetime`) == 1)
        self$`created_datetime` <- `created_datetime`
      }
      if (!is.null(`file`)) {
        stopifnot(is.character(`file`), length(`file`) == 1)
        self$`file` <- `file`
      }
      if (!is.null(`fps`)) {
        stopifnot(is.numeric(`fps`), length(`fps`) == 1)
        self$`fps` <- `fps`
      }
      if (!is.null(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`last_edit_end`)) {
        stopifnot(is.character(`last_edit_end`), length(`last_edit_end`) == 1)
        self$`last_edit_end` <- `last_edit_end`
      }
      if (!is.null(`last_edit_start`)) {
        stopifnot(is.character(`last_edit_start`), length(`last_edit_start`) == 1)
        self$`last_edit_start` <- `last_edit_start`
      }
      if (!is.null(`md5`)) {
        stopifnot(is.character(`md5`), length(`md5`) == 1)
        self$`md5` <- `md5`
      }
      if (!is.null(`media_files`)) {
        stopifnot(R6::is.R6(`media_files`))
        self$`media_files` <- `media_files`
      }
      if (!is.null(`meta`)) {
        stopifnot(is.numeric(`meta`), length(`meta`) == 1)
        self$`meta` <- `meta`
      }
      if (!is.null(`modified_by`)) {
        stopifnot(is.numeric(`modified_by`), length(`modified_by`) == 1)
        self$`modified_by` <- `modified_by`
      }
      if (!is.null(`modified_datetime`)) {
        stopifnot(is.character(`modified_datetime`), length(`modified_datetime`) == 1)
        self$`modified_datetime` <- `modified_datetime`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`num_frames`)) {
        stopifnot(is.numeric(`num_frames`), length(`num_frames`) == 1)
        self$`num_frames` <- `num_frames`
      }
      if (!is.null(`original`)) {
        stopifnot(is.character(`original`), length(`original`) == 1)
        self$`original` <- `original`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`segment_info`)) {
        stopifnot(is.character(`segment_info`), length(`segment_info`) == 1)
        self$`segment_info` <- `segment_info`
      }
      if (!is.null(`thumbnail`)) {
        stopifnot(is.character(`thumbnail`), length(`thumbnail`) == 1)
        self$`thumbnail` <- `thumbnail`
      }
      if (!is.null(`thumbnail_gif`)) {
        stopifnot(is.character(`thumbnail_gif`), length(`thumbnail_gif`) == 1)
        self$`thumbnail_gif` <- `thumbnail_gif`
      }
      if (!is.null(`width`)) {
        stopifnot(is.numeric(`width`), length(`width`) == 1)
        self$`width` <- `width`
      }
    },
    toJSON = function() {
      MediaObject <- list()
      if (!is.null(self$`attributes`)) {
        MediaObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`codec`)) {
        MediaObject[['codec']] <-
          self$`codec`
      }
      if (!is.null(self$`created_by`)) {
        MediaObject[['created_by']] <-
          self$`created_by`
      }
      if (!is.null(self$`created_datetime`)) {
        MediaObject[['created_datetime']] <-
          self$`created_datetime`
      }
      if (!is.null(self$`file`)) {
        MediaObject[['file']] <-
          self$`file`
      }
      if (!is.null(self$`fps`)) {
        MediaObject[['fps']] <-
          self$`fps`
      }
      if (!is.null(self$`height`)) {
        MediaObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`id`)) {
        MediaObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`last_edit_end`)) {
        MediaObject[['last_edit_end']] <-
          self$`last_edit_end`
      }
      if (!is.null(self$`last_edit_start`)) {
        MediaObject[['last_edit_start']] <-
          self$`last_edit_start`
      }
      if (!is.null(self$`md5`)) {
        MediaObject[['md5']] <-
          self$`md5`
      }
      if (!is.null(self$`media_files`)) {
        MediaObject[['media_files']] <-
          self$`media_files`$toJSON()
      }
      if (!is.null(self$`meta`)) {
        MediaObject[['meta']] <-
          self$`meta`
      }
      if (!is.null(self$`modified_by`)) {
        MediaObject[['modified_by']] <-
          self$`modified_by`
      }
      if (!is.null(self$`modified_datetime`)) {
        MediaObject[['modified_datetime']] <-
          self$`modified_datetime`
      }
      if (!is.null(self$`name`)) {
        MediaObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`num_frames`)) {
        MediaObject[['num_frames']] <-
          self$`num_frames`
      }
      if (!is.null(self$`original`)) {
        MediaObject[['original']] <-
          self$`original`
      }
      if (!is.null(self$`project`)) {
        MediaObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`segment_info`)) {
        MediaObject[['segment_info']] <-
          self$`segment_info`
      }
      if (!is.null(self$`thumbnail`)) {
        MediaObject[['thumbnail']] <-
          self$`thumbnail`
      }
      if (!is.null(self$`thumbnail_gif`)) {
        MediaObject[['thumbnail_gif']] <-
          self$`thumbnail_gif`
      }
      if (!is.null(self$`width`)) {
        MediaObject[['width']] <-
          self$`width`
      }

      MediaObject
    },
    fromJSON = function(MediaJson) {
      MediaObject <- jsonlite::fromJSON(MediaJson)
      if (!is.null(MediaObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(MediaObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(MediaObject$`codec`)) {
        self$`codec` <- MediaObject$`codec`
      }
      if (!is.null(MediaObject$`created_by`)) {
        self$`created_by` <- MediaObject$`created_by`
      }
      if (!is.null(MediaObject$`created_datetime`)) {
        self$`created_datetime` <- MediaObject$`created_datetime`
      }
      if (!is.null(MediaObject$`file`)) {
        self$`file` <- MediaObject$`file`
      }
      if (!is.null(MediaObject$`fps`)) {
        self$`fps` <- MediaObject$`fps`
      }
      if (!is.null(MediaObject$`height`)) {
        self$`height` <- MediaObject$`height`
      }
      if (!is.null(MediaObject$`id`)) {
        self$`id` <- MediaObject$`id`
      }
      if (!is.null(MediaObject$`last_edit_end`)) {
        self$`last_edit_end` <- MediaObject$`last_edit_end`
      }
      if (!is.null(MediaObject$`last_edit_start`)) {
        self$`last_edit_start` <- MediaObject$`last_edit_start`
      }
      if (!is.null(MediaObject$`md5`)) {
        self$`md5` <- MediaObject$`md5`
      }
      if (!is.null(MediaObject$`media_files`)) {
        media_filesObject <- MediaFiles$new()
        media_filesObject$fromJSON(jsonlite::toJSON(MediaObject$media_files, auto_unbox = TRUE, digits = NA))
        self$`media_files` <- media_filesObject
      }
      if (!is.null(MediaObject$`meta`)) {
        self$`meta` <- MediaObject$`meta`
      }
      if (!is.null(MediaObject$`modified_by`)) {
        self$`modified_by` <- MediaObject$`modified_by`
      }
      if (!is.null(MediaObject$`modified_datetime`)) {
        self$`modified_datetime` <- MediaObject$`modified_datetime`
      }
      if (!is.null(MediaObject$`name`)) {
        self$`name` <- MediaObject$`name`
      }
      if (!is.null(MediaObject$`num_frames`)) {
        self$`num_frames` <- MediaObject$`num_frames`
      }
      if (!is.null(MediaObject$`original`)) {
        self$`original` <- MediaObject$`original`
      }
      if (!is.null(MediaObject$`project`)) {
        self$`project` <- MediaObject$`project`
      }
      if (!is.null(MediaObject$`segment_info`)) {
        self$`segment_info` <- MediaObject$`segment_info`
      }
      if (!is.null(MediaObject$`thumbnail`)) {
        self$`thumbnail` <- MediaObject$`thumbnail`
      }
      if (!is.null(MediaObject$`thumbnail_gif`)) {
        self$`thumbnail_gif` <- MediaObject$`thumbnail_gif`
      }
      if (!is.null(MediaObject$`width`)) {
        self$`width` <- MediaObject$`width`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`codec`)) {
        sprintf(
        '"codec":
          "%s"
                ',
        self$`codec`
        )},
        if (!is.null(self$`created_by`)) {
        sprintf(
        '"created_by":
          %d
                ',
        self$`created_by`
        )},
        if (!is.null(self$`created_datetime`)) {
        sprintf(
        '"created_datetime":
          "%s"
                ',
        self$`created_datetime`
        )},
        if (!is.null(self$`file`)) {
        sprintf(
        '"file":
          "%s"
                ',
        self$`file`
        )},
        if (!is.null(self$`fps`)) {
        sprintf(
        '"fps":
          %d
                ',
        self$`fps`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`last_edit_end`)) {
        sprintf(
        '"last_edit_end":
          "%s"
                ',
        self$`last_edit_end`
        )},
        if (!is.null(self$`last_edit_start`)) {
        sprintf(
        '"last_edit_start":
          "%s"
                ',
        self$`last_edit_start`
        )},
        if (!is.null(self$`md5`)) {
        sprintf(
        '"md5":
          "%s"
                ',
        self$`md5`
        )},
        if (!is.null(self$`media_files`)) {
        sprintf(
        '"media_files":
        %s
        ',
        jsonlite::toJSON(self$`media_files`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
          %d
                ',
        self$`meta`
        )},
        if (!is.null(self$`modified_by`)) {
        sprintf(
        '"modified_by":
          %d
                ',
        self$`modified_by`
        )},
        if (!is.null(self$`modified_datetime`)) {
        sprintf(
        '"modified_datetime":
          "%s"
                ',
        self$`modified_datetime`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`num_frames`)) {
        sprintf(
        '"num_frames":
          %d
                ',
        self$`num_frames`
        )},
        if (!is.null(self$`original`)) {
        sprintf(
        '"original":
          "%s"
                ',
        self$`original`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )},
        if (!is.null(self$`segment_info`)) {
        sprintf(
        '"segment_info":
          "%s"
                ',
        self$`segment_info`
        )},
        if (!is.null(self$`thumbnail`)) {
        sprintf(
        '"thumbnail":
          "%s"
                ',
        self$`thumbnail`
        )},
        if (!is.null(self$`thumbnail_gif`)) {
        sprintf(
        '"thumbnail_gif":
          "%s"
                ',
        self$`thumbnail_gif`
        )},
        if (!is.null(self$`width`)) {
        sprintf(
        '"width":
          %d
                ',
        self$`width`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaJson) {
      MediaObject <- jsonlite::fromJSON(MediaJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(MediaObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`codec` <- MediaObject$`codec`
      self$`created_by` <- MediaObject$`created_by`
      self$`created_datetime` <- MediaObject$`created_datetime`
      self$`file` <- MediaObject$`file`
      self$`fps` <- MediaObject$`fps`
      self$`height` <- MediaObject$`height`
      self$`id` <- MediaObject$`id`
      self$`last_edit_end` <- MediaObject$`last_edit_end`
      self$`last_edit_start` <- MediaObject$`last_edit_start`
      self$`md5` <- MediaObject$`md5`
      self$`media_files` <- MediaFiles$new()$fromJSON(jsonlite::toJSON(MediaObject$media_files, auto_unbox = TRUE, digits = NA))
      self$`meta` <- MediaObject$`meta`
      self$`modified_by` <- MediaObject$`modified_by`
      self$`modified_datetime` <- MediaObject$`modified_datetime`
      self$`name` <- MediaObject$`name`
      self$`num_frames` <- MediaObject$`num_frames`
      self$`original` <- MediaObject$`original`
      self$`project` <- MediaObject$`project`
      self$`segment_info` <- MediaObject$`segment_info`
      self$`thumbnail` <- MediaObject$`thumbnail`
      self$`thumbnail_gif` <- MediaObject$`thumbnail_gif`
      self$`width` <- MediaObject$`width`
      self
    }
  )
)
