# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaType
#' @description MediaType Class
#' @format An \code{R6Class} generator object
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field default_volume  integer [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character [optional]
#'
#' @field file_format  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field keep_original  character [optional]
#'
#' @field name  character [optional]
#'
#' @field project  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaType <- R6::R6Class(
  'MediaType',
  public = list(
    `attribute_types` = NULL,
    `default_volume` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `file_format` = NULL,
    `id` = NULL,
    `keep_original` = NULL,
    `name` = NULL,
    `project` = NULL,
    initialize = function(`attribute_types`=NULL, `default_volume`=NULL, `description`='', `dtype`=NULL, `file_format`=NULL, `id`=NULL, `keep_original`=TRUE, `name`=NULL, `project`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`default_volume`)) {
        stopifnot(is.numeric(`default_volume`), length(`default_volume`) == 1)
        self$`default_volume` <- `default_volume`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!is.null(`file_format`)) {
        stopifnot(is.character(`file_format`), length(`file_format`) == 1)
        self$`file_format` <- `file_format`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`keep_original`)) {
        self$`keep_original` <- `keep_original`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
    },
    toJSON = function() {
      MediaTypeObject <- list()
      if (!is.null(self$`attribute_types`)) {
        MediaTypeObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`default_volume`)) {
        MediaTypeObject[['default_volume']] <-
          self$`default_volume`
      }
      if (!is.null(self$`description`)) {
        MediaTypeObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        MediaTypeObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`file_format`)) {
        MediaTypeObject[['file_format']] <-
          self$`file_format`
      }
      if (!is.null(self$`id`)) {
        MediaTypeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`keep_original`)) {
        MediaTypeObject[['keep_original']] <-
          self$`keep_original`
      }
      if (!is.null(self$`name`)) {
        MediaTypeObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`project`)) {
        MediaTypeObject[['project']] <-
          self$`project`
      }

      MediaTypeObject
    },
    fromJSON = function(MediaTypeJson) {
      MediaTypeObject <- jsonlite::fromJSON(MediaTypeJson)
      if (!is.null(MediaTypeObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(MediaTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(MediaTypeObject$`default_volume`)) {
        self$`default_volume` <- MediaTypeObject$`default_volume`
      }
      if (!is.null(MediaTypeObject$`description`)) {
        self$`description` <- MediaTypeObject$`description`
      }
      if (!is.null(MediaTypeObject$`dtype`)) {
        self$`dtype` <- MediaTypeObject$`dtype`
      }
      if (!is.null(MediaTypeObject$`file_format`)) {
        self$`file_format` <- MediaTypeObject$`file_format`
      }
      if (!is.null(MediaTypeObject$`id`)) {
        self$`id` <- MediaTypeObject$`id`
      }
      if (!is.null(MediaTypeObject$`keep_original`)) {
        self$`keep_original` <- MediaTypeObject$`keep_original`
      }
      if (!is.null(MediaTypeObject$`name`)) {
        self$`name` <- MediaTypeObject$`name`
      }
      if (!is.null(MediaTypeObject$`project`)) {
        self$`project` <- MediaTypeObject$`project`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`default_volume`)) {
        sprintf(
        '"default_volume":
          %d
                ',
        self$`default_volume`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`file_format`)) {
        sprintf(
        '"file_format":
          "%s"
                ',
        self$`file_format`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`keep_original`)) {
        sprintf(
        '"keep_original":
          "%s"
                ',
        self$`keep_original`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaTypeJson) {
      MediaTypeObject <- jsonlite::fromJSON(MediaTypeJson)
      self$`attribute_types` <- ApiClient$new()$deserializeObj(MediaTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`default_volume` <- MediaTypeObject$`default_volume`
      self$`description` <- MediaTypeObject$`description`
      self$`dtype` <- MediaTypeObject$`dtype`
      self$`file_format` <- MediaTypeObject$`file_format`
      self$`id` <- MediaTypeObject$`id`
      self$`keep_original` <- MediaTypeObject$`keep_original`
      self$`name` <- MediaTypeObject$`name`
      self$`project` <- MediaTypeObject$`project`
      self
    }
  )
)
