# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaNext
#' @description MediaNext Class
#' @format An \code{R6Class} generator object
#' @field next  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaNext <- R6::R6Class(
  'MediaNext',
  public = list(
    `next` = NULL,
    initialize = function(`next`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`next`)) {
        stopifnot(is.numeric(`next`), length(`next`) == 1)
        self$`next` <- `next`
      }
    },
    toJSON = function() {
      MediaNextObject <- list()
      if (!is.null(self$`next`)) {
        MediaNextObject[['next']] <-
          self$`next`
      }

      MediaNextObject
    },
    fromJSON = function(MediaNextJson) {
      MediaNextObject <- jsonlite::fromJSON(MediaNextJson)
      if (!is.null(MediaNextObject$`next`)) {
        self$`next` <- MediaNextObject$`next`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`next`)) {
        sprintf(
        '"next":
          %d
                ',
        self$`next`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaNextJson) {
      MediaNextObject <- jsonlite::fromJSON(MediaNextJson)
      self$`next` <- MediaNextObject$`next`
      self
    }
  )
)
