# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaPrev
#' @description MediaPrev Class
#' @format An \code{R6Class} generator object
#' @field prev  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaPrev <- R6::R6Class(
  'MediaPrev',
  public = list(
    `prev` = NULL,
    initialize = function(`prev`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`prev`)) {
        stopifnot(is.numeric(`prev`), length(`prev`) == 1)
        self$`prev` <- `prev`
      }
    },
    toJSON = function() {
      MediaPrevObject <- list()
      if (!is.null(self$`prev`)) {
        MediaPrevObject[['prev']] <-
          self$`prev`
      }

      MediaPrevObject
    },
    fromJSON = function(MediaPrevJson) {
      MediaPrevObject <- jsonlite::fromJSON(MediaPrevJson)
      if (!is.null(MediaPrevObject$`prev`)) {
        self$`prev` <- MediaPrevObject$`prev`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`prev`)) {
        sprintf(
        '"prev":
          %d
                ',
        self$`prev`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaPrevJson) {
      MediaPrevObject <- jsonlite::fromJSON(MediaPrevJson)
      self$`prev` <- MediaPrevObject$`prev`
      self
    }
  )
)
