# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaTypeUpdate
#' @description MediaTypeUpdate Class
#' @format An \code{R6Class} generator object
#' @field description  character [optional]
#'
#' @field file_format  character [optional]
#'
#' @field keep_original  character [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaTypeUpdate <- R6::R6Class(
  'MediaTypeUpdate',
  public = list(
    `description` = NULL,
    `file_format` = NULL,
    `keep_original` = NULL,
    `name` = NULL,
    initialize = function(`description`='', `file_format`=NULL, `keep_original`=TRUE, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`file_format`)) {
        stopifnot(is.character(`file_format`), length(`file_format`) == 1)
        self$`file_format` <- `file_format`
      }
      if (!is.null(`keep_original`)) {
        self$`keep_original` <- `keep_original`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      MediaTypeUpdateObject <- list()
      if (!is.null(self$`description`)) {
        MediaTypeUpdateObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`file_format`)) {
        MediaTypeUpdateObject[['file_format']] <-
          self$`file_format`
      }
      if (!is.null(self$`keep_original`)) {
        MediaTypeUpdateObject[['keep_original']] <-
          self$`keep_original`
      }
      if (!is.null(self$`name`)) {
        MediaTypeUpdateObject[['name']] <-
          self$`name`
      }

      MediaTypeUpdateObject
    },
    fromJSON = function(MediaTypeUpdateJson) {
      MediaTypeUpdateObject <- jsonlite::fromJSON(MediaTypeUpdateJson)
      if (!is.null(MediaTypeUpdateObject$`description`)) {
        self$`description` <- MediaTypeUpdateObject$`description`
      }
      if (!is.null(MediaTypeUpdateObject$`file_format`)) {
        self$`file_format` <- MediaTypeUpdateObject$`file_format`
      }
      if (!is.null(MediaTypeUpdateObject$`keep_original`)) {
        self$`keep_original` <- MediaTypeUpdateObject$`keep_original`
      }
      if (!is.null(MediaTypeUpdateObject$`name`)) {
        self$`name` <- MediaTypeUpdateObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`file_format`)) {
        sprintf(
        '"file_format":
          "%s"
                ',
        self$`file_format`
        )},
        if (!is.null(self$`keep_original`)) {
        sprintf(
        '"keep_original":
          "%s"
                ',
        self$`keep_original`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaTypeUpdateJson) {
      MediaTypeUpdateObject <- jsonlite::fromJSON(MediaTypeUpdateJson)
      self$`description` <- MediaTypeUpdateObject$`description`
      self$`file_format` <- MediaTypeUpdateObject$`file_format`
      self$`keep_original` <- MediaTypeUpdateObject$`keep_original`
      self$`name` <- MediaTypeUpdateObject$`name`
      self
    }
  )
)
