# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaUpdate
#' @description MediaUpdate Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field last_edit_end  character [optional]
#'
#' @field last_edit_start  character [optional]
#'
#' @field media_files  \link{MediaFiles} [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaUpdate <- R6::R6Class(
  'MediaUpdate',
  public = list(
    `attributes` = NULL,
    `last_edit_end` = NULL,
    `last_edit_start` = NULL,
    `media_files` = NULL,
    `name` = NULL,
    initialize = function(`attributes`=NULL, `last_edit_end`=NULL, `last_edit_start`=NULL, `media_files`=NULL, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`last_edit_end`)) {
        stopifnot(is.character(`last_edit_end`), length(`last_edit_end`) == 1)
        self$`last_edit_end` <- `last_edit_end`
      }
      if (!is.null(`last_edit_start`)) {
        stopifnot(is.character(`last_edit_start`), length(`last_edit_start`) == 1)
        self$`last_edit_start` <- `last_edit_start`
      }
      if (!is.null(`media_files`)) {
        stopifnot(R6::is.R6(`media_files`))
        self$`media_files` <- `media_files`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      MediaUpdateObject <- list()
      if (!is.null(self$`attributes`)) {
        MediaUpdateObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`last_edit_end`)) {
        MediaUpdateObject[['last_edit_end']] <-
          self$`last_edit_end`
      }
      if (!is.null(self$`last_edit_start`)) {
        MediaUpdateObject[['last_edit_start']] <-
          self$`last_edit_start`
      }
      if (!is.null(self$`media_files`)) {
        MediaUpdateObject[['media_files']] <-
          self$`media_files`$toJSON()
      }
      if (!is.null(self$`name`)) {
        MediaUpdateObject[['name']] <-
          self$`name`
      }

      MediaUpdateObject
    },
    fromJSON = function(MediaUpdateJson) {
      MediaUpdateObject <- jsonlite::fromJSON(MediaUpdateJson)
      if (!is.null(MediaUpdateObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(MediaUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(MediaUpdateObject$`last_edit_end`)) {
        self$`last_edit_end` <- MediaUpdateObject$`last_edit_end`
      }
      if (!is.null(MediaUpdateObject$`last_edit_start`)) {
        self$`last_edit_start` <- MediaUpdateObject$`last_edit_start`
      }
      if (!is.null(MediaUpdateObject$`media_files`)) {
        media_filesObject <- MediaFiles$new()
        media_filesObject$fromJSON(jsonlite::toJSON(MediaUpdateObject$media_files, auto_unbox = TRUE, digits = NA))
        self$`media_files` <- media_filesObject
      }
      if (!is.null(MediaUpdateObject$`name`)) {
        self$`name` <- MediaUpdateObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`last_edit_end`)) {
        sprintf(
        '"last_edit_end":
          "%s"
                ',
        self$`last_edit_end`
        )},
        if (!is.null(self$`last_edit_start`)) {
        sprintf(
        '"last_edit_start":
          "%s"
                ',
        self$`last_edit_start`
        )},
        if (!is.null(self$`media_files`)) {
        sprintf(
        '"media_files":
        %s
        ',
        jsonlite::toJSON(self$`media_files`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaUpdateJson) {
      MediaUpdateObject <- jsonlite::fromJSON(MediaUpdateJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(MediaUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`last_edit_end` <- MediaUpdateObject$`last_edit_end`
      self$`last_edit_start` <- MediaUpdateObject$`last_edit_start`
      self$`media_files` <- MediaFiles$new()$fromJSON(jsonlite::toJSON(MediaUpdateObject$media_files, auto_unbox = TRUE, digits = NA))
      self$`name` <- MediaUpdateObject$`name`
      self
    }
  )
)
