# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaFiles
#' @description MediaFiles Class
#' @format An \code{R6Class} generator object
#' @field archival  list( \link{VideoDefinition} ) [optional]
#'
#' @field audio  list( \link{AudioDefinition} ) [optional]
#'
#' @field streaming  list( \link{VideoDefinition} ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaFiles <- R6::R6Class(
  'MediaFiles',
  public = list(
    `archival` = NULL,
    `audio` = NULL,
    `streaming` = NULL,
    initialize = function(`archival`=NULL, `audio`=NULL, `streaming`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`archival`)) {
        stopifnot(is.vector(`archival`), length(`archival`) != 0)
        sapply(`archival`, function(x) stopifnot(R6::is.R6(x)))
        self$`archival` <- `archival`
      }
      if (!is.null(`audio`)) {
        stopifnot(is.vector(`audio`), length(`audio`) != 0)
        sapply(`audio`, function(x) stopifnot(R6::is.R6(x)))
        self$`audio` <- `audio`
      }
      if (!is.null(`streaming`)) {
        stopifnot(is.vector(`streaming`), length(`streaming`) != 0)
        sapply(`streaming`, function(x) stopifnot(R6::is.R6(x)))
        self$`streaming` <- `streaming`
      }
    },
    toJSON = function() {
      MediaFilesObject <- list()
      if (!is.null(self$`archival`)) {
        MediaFilesObject[['archival']] <-
          lapply(self$`archival`, function(x) x$toJSON())
      }
      if (!is.null(self$`audio`)) {
        MediaFilesObject[['audio']] <-
          lapply(self$`audio`, function(x) x$toJSON())
      }
      if (!is.null(self$`streaming`)) {
        MediaFilesObject[['streaming']] <-
          lapply(self$`streaming`, function(x) x$toJSON())
      }

      MediaFilesObject
    },
    fromJSON = function(MediaFilesJson) {
      MediaFilesObject <- jsonlite::fromJSON(MediaFilesJson)
      if (!is.null(MediaFilesObject$`archival`)) {
        self$`archival` <- ApiClient$new()$deserializeObj(MediaFilesObject$`archival`, "array[VideoDefinition]", loadNamespace("tator"))
      }
      if (!is.null(MediaFilesObject$`audio`)) {
        self$`audio` <- ApiClient$new()$deserializeObj(MediaFilesObject$`audio`, "array[AudioDefinition]", loadNamespace("tator"))
      }
      if (!is.null(MediaFilesObject$`streaming`)) {
        self$`streaming` <- ApiClient$new()$deserializeObj(MediaFilesObject$`streaming`, "array[VideoDefinition]", loadNamespace("tator"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`archival`)) {
        sprintf(
        '"archival":
        [%s]
',
        paste(sapply(self$`archival`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`audio`)) {
        sprintf(
        '"audio":
        [%s]
',
        paste(sapply(self$`audio`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`streaming`)) {
        sprintf(
        '"streaming":
        [%s]
',
        paste(sapply(self$`streaming`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaFilesJson) {
      MediaFilesObject <- jsonlite::fromJSON(MediaFilesJson)
      self$`archival` <- ApiClient$new()$deserializeObj(MediaFilesObject$`archival`, "array[VideoDefinition]", loadNamespace("tator"))
      self$`audio` <- ApiClient$new()$deserializeObj(MediaFilesObject$`audio`, "array[AudioDefinition]", loadNamespace("tator"))
      self$`streaming` <- ApiClient$new()$deserializeObj(MediaFilesObject$`streaming`, "array[VideoDefinition]", loadNamespace("tator"))
      self
    }
  )
)
