# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MediaTypeSpec
#' @description MediaTypeSpec Class
#' @format An \code{R6Class} generator object
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field default_volume  integer [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character 
#'
#' @field file_format  character [optional]
#'
#' @field keep_original  character [optional]
#'
#' @field name  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MediaTypeSpec <- R6::R6Class(
  'MediaTypeSpec',
  public = list(
    `attribute_types` = NULL,
    `default_volume` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `file_format` = NULL,
    `keep_original` = NULL,
    `name` = NULL,
    initialize = function(`dtype`, `name`, `attribute_types`=NULL, `default_volume`=NULL, `description`='', `file_format`=NULL, `keep_original`=TRUE, ...){
      local.optional.var <- list(...)
      if (!missing(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`default_volume`)) {
        stopifnot(is.numeric(`default_volume`), length(`default_volume`) == 1)
        self$`default_volume` <- `default_volume`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`file_format`)) {
        stopifnot(is.character(`file_format`), length(`file_format`) == 1)
        self$`file_format` <- `file_format`
      }
      if (!is.null(`keep_original`)) {
        stopifnot(is.logical(`keep_original`))
        self$`keep_original` <- `keep_original`
      }
    },
    toJSON = function() {
      MediaTypeSpecObject <- list()
      if (!is.null(self$`attribute_types`)) {
        MediaTypeSpecObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`default_volume`)) {
        MediaTypeSpecObject[['default_volume']] <-
          self$`default_volume`
      }
      if (!is.null(self$`description`)) {
        MediaTypeSpecObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        MediaTypeSpecObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`file_format`)) {
        MediaTypeSpecObject[['file_format']] <-
          self$`file_format`
      }
      if (!is.null(self$`keep_original`)) {
        stopifnot(is.logical(`keep_original`))
        MediaTypeSpecObject[['keep_original']] <-
          self$`keep_original`
      }
      if (!is.null(self$`name`)) {
        MediaTypeSpecObject[['name']] <-
          self$`name`
      }

      MediaTypeSpecObject
    },
    fromJSON = function(MediaTypeSpecJson) {
      MediaTypeSpecObject <- jsonlite::fromJSON(MediaTypeSpecJson)
      if (!is.null(MediaTypeSpecObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(MediaTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(MediaTypeSpecObject$`default_volume`)) {
        self$`default_volume` <- MediaTypeSpecObject$`default_volume`
      }
      if (!is.null(MediaTypeSpecObject$`description`)) {
        self$`description` <- MediaTypeSpecObject$`description`
      }
      if (!is.null(MediaTypeSpecObject$`dtype`)) {
        self$`dtype` <- MediaTypeSpecObject$`dtype`
      }
      if (!is.null(MediaTypeSpecObject$`file_format`)) {
        self$`file_format` <- MediaTypeSpecObject$`file_format`
      }
      if (!is.null(MediaTypeSpecObject$`keep_original`)) {
        self$`keep_original` <- MediaTypeSpecObject$`keep_original`
      }
      if (!is.null(MediaTypeSpecObject$`name`)) {
        self$`name` <- MediaTypeSpecObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`default_volume`)) {
        sprintf(
        '"default_volume":
          %d
                ',
        self$`default_volume`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`file_format`)) {
        sprintf(
        '"file_format":
          "%s"
                ',
        self$`file_format`
        )},
        if (!is.null(self$`keep_original`)) {
        sprintf(
        '"keep_original":
          %s
                ',
        jsonlite::toJSON(self$`keep_original`, auto_unbox = TRUE)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MediaTypeSpecJson) {
      MediaTypeSpecObject <- jsonlite::fromJSON(MediaTypeSpecJson)
      self$`attribute_types` <- ApiClient$new()$deserializeObj(MediaTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`default_volume` <- MediaTypeSpecObject$`default_volume`
      self$`description` <- MediaTypeSpecObject$`description`
      self$`dtype` <- MediaTypeSpecObject$`dtype`
      self$`file_format` <- MediaTypeSpecObject$`file_format`
      self$`keep_original` <- MediaTypeSpecObject$`keep_original`
      self$`name` <- MediaTypeSpecObject$`name`
      self
    }
  )
)
