# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MembershipUpdate
#' @description MembershipUpdate Class
#' @format An \code{R6Class} generator object
#' @field permission  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MembershipUpdate <- R6::R6Class(
  'MembershipUpdate',
  public = list(
    `permission` = NULL,
    initialize = function(`permission`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`permission`)) {
        stopifnot(is.character(`permission`), length(`permission`) == 1)
        self$`permission` <- `permission`
      }
    },
    toJSON = function() {
      MembershipUpdateObject <- list()
      if (!is.null(self$`permission`)) {
        MembershipUpdateObject[['permission']] <-
          self$`permission`
      }

      MembershipUpdateObject
    },
    fromJSON = function(MembershipUpdateJson) {
      MembershipUpdateObject <- jsonlite::fromJSON(MembershipUpdateJson)
      if (!is.null(MembershipUpdateObject$`permission`)) {
        self$`permission` <- MembershipUpdateObject$`permission`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`permission`)) {
        sprintf(
        '"permission":
          "%s"
                ',
        self$`permission`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MembershipUpdateJson) {
      MembershipUpdateObject <- jsonlite::fromJSON(MembershipUpdateJson)
      self$`permission` <- MembershipUpdateObject$`permission`
      self
    }
  )
)
