# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MembershipSpec
#' @description MembershipSpec Class
#' @format An \code{R6Class} generator object
#' @field permission  character [optional]
#'
#' @field user  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MembershipSpec <- R6::R6Class(
  'MembershipSpec',
  public = list(
    `permission` = NULL,
    `user` = NULL,
    initialize = function(`permission`=NULL, `user`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`permission`)) {
        stopifnot(is.character(`permission`), length(`permission`) == 1)
        self$`permission` <- `permission`
      }
      if (!is.null(`user`)) {
        stopifnot(is.numeric(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
    },
    toJSON = function() {
      MembershipSpecObject <- list()
      if (!is.null(self$`permission`)) {
        MembershipSpecObject[['permission']] <-
          self$`permission`
      }
      if (!is.null(self$`user`)) {
        MembershipSpecObject[['user']] <-
          self$`user`
      }

      MembershipSpecObject
    },
    fromJSON = function(MembershipSpecJson) {
      MembershipSpecObject <- jsonlite::fromJSON(MembershipSpecJson)
      if (!is.null(MembershipSpecObject$`permission`)) {
        self$`permission` <- MembershipSpecObject$`permission`
      }
      if (!is.null(MembershipSpecObject$`user`)) {
        self$`user` <- MembershipSpecObject$`user`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`permission`)) {
        sprintf(
        '"permission":
          "%s"
                ',
        self$`permission`
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
          %d
                ',
        self$`user`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MembershipSpecJson) {
      MembershipSpecObject <- jsonlite::fromJSON(MembershipSpecJson)
      self$`permission` <- MembershipSpecObject$`permission`
      self$`user` <- MembershipSpecObject$`user`
      self
    }
  )
)
