# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Membership
#' @description Membership Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field permission  character [optional]
#'
#' @field username  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Membership <- R6::R6Class(
  'Membership',
  public = list(
    `id` = NULL,
    `permission` = NULL,
    `username` = NULL,
    initialize = function(`id`=NULL, `permission`=NULL, `username`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`permission`)) {
        stopifnot(is.character(`permission`), length(`permission`) == 1)
        self$`permission` <- `permission`
      }
      if (!is.null(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
    },
    toJSON = function() {
      MembershipObject <- list()
      if (!is.null(self$`id`)) {
        MembershipObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`permission`)) {
        MembershipObject[['permission']] <-
          self$`permission`
      }
      if (!is.null(self$`username`)) {
        MembershipObject[['username']] <-
          self$`username`
      }

      MembershipObject
    },
    fromJSON = function(MembershipJson) {
      MembershipObject <- jsonlite::fromJSON(MembershipJson)
      if (!is.null(MembershipObject$`id`)) {
        self$`id` <- MembershipObject$`id`
      }
      if (!is.null(MembershipObject$`permission`)) {
        self$`permission` <- MembershipObject$`permission`
      }
      if (!is.null(MembershipObject$`username`)) {
        self$`username` <- MembershipObject$`username`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`permission`)) {
        sprintf(
        '"permission":
          "%s"
                ',
        self$`permission`
        )},
        if (!is.null(self$`username`)) {
        sprintf(
        '"username":
          "%s"
                ',
        self$`username`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MembershipJson) {
      MembershipObject <- jsonlite::fromJSON(MembershipJson)
      self$`id` <- MembershipObject$`id`
      self$`permission` <- MembershipObject$`permission`
      self$`username` <- MembershipObject$`username`
      self
    }
  )
)
