# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title MessageResponse
#' @description MessageResponse Class
#' @format An \code{R6Class} generator object
#' @field message  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
MessageResponse <- R6::R6Class(
  'MessageResponse',
  public = list(
    `message` = NULL,
    initialize = function(`message`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
    },
    toJSON = function() {
      MessageResponseObject <- list()
      if (!is.null(self$`message`)) {
        MessageResponseObject[['message']] <-
          self$`message`
      }

      MessageResponseObject
    },
    fromJSON = function(MessageResponseJson) {
      MessageResponseObject <- jsonlite::fromJSON(MessageResponseJson)
      if (!is.null(MessageResponseObject$`message`)) {
        self$`message` <- MessageResponseObject$`message`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(MessageResponseJson) {
      MessageResponseObject <- jsonlite::fromJSON(MessageResponseJson)
      self$`message` <- MessageResponseObject$`message`
      self
    }
  )
)
