# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title NotifySpec
#' @description NotifySpec Class
#' @format An \code{R6Class} generator object
#' @field message  character 
#'
#' @field sendAsFile  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
NotifySpec <- R6::R6Class(
  'NotifySpec',
  public = list(
    `message` = NULL,
    `sendAsFile` = NULL,
    initialize = function(`message`, `sendAsFile`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`sendAsFile`)) {
        stopifnot(is.numeric(`sendAsFile`), length(`sendAsFile`) == 1)
        self$`sendAsFile` <- `sendAsFile`
      }
    },
    toJSON = function() {
      NotifySpecObject <- list()
      if (!is.null(self$`message`)) {
        NotifySpecObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`sendAsFile`)) {
        NotifySpecObject[['sendAsFile']] <-
          self$`sendAsFile`
      }

      NotifySpecObject
    },
    fromJSON = function(NotifySpecJson) {
      NotifySpecObject <- jsonlite::fromJSON(NotifySpecJson)
      if (!is.null(NotifySpecObject$`message`)) {
        self$`message` <- NotifySpecObject$`message`
      }
      if (!is.null(NotifySpecObject$`sendAsFile`)) {
        self$`sendAsFile` <- NotifySpecObject$`sendAsFile`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`sendAsFile`)) {
        sprintf(
        '"sendAsFile":
          %d
                ',
        self$`sendAsFile`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(NotifySpecJson) {
      NotifySpecObject <- jsonlite::fromJSON(NotifySpecJson)
      self$`message` <- NotifySpecObject$`message`
      self$`sendAsFile` <- NotifySpecObject$`sendAsFile`
      self
    }
  )
)
