# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProgressSummarySpec
#' @description ProgressSummarySpec Class
#' @format An \code{R6Class} generator object
#' @field gid  character 
#'
#' @field num_complete  integer 
#'
#' @field num_jobs  integer 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProgressSummarySpec <- R6::R6Class(
  'ProgressSummarySpec',
  public = list(
    `gid` = NULL,
    `num_complete` = NULL,
    `num_jobs` = NULL,
    initialize = function(`gid`, `num_complete`, `num_jobs`, ...){
      local.optional.var <- list(...)
      if (!missing(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!missing(`num_complete`)) {
        stopifnot(is.numeric(`num_complete`), length(`num_complete`) == 1)
        self$`num_complete` <- `num_complete`
      }
      if (!missing(`num_jobs`)) {
        stopifnot(is.numeric(`num_jobs`), length(`num_jobs`) == 1)
        self$`num_jobs` <- `num_jobs`
      }
    },
    toJSON = function() {
      ProgressSummarySpecObject <- list()
      if (!is.null(self$`gid`)) {
        ProgressSummarySpecObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`num_complete`)) {
        ProgressSummarySpecObject[['num_complete']] <-
          self$`num_complete`
      }
      if (!is.null(self$`num_jobs`)) {
        ProgressSummarySpecObject[['num_jobs']] <-
          self$`num_jobs`
      }

      ProgressSummarySpecObject
    },
    fromJSON = function(ProgressSummarySpecJson) {
      ProgressSummarySpecObject <- jsonlite::fromJSON(ProgressSummarySpecJson)
      if (!is.null(ProgressSummarySpecObject$`gid`)) {
        self$`gid` <- ProgressSummarySpecObject$`gid`
      }
      if (!is.null(ProgressSummarySpecObject$`num_complete`)) {
        self$`num_complete` <- ProgressSummarySpecObject$`num_complete`
      }
      if (!is.null(ProgressSummarySpecObject$`num_jobs`)) {
        self$`num_jobs` <- ProgressSummarySpecObject$`num_jobs`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`num_complete`)) {
        sprintf(
        '"num_complete":
          %d
                ',
        self$`num_complete`
        )},
        if (!is.null(self$`num_jobs`)) {
        sprintf(
        '"num_jobs":
          %d
                ',
        self$`num_jobs`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ProgressSummarySpecJson) {
      ProgressSummarySpecObject <- jsonlite::fromJSON(ProgressSummarySpecJson)
      self$`gid` <- ProgressSummarySpecObject$`gid`
      self$`num_complete` <- ProgressSummarySpecObject$`num_complete`
      self$`num_jobs` <- ProgressSummarySpecObject$`num_jobs`
      self
    }
  )
)
