# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProgressSpec
#' @description ProgressSpec Class
#' @format An \code{R6Class} generator object
#' @field gid  character 
#'
#' @field job_type  character 
#'
#' @field media_ids  character [optional]
#'
#' @field message  character 
#'
#' @field name  character 
#'
#' @field progress  numeric 
#'
#' @field section  character [optional]
#'
#' @field sections  character [optional]
#'
#' @field state  character 
#'
#' @field swid  character [optional]
#'
#' @field uid  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProgressSpec <- R6::R6Class(
  'ProgressSpec',
  public = list(
    `gid` = NULL,
    `job_type` = NULL,
    `media_ids` = NULL,
    `message` = NULL,
    `name` = NULL,
    `progress` = NULL,
    `section` = NULL,
    `sections` = NULL,
    `state` = NULL,
    `swid` = NULL,
    `uid` = NULL,
    initialize = function(`gid`, `job_type`, `message`, `name`, `progress`, `state`, `uid`, `media_ids`=NULL, `section`=NULL, `sections`=NULL, `swid`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!missing(`job_type`)) {
        stopifnot(is.character(`job_type`), length(`job_type`) == 1)
        self$`job_type` <- `job_type`
      }
      if (!missing(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`progress`)) {
        self$`progress` <- `progress`
      }
      if (!missing(`state`)) {
        stopifnot(is.character(`state`), length(`state`) == 1)
        self$`state` <- `state`
      }
      if (!missing(`uid`)) {
        stopifnot(is.character(`uid`), length(`uid`) == 1)
        self$`uid` <- `uid`
      }
      if (!is.null(`media_ids`)) {
        stopifnot(is.character(`media_ids`), length(`media_ids`) == 1)
        self$`media_ids` <- `media_ids`
      }
      if (!is.null(`section`)) {
        stopifnot(is.character(`section`), length(`section`) == 1)
        self$`section` <- `section`
      }
      if (!is.null(`sections`)) {
        stopifnot(is.character(`sections`), length(`sections`) == 1)
        self$`sections` <- `sections`
      }
      if (!is.null(`swid`)) {
        stopifnot(is.character(`swid`), length(`swid`) == 1)
        self$`swid` <- `swid`
      }
    },
    toJSON = function() {
      ProgressSpecObject <- list()
      if (!is.null(self$`gid`)) {
        ProgressSpecObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`job_type`)) {
        ProgressSpecObject[['job_type']] <-
          self$`job_type`
      }
      if (!is.null(self$`media_ids`)) {
        ProgressSpecObject[['media_ids']] <-
          self$`media_ids`
      }
      if (!is.null(self$`message`)) {
        ProgressSpecObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`name`)) {
        ProgressSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`progress`)) {
        ProgressSpecObject[['progress']] <-
          self$`progress`
      }
      if (!is.null(self$`section`)) {
        ProgressSpecObject[['section']] <-
          self$`section`
      }
      if (!is.null(self$`sections`)) {
        ProgressSpecObject[['sections']] <-
          self$`sections`
      }
      if (!is.null(self$`state`)) {
        ProgressSpecObject[['state']] <-
          self$`state`
      }
      if (!is.null(self$`swid`)) {
        ProgressSpecObject[['swid']] <-
          self$`swid`
      }
      if (!is.null(self$`uid`)) {
        ProgressSpecObject[['uid']] <-
          self$`uid`
      }

      ProgressSpecObject
    },
    fromJSON = function(ProgressSpecJson) {
      ProgressSpecObject <- jsonlite::fromJSON(ProgressSpecJson)
      if (!is.null(ProgressSpecObject$`gid`)) {
        self$`gid` <- ProgressSpecObject$`gid`
      }
      if (!is.null(ProgressSpecObject$`job_type`)) {
        self$`job_type` <- ProgressSpecObject$`job_type`
      }
      if (!is.null(ProgressSpecObject$`media_ids`)) {
        self$`media_ids` <- ProgressSpecObject$`media_ids`
      }
      if (!is.null(ProgressSpecObject$`message`)) {
        self$`message` <- ProgressSpecObject$`message`
      }
      if (!is.null(ProgressSpecObject$`name`)) {
        self$`name` <- ProgressSpecObject$`name`
      }
      if (!is.null(ProgressSpecObject$`progress`)) {
        self$`progress` <- ProgressSpecObject$`progress`
      }
      if (!is.null(ProgressSpecObject$`section`)) {
        self$`section` <- ProgressSpecObject$`section`
      }
      if (!is.null(ProgressSpecObject$`sections`)) {
        self$`sections` <- ProgressSpecObject$`sections`
      }
      if (!is.null(ProgressSpecObject$`state`)) {
        self$`state` <- ProgressSpecObject$`state`
      }
      if (!is.null(ProgressSpecObject$`swid`)) {
        self$`swid` <- ProgressSpecObject$`swid`
      }
      if (!is.null(ProgressSpecObject$`uid`)) {
        self$`uid` <- ProgressSpecObject$`uid`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`job_type`)) {
        sprintf(
        '"job_type":
          "%s"
                ',
        self$`job_type`
        )},
        if (!is.null(self$`media_ids`)) {
        sprintf(
        '"media_ids":
          "%s"
                ',
        self$`media_ids`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`progress`)) {
        sprintf(
        '"progress":
          %d
                ',
        self$`progress`
        )},
        if (!is.null(self$`section`)) {
        sprintf(
        '"section":
          "%s"
                ',
        self$`section`
        )},
        if (!is.null(self$`sections`)) {
        sprintf(
        '"sections":
          "%s"
                ',
        self$`sections`
        )},
        if (!is.null(self$`state`)) {
        sprintf(
        '"state":
          "%s"
                ',
        self$`state`
        )},
        if (!is.null(self$`swid`)) {
        sprintf(
        '"swid":
          "%s"
                ',
        self$`swid`
        )},
        if (!is.null(self$`uid`)) {
        sprintf(
        '"uid":
          "%s"
                ',
        self$`uid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ProgressSpecJson) {
      ProgressSpecObject <- jsonlite::fromJSON(ProgressSpecJson)
      self$`gid` <- ProgressSpecObject$`gid`
      self$`job_type` <- ProgressSpecObject$`job_type`
      self$`media_ids` <- ProgressSpecObject$`media_ids`
      self$`message` <- ProgressSpecObject$`message`
      self$`name` <- ProgressSpecObject$`name`
      self$`progress` <- ProgressSpecObject$`progress`
      self$`section` <- ProgressSpecObject$`section`
      self$`sections` <- ProgressSpecObject$`sections`
      self$`state` <- ProgressSpecObject$`state`
      self$`swid` <- ProgressSpecObject$`swid`
      self$`uid` <- ProgressSpecObject$`uid`
      self
    }
  )
)
