# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Project
#' @description Project Class
#' @format An \code{R6Class} generator object
#' @field id  integer [optional]
#'
#' @field name  character [optional]
#'
#' @field num_files  integer [optional]
#'
#' @field permission  character [optional]
#'
#' @field size  integer [optional]
#'
#' @field summary  character [optional]
#'
#' @field thumb  character [optional]
#'
#' @field usernames  list( character ) [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Project <- R6::R6Class(
  'Project',
  public = list(
    `id` = NULL,
    `name` = NULL,
    `num_files` = NULL,
    `permission` = NULL,
    `size` = NULL,
    `summary` = NULL,
    `thumb` = NULL,
    `usernames` = NULL,
    initialize = function(`id`=NULL, `name`=NULL, `num_files`=NULL, `permission`=NULL, `size`=NULL, `summary`='', `thumb`=NULL, `usernames`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`num_files`)) {
        stopifnot(is.numeric(`num_files`), length(`num_files`) == 1)
        self$`num_files` <- `num_files`
      }
      if (!is.null(`permission`)) {
        stopifnot(is.character(`permission`), length(`permission`) == 1)
        self$`permission` <- `permission`
      }
      if (!is.null(`size`)) {
        stopifnot(is.numeric(`size`), length(`size`) == 1)
        self$`size` <- `size`
      }
      if (!is.null(`summary`)) {
        stopifnot(is.character(`summary`), length(`summary`) == 1)
        self$`summary` <- `summary`
      }
      if (!is.null(`thumb`)) {
        stopifnot(is.character(`thumb`), length(`thumb`) == 1)
        self$`thumb` <- `thumb`
      }
      if (!is.null(`usernames`)) {
        stopifnot(is.vector(`usernames`), length(`usernames`) != 0)
        sapply(`usernames`, function(x) stopifnot(is.character(x)))
        self$`usernames` <- `usernames`
      }
    },
    toJSON = function() {
      ProjectObject <- list()
      if (!is.null(self$`id`)) {
        ProjectObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`name`)) {
        ProjectObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`num_files`)) {
        ProjectObject[['num_files']] <-
          self$`num_files`
      }
      if (!is.null(self$`permission`)) {
        ProjectObject[['permission']] <-
          self$`permission`
      }
      if (!is.null(self$`size`)) {
        ProjectObject[['size']] <-
          self$`size`
      }
      if (!is.null(self$`summary`)) {
        ProjectObject[['summary']] <-
          self$`summary`
      }
      if (!is.null(self$`thumb`)) {
        ProjectObject[['thumb']] <-
          self$`thumb`
      }
      if (!is.null(self$`usernames`)) {
        ProjectObject[['usernames']] <-
          self$`usernames`
      }

      ProjectObject
    },
    fromJSON = function(ProjectJson) {
      ProjectObject <- jsonlite::fromJSON(ProjectJson)
      if (!is.null(ProjectObject$`id`)) {
        self$`id` <- ProjectObject$`id`
      }
      if (!is.null(ProjectObject$`name`)) {
        self$`name` <- ProjectObject$`name`
      }
      if (!is.null(ProjectObject$`num_files`)) {
        self$`num_files` <- ProjectObject$`num_files`
      }
      if (!is.null(ProjectObject$`permission`)) {
        self$`permission` <- ProjectObject$`permission`
      }
      if (!is.null(ProjectObject$`size`)) {
        self$`size` <- ProjectObject$`size`
      }
      if (!is.null(ProjectObject$`summary`)) {
        self$`summary` <- ProjectObject$`summary`
      }
      if (!is.null(ProjectObject$`thumb`)) {
        self$`thumb` <- ProjectObject$`thumb`
      }
      if (!is.null(ProjectObject$`usernames`)) {
        self$`usernames` <- ApiClient$new()$deserializeObj(ProjectObject$`usernames`, "array[character]", loadNamespace("tator"))
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`num_files`)) {
        sprintf(
        '"num_files":
          %d
                ',
        self$`num_files`
        )},
        if (!is.null(self$`permission`)) {
        sprintf(
        '"permission":
          "%s"
                ',
        self$`permission`
        )},
        if (!is.null(self$`size`)) {
        sprintf(
        '"size":
          %d
                ',
        self$`size`
        )},
        if (!is.null(self$`summary`)) {
        sprintf(
        '"summary":
          "%s"
                ',
        self$`summary`
        )},
        if (!is.null(self$`thumb`)) {
        sprintf(
        '"thumb":
          "%s"
                ',
        self$`thumb`
        )},
        if (!is.null(self$`usernames`)) {
        sprintf(
        '"usernames":
           [%s]
        ',
        paste(unlist(lapply(self$`usernames`, function(x) paste0('"', x, '"'))), collapse=",")
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ProjectJson) {
      ProjectObject <- jsonlite::fromJSON(ProjectJson)
      self$`id` <- ProjectObject$`id`
      self$`name` <- ProjectObject$`name`
      self$`num_files` <- ProjectObject$`num_files`
      self$`permission` <- ProjectObject$`permission`
      self$`size` <- ProjectObject$`size`
      self$`summary` <- ProjectObject$`summary`
      self$`thumb` <- ProjectObject$`thumb`
      self$`usernames` <- ApiClient$new()$deserializeObj(ProjectObject$`usernames`, "array[character]", loadNamespace("tator"))
      self
    }
  )
)
