# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title ProjectSpec
#' @description ProjectSpec Class
#' @format An \code{R6Class} generator object
#' @field name  character 
#'
#' @field summary  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
ProjectSpec <- R6::R6Class(
  'ProjectSpec',
  public = list(
    `name` = NULL,
    `summary` = NULL,
    initialize = function(`name`, `summary`='', ...){
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`summary`)) {
        stopifnot(is.character(`summary`), length(`summary`) == 1)
        self$`summary` <- `summary`
      }
    },
    toJSON = function() {
      ProjectSpecObject <- list()
      if (!is.null(self$`name`)) {
        ProjectSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`summary`)) {
        ProjectSpecObject[['summary']] <-
          self$`summary`
      }

      ProjectSpecObject
    },
    fromJSON = function(ProjectSpecJson) {
      ProjectSpecObject <- jsonlite::fromJSON(ProjectSpecJson)
      if (!is.null(ProjectSpecObject$`name`)) {
        self$`name` <- ProjectSpecObject$`name`
      }
      if (!is.null(ProjectSpecObject$`summary`)) {
        self$`summary` <- ProjectSpecObject$`summary`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`summary`)) {
        sprintf(
        '"summary":
          "%s"
                ',
        self$`summary`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(ProjectSpecJson) {
      ProjectSpecObject <- jsonlite::fromJSON(ProjectSpecJson)
      self$`name` <- ProjectSpecObject$`name`
      self$`summary` <- ProjectSpecObject$`summary`
      self
    }
  )
)
