# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StateTypeSpec
#' @description StateTypeSpec Class
#' @format An \code{R6Class} generator object
#' @field association  character 
#'
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field description  character [optional]
#'
#' @field media_types  list( integer ) 
#'
#' @field name  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StateTypeSpec <- R6::R6Class(
  'StateTypeSpec',
  public = list(
    `association` = NULL,
    `attribute_types` = NULL,
    `description` = NULL,
    `media_types` = NULL,
    `name` = NULL,
    initialize = function(`association`, `media_types`, `name`, `attribute_types`=NULL, `description`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`association`)) {
        stopifnot(is.character(`association`), length(`association`) == 1)
        self$`association` <- `association`
      }
      if (!missing(`media_types`)) {
        stopifnot(is.vector(`media_types`), length(`media_types`) != 0)
        sapply(`media_types`, function(x) stopifnot(is.character(x)))
        self$`media_types` <- `media_types`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
    },
    toJSON = function() {
      StateTypeSpecObject <- list()
      if (!is.null(self$`association`)) {
        StateTypeSpecObject[['association']] <-
          self$`association`
      }
      if (!is.null(self$`attribute_types`)) {
        StateTypeSpecObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`description`)) {
        StateTypeSpecObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`media_types`)) {
        StateTypeSpecObject[['media_types']] <-
          self$`media_types`
      }
      if (!is.null(self$`name`)) {
        StateTypeSpecObject[['name']] <-
          self$`name`
      }

      StateTypeSpecObject
    },
    fromJSON = function(StateTypeSpecJson) {
      StateTypeSpecObject <- jsonlite::fromJSON(StateTypeSpecJson)
      if (!is.null(StateTypeSpecObject$`association`)) {
        self$`association` <- StateTypeSpecObject$`association`
      }
      if (!is.null(StateTypeSpecObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(StateTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(StateTypeSpecObject$`description`)) {
        self$`description` <- StateTypeSpecObject$`description`
      }
      if (!is.null(StateTypeSpecObject$`media_types`)) {
        self$`media_types` <- ApiClient$new()$deserializeObj(StateTypeSpecObject$`media_types`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(StateTypeSpecObject$`name`)) {
        self$`name` <- StateTypeSpecObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`association`)) {
        sprintf(
        '"association":
          "%s"
                ',
        self$`association`
        )},
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`media_types`)) {
        sprintf(
        '"media_types":
           [%s]
        ',
        paste(unlist(lapply(self$`media_types`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StateTypeSpecJson) {
      StateTypeSpecObject <- jsonlite::fromJSON(StateTypeSpecJson)
      self$`association` <- StateTypeSpecObject$`association`
      self$`attribute_types` <- ApiClient$new()$deserializeObj(StateTypeSpecObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`description` <- StateTypeSpecObject$`description`
      self$`media_types` <- ApiClient$new()$deserializeObj(StateTypeSpecObject$`media_types`, "array[integer]", loadNamespace("tator"))
      self$`name` <- StateTypeSpecObject$`name`
      self
    }
  )
)
