# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StateTypeUpdate
#' @description StateTypeUpdate Class
#' @format An \code{R6Class} generator object
#' @field description  character [optional]
#'
#' @field name  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StateTypeUpdate <- R6::R6Class(
  'StateTypeUpdate',
  public = list(
    `description` = NULL,
    `name` = NULL,
    initialize = function(`description`=NULL, `name`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
    },
    toJSON = function() {
      StateTypeUpdateObject <- list()
      if (!is.null(self$`description`)) {
        StateTypeUpdateObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`name`)) {
        StateTypeUpdateObject[['name']] <-
          self$`name`
      }

      StateTypeUpdateObject
    },
    fromJSON = function(StateTypeUpdateJson) {
      StateTypeUpdateObject <- jsonlite::fromJSON(StateTypeUpdateJson)
      if (!is.null(StateTypeUpdateObject$`description`)) {
        self$`description` <- StateTypeUpdateObject$`description`
      }
      if (!is.null(StateTypeUpdateObject$`name`)) {
        self$`name` <- StateTypeUpdateObject$`name`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StateTypeUpdateJson) {
      StateTypeUpdateObject <- jsonlite::fromJSON(StateTypeUpdateJson)
      self$`description` <- StateTypeUpdateObject$`description`
      self$`name` <- StateTypeUpdateObject$`name`
      self
    }
  )
)
