# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title State
#' @description State Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field frame  integer [optional]
#'
#' @field id  integer [optional]
#'
#' @field localizations  list( integer ) [optional]
#'
#' @field media  list( integer ) [optional]
#'
#' @field meta  integer [optional]
#'
#' @field modified  character [optional]
#'
#' @field version  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
State <- R6::R6Class(
  'State',
  public = list(
    `attributes` = NULL,
    `frame` = NULL,
    `id` = NULL,
    `localizations` = NULL,
    `media` = NULL,
    `meta` = NULL,
    `modified` = NULL,
    `version` = NULL,
    initialize = function(`attributes`=NULL, `frame`=NULL, `id`=NULL, `localizations`=NULL, `media`=NULL, `meta`=NULL, `modified`=NULL, `version`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`frame`)) {
        stopifnot(is.numeric(`frame`), length(`frame`) == 1)
        self$`frame` <- `frame`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`localizations`)) {
        stopifnot(is.vector(`localizations`), length(`localizations`) != 0)
        sapply(`localizations`, function(x) stopifnot(is.character(x)))
        self$`localizations` <- `localizations`
      }
      if (!is.null(`media`)) {
        stopifnot(is.vector(`media`), length(`media`) != 0)
        sapply(`media`, function(x) stopifnot(is.character(x)))
        self$`media` <- `media`
      }
      if (!is.null(`meta`)) {
        stopifnot(is.numeric(`meta`), length(`meta`) == 1)
        self$`meta` <- `meta`
      }
      if (!is.null(`modified`)) {
        self$`modified` <- `modified`
      }
      if (!is.null(`version`)) {
        stopifnot(is.numeric(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      StateObject <- list()
      if (!is.null(self$`attributes`)) {
        StateObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`frame`)) {
        StateObject[['frame']] <-
          self$`frame`
      }
      if (!is.null(self$`id`)) {
        StateObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`localizations`)) {
        StateObject[['localizations']] <-
          self$`localizations`
      }
      if (!is.null(self$`media`)) {
        StateObject[['media']] <-
          self$`media`
      }
      if (!is.null(self$`meta`)) {
        StateObject[['meta']] <-
          self$`meta`
      }
      if (!is.null(self$`modified`)) {
        StateObject[['modified']] <-
          self$`modified`
      }
      if (!is.null(self$`version`)) {
        StateObject[['version']] <-
          self$`version`
      }

      StateObject
    },
    fromJSON = function(StateJson) {
      StateObject <- jsonlite::fromJSON(StateJson)
      if (!is.null(StateObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(StateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(StateObject$`frame`)) {
        self$`frame` <- StateObject$`frame`
      }
      if (!is.null(StateObject$`id`)) {
        self$`id` <- StateObject$`id`
      }
      if (!is.null(StateObject$`localizations`)) {
        self$`localizations` <- ApiClient$new()$deserializeObj(StateObject$`localizations`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(StateObject$`media`)) {
        self$`media` <- ApiClient$new()$deserializeObj(StateObject$`media`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(StateObject$`meta`)) {
        self$`meta` <- StateObject$`meta`
      }
      if (!is.null(StateObject$`modified`)) {
        self$`modified` <- StateObject$`modified`
      }
      if (!is.null(StateObject$`version`)) {
        self$`version` <- StateObject$`version`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`frame`)) {
        sprintf(
        '"frame":
          %d
                ',
        self$`frame`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`localizations`)) {
        sprintf(
        '"localizations":
           [%s]
        ',
        paste(unlist(lapply(self$`localizations`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`media`)) {
        sprintf(
        '"media":
           [%s]
        ',
        paste(unlist(lapply(self$`media`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`meta`)) {
        sprintf(
        '"meta":
          %d
                ',
        self$`meta`
        )},
        if (!is.null(self$`modified`)) {
        sprintf(
        '"modified":
          "%s"
                ',
        self$`modified`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          %d
                ',
        self$`version`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StateJson) {
      StateObject <- jsonlite::fromJSON(StateJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(StateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`frame` <- StateObject$`frame`
      self$`id` <- StateObject$`id`
      self$`localizations` <- ApiClient$new()$deserializeObj(StateObject$`localizations`, "array[integer]", loadNamespace("tator"))
      self$`media` <- ApiClient$new()$deserializeObj(StateObject$`media`, "array[integer]", loadNamespace("tator"))
      self$`meta` <- StateObject$`meta`
      self$`modified` <- StateObject$`modified`
      self$`version` <- StateObject$`version`
      self
    }
  )
)
