# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StateUpdate
#' @description StateUpdate Class
#' @format An \code{R6Class} generator object
#' @field attributes  named list( \link{AnyType} ) [optional]
#'
#' @field frame  integer [optional]
#'
#' @field modified  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StateUpdate <- R6::R6Class(
  'StateUpdate',
  public = list(
    `attributes` = NULL,
    `frame` = NULL,
    `modified` = NULL,
    initialize = function(`attributes`=NULL, `frame`=NULL, `modified`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`attributes`)) {
        stopifnot(is.vector(`attributes`), length(`attributes`) != 0)
        sapply(`attributes`, function(x) stopifnot(R6::is.R6(x)))
        self$`attributes` <- `attributes`
      }
      if (!is.null(`frame`)) {
        stopifnot(is.numeric(`frame`), length(`frame`) == 1)
        self$`frame` <- `frame`
      }
      if (!is.null(`modified`)) {
        self$`modified` <- `modified`
      }
    },
    toJSON = function() {
      StateUpdateObject <- list()
      if (!is.null(self$`attributes`)) {
        StateUpdateObject[['attributes']] <-
          lapply(self$`attributes`, function(x) x$toJSON())
      }
      if (!is.null(self$`frame`)) {
        StateUpdateObject[['frame']] <-
          self$`frame`
      }
      if (!is.null(self$`modified`)) {
        StateUpdateObject[['modified']] <-
          self$`modified`
      }

      StateUpdateObject
    },
    fromJSON = function(StateUpdateJson) {
      StateUpdateObject <- jsonlite::fromJSON(StateUpdateJson)
      if (!is.null(StateUpdateObject$`attributes`)) {
        self$`attributes` <- ApiClient$new()$deserializeObj(StateUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      }
      if (!is.null(StateUpdateObject$`frame`)) {
        self$`frame` <- StateUpdateObject$`frame`
      }
      if (!is.null(StateUpdateObject$`modified`)) {
        self$`modified` <- StateUpdateObject$`modified`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`attributes`)) {
        sprintf(
        '"attributes":
        %s
',
        jsonlite::toJSON(lapply(self$`attributes`, function(x){ x$toJSON() }), auto_unbox = TRUE, digits=NA)
        )},
        if (!is.null(self$`frame`)) {
        sprintf(
        '"frame":
          %d
                ',
        self$`frame`
        )},
        if (!is.null(self$`modified`)) {
        sprintf(
        '"modified":
          "%s"
                ',
        self$`modified`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StateUpdateJson) {
      StateUpdateObject <- jsonlite::fromJSON(StateUpdateJson)
      self$`attributes` <- ApiClient$new()$deserializeObj(StateUpdateObject$`attributes`, "map(AnyType)", loadNamespace("tator"))
      self$`frame` <- StateUpdateObject$`frame`
      self$`modified` <- StateUpdateObject$`modified`
      self
    }
  )
)
