# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StateSpec
#' @description StateSpec Class
#' @format An \code{R6Class} generator object
#' @field frame  integer [optional]
#'
#' @field localization_ids  list( integer ) [optional]
#'
#' @field media_ids  list( integer ) 
#'
#' @field modified  character [optional]
#'
#' @field type  integer 
#'
#' @field version  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StateSpec <- R6::R6Class(
  'StateSpec',
  public = list(
    `frame` = NULL,
    `localization_ids` = NULL,
    `media_ids` = NULL,
    `modified` = NULL,
    `type` = NULL,
    `version` = NULL,
    initialize = function(`media_ids`, `type`, `frame`=NULL, `localization_ids`=NULL, `modified`=NULL, `version`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`media_ids`)) {
        stopifnot(is.vector(`media_ids`), length(`media_ids`) != 0)
        sapply(`media_ids`, function(x) stopifnot(is.character(x)))
        self$`media_ids` <- `media_ids`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!is.null(`frame`)) {
        stopifnot(is.numeric(`frame`), length(`frame`) == 1)
        self$`frame` <- `frame`
      }
      if (!is.null(`localization_ids`)) {
        stopifnot(is.vector(`localization_ids`), length(`localization_ids`) != 0)
        sapply(`localization_ids`, function(x) stopifnot(is.character(x)))
        self$`localization_ids` <- `localization_ids`
      }
      if (!is.null(`modified`)) {
        self$`modified` <- `modified`
      }
      if (!is.null(`version`)) {
        stopifnot(is.numeric(`version`), length(`version`) == 1)
        self$`version` <- `version`
      }
    },
    toJSON = function() {
      StateSpecObject <- list()
      if (!is.null(self$`frame`)) {
        StateSpecObject[['frame']] <-
          self$`frame`
      }
      if (!is.null(self$`localization_ids`)) {
        StateSpecObject[['localization_ids']] <-
          self$`localization_ids`
      }
      if (!is.null(self$`media_ids`)) {
        StateSpecObject[['media_ids']] <-
          self$`media_ids`
      }
      if (!is.null(self$`modified`)) {
        StateSpecObject[['modified']] <-
          self$`modified`
      }
      if (!is.null(self$`type`)) {
        StateSpecObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`version`)) {
        StateSpecObject[['version']] <-
          self$`version`
      }

      StateSpecObject
    },
    fromJSON = function(StateSpecJson) {
      StateSpecObject <- jsonlite::fromJSON(StateSpecJson)
      if (!is.null(StateSpecObject$`frame`)) {
        self$`frame` <- StateSpecObject$`frame`
      }
      if (!is.null(StateSpecObject$`localization_ids`)) {
        self$`localization_ids` <- ApiClient$new()$deserializeObj(StateSpecObject$`localization_ids`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(StateSpecObject$`media_ids`)) {
        self$`media_ids` <- ApiClient$new()$deserializeObj(StateSpecObject$`media_ids`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(StateSpecObject$`modified`)) {
        self$`modified` <- StateSpecObject$`modified`
      }
      if (!is.null(StateSpecObject$`type`)) {
        self$`type` <- StateSpecObject$`type`
      }
      if (!is.null(StateSpecObject$`version`)) {
        self$`version` <- StateSpecObject$`version`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`frame`)) {
        sprintf(
        '"frame":
          %d
                ',
        self$`frame`
        )},
        if (!is.null(self$`localization_ids`)) {
        sprintf(
        '"localization_ids":
           [%s]
        ',
        paste(unlist(lapply(self$`localization_ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`media_ids`)) {
        sprintf(
        '"media_ids":
           [%s]
        ',
        paste(unlist(lapply(self$`media_ids`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`modified`)) {
        sprintf(
        '"modified":
          "%s"
                ',
        self$`modified`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )},
        if (!is.null(self$`version`)) {
        sprintf(
        '"version":
          %d
                ',
        self$`version`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StateSpecJson) {
      StateSpecObject <- jsonlite::fromJSON(StateSpecJson)
      self$`frame` <- StateSpecObject$`frame`
      self$`localization_ids` <- ApiClient$new()$deserializeObj(StateSpecObject$`localization_ids`, "array[integer]", loadNamespace("tator"))
      self$`media_ids` <- ApiClient$new()$deserializeObj(StateSpecObject$`media_ids`, "array[integer]", loadNamespace("tator"))
      self$`modified` <- StateSpecObject$`modified`
      self$`type` <- StateSpecObject$`type`
      self$`version` <- StateSpecObject$`version`
      self
    }
  )
)
