# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title StateType
#' @description StateType Class
#' @format An \code{R6Class} generator object
#' @field association  character [optional]
#'
#' @field attribute_types  list( \link{AttributeType} ) [optional]
#'
#' @field description  character [optional]
#'
#' @field dtype  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field interpolation  character [optional]
#'
#' @field media  list( integer ) [optional]
#'
#' @field name  character [optional]
#'
#' @field project  integer [optional]
#'
#' @field visible  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
StateType <- R6::R6Class(
  'StateType',
  public = list(
    `association` = NULL,
    `attribute_types` = NULL,
    `description` = NULL,
    `dtype` = NULL,
    `id` = NULL,
    `interpolation` = NULL,
    `media` = NULL,
    `name` = NULL,
    `project` = NULL,
    `visible` = NULL,
    initialize = function(`association`=NULL, `attribute_types`=NULL, `description`=NULL, `dtype`=NULL, `id`=NULL, `interpolation`='latest', `media`=NULL, `name`=NULL, `project`=NULL, `visible`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`association`)) {
        stopifnot(is.character(`association`), length(`association`) == 1)
        self$`association` <- `association`
      }
      if (!is.null(`attribute_types`)) {
        stopifnot(is.vector(`attribute_types`), length(`attribute_types`) != 0)
        sapply(`attribute_types`, function(x) stopifnot(R6::is.R6(x)))
        self$`attribute_types` <- `attribute_types`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`dtype`)) {
        stopifnot(is.character(`dtype`), length(`dtype`) == 1)
        self$`dtype` <- `dtype`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`interpolation`)) {
        stopifnot(is.character(`interpolation`), length(`interpolation`) == 1)
        self$`interpolation` <- `interpolation`
      }
      if (!is.null(`media`)) {
        stopifnot(is.vector(`media`), length(`media`) != 0)
        sapply(`media`, function(x) stopifnot(is.character(x)))
        self$`media` <- `media`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`visible`)) {
        self$`visible` <- `visible`
      }
    },
    toJSON = function() {
      StateTypeObject <- list()
      if (!is.null(self$`association`)) {
        StateTypeObject[['association']] <-
          self$`association`
      }
      if (!is.null(self$`attribute_types`)) {
        StateTypeObject[['attribute_types']] <-
          lapply(self$`attribute_types`, function(x) x$toJSON())
      }
      if (!is.null(self$`description`)) {
        StateTypeObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`dtype`)) {
        StateTypeObject[['dtype']] <-
          self$`dtype`
      }
      if (!is.null(self$`id`)) {
        StateTypeObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`interpolation`)) {
        StateTypeObject[['interpolation']] <-
          self$`interpolation`
      }
      if (!is.null(self$`media`)) {
        StateTypeObject[['media']] <-
          self$`media`
      }
      if (!is.null(self$`name`)) {
        StateTypeObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`project`)) {
        StateTypeObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`visible`)) {
        StateTypeObject[['visible']] <-
          self$`visible`
      }

      StateTypeObject
    },
    fromJSON = function(StateTypeJson) {
      StateTypeObject <- jsonlite::fromJSON(StateTypeJson)
      if (!is.null(StateTypeObject$`association`)) {
        self$`association` <- StateTypeObject$`association`
      }
      if (!is.null(StateTypeObject$`attribute_types`)) {
        self$`attribute_types` <- ApiClient$new()$deserializeObj(StateTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      }
      if (!is.null(StateTypeObject$`description`)) {
        self$`description` <- StateTypeObject$`description`
      }
      if (!is.null(StateTypeObject$`dtype`)) {
        self$`dtype` <- StateTypeObject$`dtype`
      }
      if (!is.null(StateTypeObject$`id`)) {
        self$`id` <- StateTypeObject$`id`
      }
      if (!is.null(StateTypeObject$`interpolation`)) {
        self$`interpolation` <- StateTypeObject$`interpolation`
      }
      if (!is.null(StateTypeObject$`media`)) {
        self$`media` <- ApiClient$new()$deserializeObj(StateTypeObject$`media`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(StateTypeObject$`name`)) {
        self$`name` <- StateTypeObject$`name`
      }
      if (!is.null(StateTypeObject$`project`)) {
        self$`project` <- StateTypeObject$`project`
      }
      if (!is.null(StateTypeObject$`visible`)) {
        self$`visible` <- StateTypeObject$`visible`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`association`)) {
        sprintf(
        '"association":
          "%s"
                ',
        self$`association`
        )},
        if (!is.null(self$`attribute_types`)) {
        sprintf(
        '"attribute_types":
        [%s]
',
        paste(sapply(self$`attribute_types`, function(x) jsonlite::toJSON(x$toJSON(), auto_unbox=TRUE, digits = NA)), collapse=",")
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`dtype`)) {
        sprintf(
        '"dtype":
          "%s"
                ',
        self$`dtype`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`interpolation`)) {
        sprintf(
        '"interpolation":
          "%s"
                ',
        self$`interpolation`
        )},
        if (!is.null(self$`media`)) {
        sprintf(
        '"media":
           [%s]
        ',
        paste(unlist(lapply(self$`media`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )},
        if (!is.null(self$`visible`)) {
        sprintf(
        '"visible":
          "%s"
                ',
        self$`visible`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(StateTypeJson) {
      StateTypeObject <- jsonlite::fromJSON(StateTypeJson)
      self$`association` <- StateTypeObject$`association`
      self$`attribute_types` <- ApiClient$new()$deserializeObj(StateTypeObject$`attribute_types`, "array[AttributeType]", loadNamespace("tator"))
      self$`description` <- StateTypeObject$`description`
      self$`dtype` <- StateTypeObject$`dtype`
      self$`id` <- StateTypeObject$`id`
      self$`interpolation` <- StateTypeObject$`interpolation`
      self$`media` <- ApiClient$new()$deserializeObj(StateTypeObject$`media`, "array[integer]", loadNamespace("tator"))
      self$`name` <- StateTypeObject$`name`
      self$`project` <- StateTypeObject$`project`
      self$`visible` <- StateTypeObject$`visible`
      self
    }
  )
)
