# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TemporaryFile
#' @description TemporaryFile Class
#' @format An \code{R6Class} generator object
#' @field created_datetime  character [optional]
#'
#' @field eol_datetime  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field lookup  character [optional]
#'
#' @field name  character [optional]
#'
#' @field path  character [optional]
#'
#' @field project  integer [optional]
#'
#' @field user  integer [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TemporaryFile <- R6::R6Class(
  'TemporaryFile',
  public = list(
    `created_datetime` = NULL,
    `eol_datetime` = NULL,
    `id` = NULL,
    `lookup` = NULL,
    `name` = NULL,
    `path` = NULL,
    `project` = NULL,
    `user` = NULL,
    initialize = function(`created_datetime`=NULL, `eol_datetime`=NULL, `id`=NULL, `lookup`=NULL, `name`=NULL, `path`=NULL, `project`=NULL, `user`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`created_datetime`)) {
        stopifnot(is.character(`created_datetime`), length(`created_datetime`) == 1)
        self$`created_datetime` <- `created_datetime`
      }
      if (!is.null(`eol_datetime`)) {
        stopifnot(is.character(`eol_datetime`), length(`eol_datetime`) == 1)
        self$`eol_datetime` <- `eol_datetime`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`lookup`)) {
        stopifnot(is.character(`lookup`), length(`lookup`) == 1)
        self$`lookup` <- `lookup`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`user`)) {
        stopifnot(is.numeric(`user`), length(`user`) == 1)
        self$`user` <- `user`
      }
    },
    toJSON = function() {
      TemporaryFileObject <- list()
      if (!is.null(self$`created_datetime`)) {
        TemporaryFileObject[['created_datetime']] <-
          self$`created_datetime`
      }
      if (!is.null(self$`eol_datetime`)) {
        TemporaryFileObject[['eol_datetime']] <-
          self$`eol_datetime`
      }
      if (!is.null(self$`id`)) {
        TemporaryFileObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`lookup`)) {
        TemporaryFileObject[['lookup']] <-
          self$`lookup`
      }
      if (!is.null(self$`name`)) {
        TemporaryFileObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`path`)) {
        TemporaryFileObject[['path']] <-
          self$`path`
      }
      if (!is.null(self$`project`)) {
        TemporaryFileObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`user`)) {
        TemporaryFileObject[['user']] <-
          self$`user`
      }

      TemporaryFileObject
    },
    fromJSON = function(TemporaryFileJson) {
      TemporaryFileObject <- jsonlite::fromJSON(TemporaryFileJson)
      if (!is.null(TemporaryFileObject$`created_datetime`)) {
        self$`created_datetime` <- TemporaryFileObject$`created_datetime`
      }
      if (!is.null(TemporaryFileObject$`eol_datetime`)) {
        self$`eol_datetime` <- TemporaryFileObject$`eol_datetime`
      }
      if (!is.null(TemporaryFileObject$`id`)) {
        self$`id` <- TemporaryFileObject$`id`
      }
      if (!is.null(TemporaryFileObject$`lookup`)) {
        self$`lookup` <- TemporaryFileObject$`lookup`
      }
      if (!is.null(TemporaryFileObject$`name`)) {
        self$`name` <- TemporaryFileObject$`name`
      }
      if (!is.null(TemporaryFileObject$`path`)) {
        self$`path` <- TemporaryFileObject$`path`
      }
      if (!is.null(TemporaryFileObject$`project`)) {
        self$`project` <- TemporaryFileObject$`project`
      }
      if (!is.null(TemporaryFileObject$`user`)) {
        self$`user` <- TemporaryFileObject$`user`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`created_datetime`)) {
        sprintf(
        '"created_datetime":
          "%s"
                ',
        self$`created_datetime`
        )},
        if (!is.null(self$`eol_datetime`)) {
        sprintf(
        '"eol_datetime":
          "%s"
                ',
        self$`eol_datetime`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`lookup`)) {
        sprintf(
        '"lookup":
          "%s"
                ',
        self$`lookup`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )},
        if (!is.null(self$`user`)) {
        sprintf(
        '"user":
          %d
                ',
        self$`user`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TemporaryFileJson) {
      TemporaryFileObject <- jsonlite::fromJSON(TemporaryFileJson)
      self$`created_datetime` <- TemporaryFileObject$`created_datetime`
      self$`eol_datetime` <- TemporaryFileObject$`eol_datetime`
      self$`id` <- TemporaryFileObject$`id`
      self$`lookup` <- TemporaryFileObject$`lookup`
      self$`name` <- TemporaryFileObject$`name`
      self$`path` <- TemporaryFileObject$`path`
      self$`project` <- TemporaryFileObject$`project`
      self$`user` <- TemporaryFileObject$`user`
      self
    }
  )
)
