# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TemporaryFileSpec
#' @description TemporaryFileSpec Class
#' @format An \code{R6Class} generator object
#' @field hours  integer [optional]
#'
#' @field lookup  character 
#'
#' @field name  character 
#'
#' @field url  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TemporaryFileSpec <- R6::R6Class(
  'TemporaryFileSpec',
  public = list(
    `hours` = NULL,
    `lookup` = NULL,
    `name` = NULL,
    `url` = NULL,
    initialize = function(`lookup`, `name`, `url`, `hours`=24, ...){
      local.optional.var <- list(...)
      if (!missing(`lookup`)) {
        stopifnot(is.character(`lookup`), length(`lookup`) == 1)
        self$`lookup` <- `lookup`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
      if (!is.null(`hours`)) {
        stopifnot(is.numeric(`hours`), length(`hours`) == 1)
        self$`hours` <- `hours`
      }
    },
    toJSON = function() {
      TemporaryFileSpecObject <- list()
      if (!is.null(self$`hours`)) {
        TemporaryFileSpecObject[['hours']] <-
          self$`hours`
      }
      if (!is.null(self$`lookup`)) {
        TemporaryFileSpecObject[['lookup']] <-
          self$`lookup`
      }
      if (!is.null(self$`name`)) {
        TemporaryFileSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`url`)) {
        TemporaryFileSpecObject[['url']] <-
          self$`url`
      }

      TemporaryFileSpecObject
    },
    fromJSON = function(TemporaryFileSpecJson) {
      TemporaryFileSpecObject <- jsonlite::fromJSON(TemporaryFileSpecJson)
      if (!is.null(TemporaryFileSpecObject$`hours`)) {
        self$`hours` <- TemporaryFileSpecObject$`hours`
      }
      if (!is.null(TemporaryFileSpecObject$`lookup`)) {
        self$`lookup` <- TemporaryFileSpecObject$`lookup`
      }
      if (!is.null(TemporaryFileSpecObject$`name`)) {
        self$`name` <- TemporaryFileSpecObject$`name`
      }
      if (!is.null(TemporaryFileSpecObject$`url`)) {
        self$`url` <- TemporaryFileSpecObject$`url`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`hours`)) {
        sprintf(
        '"hours":
          %d
                ',
        self$`hours`
        )},
        if (!is.null(self$`lookup`)) {
        sprintf(
        '"lookup":
          "%s"
                ',
        self$`lookup`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TemporaryFileSpecJson) {
      TemporaryFileSpecObject <- jsonlite::fromJSON(TemporaryFileSpecJson)
      self$`hours` <- TemporaryFileSpecObject$`hours`
      self$`lookup` <- TemporaryFileSpecObject$`lookup`
      self$`name` <- TemporaryFileSpecObject$`name`
      self$`url` <- TemporaryFileSpecObject$`url`
      self
    }
  )
)
