# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Token
#' @description Token Class
#' @format An \code{R6Class} generator object
#' @field token  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Token <- R6::R6Class(
  'Token',
  public = list(
    `token` = NULL,
    initialize = function(`token`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`token`)) {
        stopifnot(is.character(`token`), length(`token`) == 1)
        self$`token` <- `token`
      }
    },
    toJSON = function() {
      TokenObject <- list()
      if (!is.null(self$`token`)) {
        TokenObject[['token']] <-
          self$`token`
      }

      TokenObject
    },
    fromJSON = function(TokenJson) {
      TokenObject <- jsonlite::fromJSON(TokenJson)
      if (!is.null(TokenObject$`token`)) {
        self$`token` <- TokenObject$`token`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`token`)) {
        sprintf(
        '"token":
          "%s"
                ',
        self$`token`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TokenJson) {
      TokenObject <- jsonlite::fromJSON(TokenJson)
      self$`token` <- TokenObject$`token`
      self
    }
  )
)
