# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title TranscodeSpec
#' @description TranscodeSpec Class
#' @format An \code{R6Class} generator object
#' @field gid  character 
#'
#' @field md5  character 
#'
#' @field name  character 
#'
#' @field section  character 
#'
#' @field type  integer 
#'
#' @field uid  character 
#'
#' @field url  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
TranscodeSpec <- R6::R6Class(
  'TranscodeSpec',
  public = list(
    `gid` = NULL,
    `md5` = NULL,
    `name` = NULL,
    `section` = NULL,
    `type` = NULL,
    `uid` = NULL,
    `url` = NULL,
    initialize = function(`gid`, `md5`, `name`, `section`, `type`, `uid`, `url`, ...){
      local.optional.var <- list(...)
      if (!missing(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!missing(`md5`)) {
        stopifnot(is.character(`md5`), length(`md5`) == 1)
        self$`md5` <- `md5`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`section`)) {
        stopifnot(is.character(`section`), length(`section`) == 1)
        self$`section` <- `section`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`uid`)) {
        stopifnot(is.character(`uid`), length(`uid`) == 1)
        self$`uid` <- `uid`
      }
      if (!missing(`url`)) {
        stopifnot(is.character(`url`), length(`url`) == 1)
        self$`url` <- `url`
      }
    },
    toJSON = function() {
      TranscodeSpecObject <- list()
      if (!is.null(self$`gid`)) {
        TranscodeSpecObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`md5`)) {
        TranscodeSpecObject[['md5']] <-
          self$`md5`
      }
      if (!is.null(self$`name`)) {
        TranscodeSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`section`)) {
        TranscodeSpecObject[['section']] <-
          self$`section`
      }
      if (!is.null(self$`type`)) {
        TranscodeSpecObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`uid`)) {
        TranscodeSpecObject[['uid']] <-
          self$`uid`
      }
      if (!is.null(self$`url`)) {
        TranscodeSpecObject[['url']] <-
          self$`url`
      }

      TranscodeSpecObject
    },
    fromJSON = function(TranscodeSpecJson) {
      TranscodeSpecObject <- jsonlite::fromJSON(TranscodeSpecJson)
      if (!is.null(TranscodeSpecObject$`gid`)) {
        self$`gid` <- TranscodeSpecObject$`gid`
      }
      if (!is.null(TranscodeSpecObject$`md5`)) {
        self$`md5` <- TranscodeSpecObject$`md5`
      }
      if (!is.null(TranscodeSpecObject$`name`)) {
        self$`name` <- TranscodeSpecObject$`name`
      }
      if (!is.null(TranscodeSpecObject$`section`)) {
        self$`section` <- TranscodeSpecObject$`section`
      }
      if (!is.null(TranscodeSpecObject$`type`)) {
        self$`type` <- TranscodeSpecObject$`type`
      }
      if (!is.null(TranscodeSpecObject$`uid`)) {
        self$`uid` <- TranscodeSpecObject$`uid`
      }
      if (!is.null(TranscodeSpecObject$`url`)) {
        self$`url` <- TranscodeSpecObject$`url`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`md5`)) {
        sprintf(
        '"md5":
          "%s"
                ',
        self$`md5`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`section`)) {
        sprintf(
        '"section":
          "%s"
                ',
        self$`section`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )},
        if (!is.null(self$`uid`)) {
        sprintf(
        '"uid":
          "%s"
                ',
        self$`uid`
        )},
        if (!is.null(self$`url`)) {
        sprintf(
        '"url":
          "%s"
                ',
        self$`url`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TranscodeSpecJson) {
      TranscodeSpecObject <- jsonlite::fromJSON(TranscodeSpecJson)
      self$`gid` <- TranscodeSpecObject$`gid`
      self$`md5` <- TranscodeSpecObject$`md5`
      self$`name` <- TranscodeSpecObject$`name`
      self$`section` <- TranscodeSpecObject$`section`
      self$`type` <- TranscodeSpecObject$`type`
      self$`uid` <- TranscodeSpecObject$`uid`
      self$`url` <- TranscodeSpecObject$`url`
      self
    }
  )
)
