# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Transcode
#' @description Transcode Class
#' @format An \code{R6Class} generator object
#' @field group_id  character [optional]
#'
#' @field message  character [optional]
#'
#' @field run_uid  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Transcode <- R6::R6Class(
  'Transcode',
  public = list(
    `group_id` = NULL,
    `message` = NULL,
    `run_uid` = NULL,
    initialize = function(`group_id`=NULL, `message`=NULL, `run_uid`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`group_id`)) {
        stopifnot(is.character(`group_id`), length(`group_id`) == 1)
        self$`group_id` <- `group_id`
      }
      if (!is.null(`message`)) {
        stopifnot(is.character(`message`), length(`message`) == 1)
        self$`message` <- `message`
      }
      if (!is.null(`run_uid`)) {
        stopifnot(is.character(`run_uid`), length(`run_uid`) == 1)
        self$`run_uid` <- `run_uid`
      }
    },
    toJSON = function() {
      TranscodeObject <- list()
      if (!is.null(self$`group_id`)) {
        TranscodeObject[['group_id']] <-
          self$`group_id`
      }
      if (!is.null(self$`message`)) {
        TranscodeObject[['message']] <-
          self$`message`
      }
      if (!is.null(self$`run_uid`)) {
        TranscodeObject[['run_uid']] <-
          self$`run_uid`
      }

      TranscodeObject
    },
    fromJSON = function(TranscodeJson) {
      TranscodeObject <- jsonlite::fromJSON(TranscodeJson)
      if (!is.null(TranscodeObject$`group_id`)) {
        self$`group_id` <- TranscodeObject$`group_id`
      }
      if (!is.null(TranscodeObject$`message`)) {
        self$`message` <- TranscodeObject$`message`
      }
      if (!is.null(TranscodeObject$`run_uid`)) {
        self$`run_uid` <- TranscodeObject$`run_uid`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`group_id`)) {
        sprintf(
        '"group_id":
          "%s"
                ',
        self$`group_id`
        )},
        if (!is.null(self$`message`)) {
        sprintf(
        '"message":
          "%s"
                ',
        self$`message`
        )},
        if (!is.null(self$`run_uid`)) {
        sprintf(
        '"run_uid":
          "%s"
                ',
        self$`run_uid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(TranscodeJson) {
      TranscodeObject <- jsonlite::fromJSON(TranscodeJson)
      self$`group_id` <- TranscodeObject$`group_id`
      self$`message` <- TranscodeObject$`message`
      self$`run_uid` <- TranscodeObject$`run_uid`
      self
    }
  )
)
