# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title UserUpdate
#' @description UserUpdate Class
#' @format An \code{R6Class} generator object
#' @field email  character [optional]
#'
#' @field first_name  character [optional]
#'
#' @field last_name  character [optional]
#'
#' @field username  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
UserUpdate <- R6::R6Class(
  'UserUpdate',
  public = list(
    `email` = NULL,
    `first_name` = NULL,
    `last_name` = NULL,
    `username` = NULL,
    initialize = function(`email`=NULL, `first_name`=NULL, `last_name`=NULL, `username`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!is.null(`first_name`)) {
        stopifnot(is.character(`first_name`), length(`first_name`) == 1)
        self$`first_name` <- `first_name`
      }
      if (!is.null(`last_name`)) {
        stopifnot(is.character(`last_name`), length(`last_name`) == 1)
        self$`last_name` <- `last_name`
      }
      if (!is.null(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
    },
    toJSON = function() {
      UserUpdateObject <- list()
      if (!is.null(self$`email`)) {
        UserUpdateObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`first_name`)) {
        UserUpdateObject[['first_name']] <-
          self$`first_name`
      }
      if (!is.null(self$`last_name`)) {
        UserUpdateObject[['last_name']] <-
          self$`last_name`
      }
      if (!is.null(self$`username`)) {
        UserUpdateObject[['username']] <-
          self$`username`
      }

      UserUpdateObject
    },
    fromJSON = function(UserUpdateJson) {
      UserUpdateObject <- jsonlite::fromJSON(UserUpdateJson)
      if (!is.null(UserUpdateObject$`email`)) {
        self$`email` <- UserUpdateObject$`email`
      }
      if (!is.null(UserUpdateObject$`first_name`)) {
        self$`first_name` <- UserUpdateObject$`first_name`
      }
      if (!is.null(UserUpdateObject$`last_name`)) {
        self$`last_name` <- UserUpdateObject$`last_name`
      }
      if (!is.null(UserUpdateObject$`username`)) {
        self$`username` <- UserUpdateObject$`username`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`first_name`)) {
        sprintf(
        '"first_name":
          "%s"
                ',
        self$`first_name`
        )},
        if (!is.null(self$`last_name`)) {
        sprintf(
        '"last_name":
          "%s"
                ',
        self$`last_name`
        )},
        if (!is.null(self$`username`)) {
        sprintf(
        '"username":
          "%s"
                ',
        self$`username`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UserUpdateJson) {
      UserUpdateObject <- jsonlite::fromJSON(UserUpdateJson)
      self$`email` <- UserUpdateObject$`email`
      self$`first_name` <- UserUpdateObject$`first_name`
      self$`last_name` <- UserUpdateObject$`last_name`
      self$`username` <- UserUpdateObject$`username`
      self
    }
  )
)
