# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title User
#' @description User Class
#' @format An \code{R6Class} generator object
#' @field email  character [optional]
#'
#' @field first_name  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field last_name  character [optional]
#'
#' @field username  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
User <- R6::R6Class(
  'User',
  public = list(
    `email` = NULL,
    `first_name` = NULL,
    `id` = NULL,
    `last_name` = NULL,
    `username` = NULL,
    initialize = function(`email`=NULL, `first_name`=NULL, `id`=NULL, `last_name`=NULL, `username`=NULL, ...){
      local.optional.var <- list(...)
      if (!is.null(`email`)) {
        stopifnot(is.character(`email`), length(`email`) == 1)
        self$`email` <- `email`
      }
      if (!is.null(`first_name`)) {
        stopifnot(is.character(`first_name`), length(`first_name`) == 1)
        self$`first_name` <- `first_name`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`last_name`)) {
        stopifnot(is.character(`last_name`), length(`last_name`) == 1)
        self$`last_name` <- `last_name`
      }
      if (!is.null(`username`)) {
        stopifnot(is.character(`username`), length(`username`) == 1)
        self$`username` <- `username`
      }
    },
    toJSON = function() {
      UserObject <- list()
      if (!is.null(self$`email`)) {
        UserObject[['email']] <-
          self$`email`
      }
      if (!is.null(self$`first_name`)) {
        UserObject[['first_name']] <-
          self$`first_name`
      }
      if (!is.null(self$`id`)) {
        UserObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`last_name`)) {
        UserObject[['last_name']] <-
          self$`last_name`
      }
      if (!is.null(self$`username`)) {
        UserObject[['username']] <-
          self$`username`
      }

      UserObject
    },
    fromJSON = function(UserJson) {
      UserObject <- jsonlite::fromJSON(UserJson)
      if (!is.null(UserObject$`email`)) {
        self$`email` <- UserObject$`email`
      }
      if (!is.null(UserObject$`first_name`)) {
        self$`first_name` <- UserObject$`first_name`
      }
      if (!is.null(UserObject$`id`)) {
        self$`id` <- UserObject$`id`
      }
      if (!is.null(UserObject$`last_name`)) {
        self$`last_name` <- UserObject$`last_name`
      }
      if (!is.null(UserObject$`username`)) {
        self$`username` <- UserObject$`username`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`email`)) {
        sprintf(
        '"email":
          "%s"
                ',
        self$`email`
        )},
        if (!is.null(self$`first_name`)) {
        sprintf(
        '"first_name":
          "%s"
                ',
        self$`first_name`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`last_name`)) {
        sprintf(
        '"last_name":
          "%s"
                ',
        self$`last_name`
        )},
        if (!is.null(self$`username`)) {
        sprintf(
        '"username":
          "%s"
                ',
        self$`username`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(UserJson) {
      UserObject <- jsonlite::fromJSON(UserJson)
      self$`email` <- UserObject$`email`
      self$`first_name` <- UserObject$`first_name`
      self$`id` <- UserObject$`id`
      self$`last_name` <- UserObject$`last_name`
      self$`username` <- UserObject$`username`
      self
    }
  )
)
