# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersionUpdate
#' @description VersionUpdate Class
#' @format An \code{R6Class} generator object
#' @field bases  list( integer ) [optional]
#'
#' @field description  character [optional]
#'
#' @field name  character [optional]
#'
#' @field show_empty  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersionUpdate <- R6::R6Class(
  'VersionUpdate',
  public = list(
    `bases` = NULL,
    `description` = NULL,
    `name` = NULL,
    `show_empty` = NULL,
    initialize = function(`bases`=NULL, `description`='', `name`=NULL, `show_empty`=TRUE, ...){
      local.optional.var <- list(...)
      if (!is.null(`bases`)) {
        stopifnot(is.vector(`bases`), length(`bases`) != 0)
        sapply(`bases`, function(x) stopifnot(is.character(x)))
        self$`bases` <- `bases`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`show_empty`)) {
        self$`show_empty` <- `show_empty`
      }
    },
    toJSON = function() {
      VersionUpdateObject <- list()
      if (!is.null(self$`bases`)) {
        VersionUpdateObject[['bases']] <-
          self$`bases`
      }
      if (!is.null(self$`description`)) {
        VersionUpdateObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`name`)) {
        VersionUpdateObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`show_empty`)) {
        VersionUpdateObject[['show_empty']] <-
          self$`show_empty`
      }

      VersionUpdateObject
    },
    fromJSON = function(VersionUpdateJson) {
      VersionUpdateObject <- jsonlite::fromJSON(VersionUpdateJson)
      if (!is.null(VersionUpdateObject$`bases`)) {
        self$`bases` <- ApiClient$new()$deserializeObj(VersionUpdateObject$`bases`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(VersionUpdateObject$`description`)) {
        self$`description` <- VersionUpdateObject$`description`
      }
      if (!is.null(VersionUpdateObject$`name`)) {
        self$`name` <- VersionUpdateObject$`name`
      }
      if (!is.null(VersionUpdateObject$`show_empty`)) {
        self$`show_empty` <- VersionUpdateObject$`show_empty`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bases`)) {
        sprintf(
        '"bases":
           [%s]
        ',
        paste(unlist(lapply(self$`bases`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`show_empty`)) {
        sprintf(
        '"show_empty":
          "%s"
                ',
        self$`show_empty`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersionUpdateJson) {
      VersionUpdateObject <- jsonlite::fromJSON(VersionUpdateJson)
      self$`bases` <- ApiClient$new()$deserializeObj(VersionUpdateObject$`bases`, "array[integer]", loadNamespace("tator"))
      self$`description` <- VersionUpdateObject$`description`
      self$`name` <- VersionUpdateObject$`name`
      self$`show_empty` <- VersionUpdateObject$`show_empty`
      self
    }
  )
)
