# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title Version
#' @description Version Class
#' @format An \code{R6Class} generator object
#' @field bases  list( integer ) [optional]
#'
#' @field created_by  character [optional]
#'
#' @field created_datetime  character [optional]
#'
#' @field description  character [optional]
#'
#' @field id  integer [optional]
#'
#' @field modified_by  character [optional]
#'
#' @field modified_datetime  character [optional]
#'
#' @field name  character [optional]
#'
#' @field num_created  integer [optional]
#'
#' @field num_modified  integer [optional]
#'
#' @field number  integer [optional]
#'
#' @field project  integer [optional]
#'
#' @field show_empty  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
Version <- R6::R6Class(
  'Version',
  public = list(
    `bases` = NULL,
    `created_by` = NULL,
    `created_datetime` = NULL,
    `description` = NULL,
    `id` = NULL,
    `modified_by` = NULL,
    `modified_datetime` = NULL,
    `name` = NULL,
    `num_created` = NULL,
    `num_modified` = NULL,
    `number` = NULL,
    `project` = NULL,
    `show_empty` = NULL,
    initialize = function(`bases`=NULL, `created_by`=NULL, `created_datetime`=NULL, `description`='', `id`=NULL, `modified_by`=NULL, `modified_datetime`=NULL, `name`=NULL, `num_created`=NULL, `num_modified`=NULL, `number`=NULL, `project`=NULL, `show_empty`=TRUE, ...){
      local.optional.var <- list(...)
      if (!is.null(`bases`)) {
        stopifnot(is.vector(`bases`), length(`bases`) != 0)
        sapply(`bases`, function(x) stopifnot(is.character(x)))
        self$`bases` <- `bases`
      }
      if (!is.null(`created_by`)) {
        stopifnot(is.character(`created_by`), length(`created_by`) == 1)
        self$`created_by` <- `created_by`
      }
      if (!is.null(`created_datetime`)) {
        stopifnot(is.character(`created_datetime`), length(`created_datetime`) == 1)
        self$`created_datetime` <- `created_datetime`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!is.null(`modified_by`)) {
        stopifnot(is.character(`modified_by`), length(`modified_by`) == 1)
        self$`modified_by` <- `modified_by`
      }
      if (!is.null(`modified_datetime`)) {
        stopifnot(is.character(`modified_datetime`), length(`modified_datetime`) == 1)
        self$`modified_datetime` <- `modified_datetime`
      }
      if (!is.null(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`num_created`)) {
        stopifnot(is.numeric(`num_created`), length(`num_created`) == 1)
        self$`num_created` <- `num_created`
      }
      if (!is.null(`num_modified`)) {
        stopifnot(is.numeric(`num_modified`), length(`num_modified`) == 1)
        self$`num_modified` <- `num_modified`
      }
      if (!is.null(`number`)) {
        stopifnot(is.numeric(`number`), length(`number`) == 1)
        self$`number` <- `number`
      }
      if (!is.null(`project`)) {
        stopifnot(is.numeric(`project`), length(`project`) == 1)
        self$`project` <- `project`
      }
      if (!is.null(`show_empty`)) {
        self$`show_empty` <- `show_empty`
      }
    },
    toJSON = function() {
      VersionObject <- list()
      if (!is.null(self$`bases`)) {
        VersionObject[['bases']] <-
          self$`bases`
      }
      if (!is.null(self$`created_by`)) {
        VersionObject[['created_by']] <-
          self$`created_by`
      }
      if (!is.null(self$`created_datetime`)) {
        VersionObject[['created_datetime']] <-
          self$`created_datetime`
      }
      if (!is.null(self$`description`)) {
        VersionObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`id`)) {
        VersionObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`modified_by`)) {
        VersionObject[['modified_by']] <-
          self$`modified_by`
      }
      if (!is.null(self$`modified_datetime`)) {
        VersionObject[['modified_datetime']] <-
          self$`modified_datetime`
      }
      if (!is.null(self$`name`)) {
        VersionObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`num_created`)) {
        VersionObject[['num_created']] <-
          self$`num_created`
      }
      if (!is.null(self$`num_modified`)) {
        VersionObject[['num_modified']] <-
          self$`num_modified`
      }
      if (!is.null(self$`number`)) {
        VersionObject[['number']] <-
          self$`number`
      }
      if (!is.null(self$`project`)) {
        VersionObject[['project']] <-
          self$`project`
      }
      if (!is.null(self$`show_empty`)) {
        VersionObject[['show_empty']] <-
          self$`show_empty`
      }

      VersionObject
    },
    fromJSON = function(VersionJson) {
      VersionObject <- jsonlite::fromJSON(VersionJson)
      if (!is.null(VersionObject$`bases`)) {
        self$`bases` <- ApiClient$new()$deserializeObj(VersionObject$`bases`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(VersionObject$`created_by`)) {
        self$`created_by` <- VersionObject$`created_by`
      }
      if (!is.null(VersionObject$`created_datetime`)) {
        self$`created_datetime` <- VersionObject$`created_datetime`
      }
      if (!is.null(VersionObject$`description`)) {
        self$`description` <- VersionObject$`description`
      }
      if (!is.null(VersionObject$`id`)) {
        self$`id` <- VersionObject$`id`
      }
      if (!is.null(VersionObject$`modified_by`)) {
        self$`modified_by` <- VersionObject$`modified_by`
      }
      if (!is.null(VersionObject$`modified_datetime`)) {
        self$`modified_datetime` <- VersionObject$`modified_datetime`
      }
      if (!is.null(VersionObject$`name`)) {
        self$`name` <- VersionObject$`name`
      }
      if (!is.null(VersionObject$`num_created`)) {
        self$`num_created` <- VersionObject$`num_created`
      }
      if (!is.null(VersionObject$`num_modified`)) {
        self$`num_modified` <- VersionObject$`num_modified`
      }
      if (!is.null(VersionObject$`number`)) {
        self$`number` <- VersionObject$`number`
      }
      if (!is.null(VersionObject$`project`)) {
        self$`project` <- VersionObject$`project`
      }
      if (!is.null(VersionObject$`show_empty`)) {
        self$`show_empty` <- VersionObject$`show_empty`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bases`)) {
        sprintf(
        '"bases":
           [%s]
        ',
        paste(unlist(lapply(self$`bases`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`created_by`)) {
        sprintf(
        '"created_by":
          "%s"
                ',
        self$`created_by`
        )},
        if (!is.null(self$`created_datetime`)) {
        sprintf(
        '"created_datetime":
          "%s"
                ',
        self$`created_datetime`
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`modified_by`)) {
        sprintf(
        '"modified_by":
          "%s"
                ',
        self$`modified_by`
        )},
        if (!is.null(self$`modified_datetime`)) {
        sprintf(
        '"modified_datetime":
          "%s"
                ',
        self$`modified_datetime`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`num_created`)) {
        sprintf(
        '"num_created":
          %d
                ',
        self$`num_created`
        )},
        if (!is.null(self$`num_modified`)) {
        sprintf(
        '"num_modified":
          %d
                ',
        self$`num_modified`
        )},
        if (!is.null(self$`number`)) {
        sprintf(
        '"number":
          %d
                ',
        self$`number`
        )},
        if (!is.null(self$`project`)) {
        sprintf(
        '"project":
          %d
                ',
        self$`project`
        )},
        if (!is.null(self$`show_empty`)) {
        sprintf(
        '"show_empty":
          "%s"
                ',
        self$`show_empty`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersionJson) {
      VersionObject <- jsonlite::fromJSON(VersionJson)
      self$`bases` <- ApiClient$new()$deserializeObj(VersionObject$`bases`, "array[integer]", loadNamespace("tator"))
      self$`created_by` <- VersionObject$`created_by`
      self$`created_datetime` <- VersionObject$`created_datetime`
      self$`description` <- VersionObject$`description`
      self$`id` <- VersionObject$`id`
      self$`modified_by` <- VersionObject$`modified_by`
      self$`modified_datetime` <- VersionObject$`modified_datetime`
      self$`name` <- VersionObject$`name`
      self$`num_created` <- VersionObject$`num_created`
      self$`num_modified` <- VersionObject$`num_modified`
      self$`number` <- VersionObject$`number`
      self$`project` <- VersionObject$`project`
      self$`show_empty` <- VersionObject$`show_empty`
      self
    }
  )
)
