# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VersionSpec
#' @description VersionSpec Class
#' @format An \code{R6Class} generator object
#' @field bases  list( integer ) [optional]
#'
#' @field description  character [optional]
#'
#' @field name  character 
#'
#' @field show_empty  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VersionSpec <- R6::R6Class(
  'VersionSpec',
  public = list(
    `bases` = NULL,
    `description` = NULL,
    `name` = NULL,
    `show_empty` = NULL,
    initialize = function(`name`, `bases`=NULL, `description`='', `show_empty`=TRUE, ...){
      local.optional.var <- list(...)
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!is.null(`bases`)) {
        stopifnot(is.vector(`bases`), length(`bases`) != 0)
        sapply(`bases`, function(x) stopifnot(is.character(x)))
        self$`bases` <- `bases`
      }
      if (!is.null(`description`)) {
        stopifnot(is.character(`description`), length(`description`) == 1)
        self$`description` <- `description`
      }
      if (!is.null(`show_empty`)) {
        self$`show_empty` <- `show_empty`
      }
    },
    toJSON = function() {
      VersionSpecObject <- list()
      if (!is.null(self$`bases`)) {
        VersionSpecObject[['bases']] <-
          self$`bases`
      }
      if (!is.null(self$`description`)) {
        VersionSpecObject[['description']] <-
          self$`description`
      }
      if (!is.null(self$`name`)) {
        VersionSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`show_empty`)) {
        VersionSpecObject[['show_empty']] <-
          self$`show_empty`
      }

      VersionSpecObject
    },
    fromJSON = function(VersionSpecJson) {
      VersionSpecObject <- jsonlite::fromJSON(VersionSpecJson)
      if (!is.null(VersionSpecObject$`bases`)) {
        self$`bases` <- ApiClient$new()$deserializeObj(VersionSpecObject$`bases`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(VersionSpecObject$`description`)) {
        self$`description` <- VersionSpecObject$`description`
      }
      if (!is.null(VersionSpecObject$`name`)) {
        self$`name` <- VersionSpecObject$`name`
      }
      if (!is.null(VersionSpecObject$`show_empty`)) {
        self$`show_empty` <- VersionSpecObject$`show_empty`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`bases`)) {
        sprintf(
        '"bases":
           [%s]
        ',
        paste(unlist(lapply(self$`bases`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`description`)) {
        sprintf(
        '"description":
          "%s"
                ',
        self$`description`
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`show_empty`)) {
        sprintf(
        '"show_empty":
          %s
                ',
        jsonlite::toJSON(self$`show_empty`, auto_unbox = TRUE)
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VersionSpecJson) {
      VersionSpecObject <- jsonlite::fromJSON(VersionSpecJson)
      self$`bases` <- ApiClient$new()$deserializeObj(VersionSpecObject$`bases`, "array[integer]", loadNamespace("tator"))
      self$`description` <- VersionSpecObject$`description`
      self$`name` <- VersionSpecObject$`name`
      self$`show_empty` <- VersionSpecObject$`show_empty`
      self
    }
  )
)
