# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VideoDefinition
#' @description VideoDefinition Class
#' @format An \code{R6Class} generator object
#' @field codec  character 
#'
#' @field codec_description  character [optional]
#'
#' @field codec_mime  character [optional]
#'
#' @field host  character [optional]
#'
#' @field http_auth  character [optional]
#'
#' @field path  character [optional]
#'
#' @field resolution  list( integer ) 
#'
#' @field segment_info  character [optional]
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VideoDefinition <- R6::R6Class(
  'VideoDefinition',
  public = list(
    `codec` = NULL,
    `codec_description` = NULL,
    `codec_mime` = NULL,
    `host` = NULL,
    `http_auth` = NULL,
    `path` = NULL,
    `resolution` = NULL,
    `segment_info` = NULL,
    initialize = function(`codec`, `resolution`, `codec_description`=NULL, `codec_mime`=NULL, `host`=NULL, `http_auth`=NULL, `path`=NULL, `segment_info`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`codec`)) {
        stopifnot(is.character(`codec`), length(`codec`) == 1)
        self$`codec` <- `codec`
      }
      if (!missing(`resolution`)) {
        stopifnot(is.vector(`resolution`), length(`resolution`) != 0)
        sapply(`resolution`, function(x) stopifnot(is.character(x)))
        self$`resolution` <- `resolution`
      }
      if (!is.null(`codec_description`)) {
        stopifnot(is.character(`codec_description`), length(`codec_description`) == 1)
        self$`codec_description` <- `codec_description`
      }
      if (!is.null(`codec_mime`)) {
        stopifnot(is.character(`codec_mime`), length(`codec_mime`) == 1)
        self$`codec_mime` <- `codec_mime`
      }
      if (!is.null(`host`)) {
        stopifnot(is.character(`host`), length(`host`) == 1)
        self$`host` <- `host`
      }
      if (!is.null(`http_auth`)) {
        stopifnot(is.character(`http_auth`), length(`http_auth`) == 1)
        self$`http_auth` <- `http_auth`
      }
      if (!is.null(`path`)) {
        stopifnot(is.character(`path`), length(`path`) == 1)
        self$`path` <- `path`
      }
      if (!is.null(`segment_info`)) {
        stopifnot(is.character(`segment_info`), length(`segment_info`) == 1)
        self$`segment_info` <- `segment_info`
      }
    },
    toJSON = function() {
      VideoDefinitionObject <- list()
      if (!is.null(self$`codec`)) {
        VideoDefinitionObject[['codec']] <-
          self$`codec`
      }
      if (!is.null(self$`codec_description`)) {
        VideoDefinitionObject[['codec_description']] <-
          self$`codec_description`
      }
      if (!is.null(self$`codec_mime`)) {
        VideoDefinitionObject[['codec_mime']] <-
          self$`codec_mime`
      }
      if (!is.null(self$`host`)) {
        VideoDefinitionObject[['host']] <-
          self$`host`
      }
      if (!is.null(self$`http_auth`)) {
        VideoDefinitionObject[['http_auth']] <-
          self$`http_auth`
      }
      if (!is.null(self$`path`)) {
        VideoDefinitionObject[['path']] <-
          self$`path`
      }
      if (!is.null(self$`resolution`)) {
        VideoDefinitionObject[['resolution']] <-
          self$`resolution`
      }
      if (!is.null(self$`segment_info`)) {
        VideoDefinitionObject[['segment_info']] <-
          self$`segment_info`
      }

      VideoDefinitionObject
    },
    fromJSON = function(VideoDefinitionJson) {
      VideoDefinitionObject <- jsonlite::fromJSON(VideoDefinitionJson)
      if (!is.null(VideoDefinitionObject$`codec`)) {
        self$`codec` <- VideoDefinitionObject$`codec`
      }
      if (!is.null(VideoDefinitionObject$`codec_description`)) {
        self$`codec_description` <- VideoDefinitionObject$`codec_description`
      }
      if (!is.null(VideoDefinitionObject$`codec_mime`)) {
        self$`codec_mime` <- VideoDefinitionObject$`codec_mime`
      }
      if (!is.null(VideoDefinitionObject$`host`)) {
        self$`host` <- VideoDefinitionObject$`host`
      }
      if (!is.null(VideoDefinitionObject$`http_auth`)) {
        self$`http_auth` <- VideoDefinitionObject$`http_auth`
      }
      if (!is.null(VideoDefinitionObject$`path`)) {
        self$`path` <- VideoDefinitionObject$`path`
      }
      if (!is.null(VideoDefinitionObject$`resolution`)) {
        self$`resolution` <- ApiClient$new()$deserializeObj(VideoDefinitionObject$`resolution`, "array[integer]", loadNamespace("tator"))
      }
      if (!is.null(VideoDefinitionObject$`segment_info`)) {
        self$`segment_info` <- VideoDefinitionObject$`segment_info`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`codec`)) {
        sprintf(
        '"codec":
          "%s"
                ',
        self$`codec`
        )},
        if (!is.null(self$`codec_description`)) {
        sprintf(
        '"codec_description":
          "%s"
                ',
        self$`codec_description`
        )},
        if (!is.null(self$`codec_mime`)) {
        sprintf(
        '"codec_mime":
          "%s"
                ',
        self$`codec_mime`
        )},
        if (!is.null(self$`host`)) {
        sprintf(
        '"host":
          "%s"
                ',
        self$`host`
        )},
        if (!is.null(self$`http_auth`)) {
        sprintf(
        '"http_auth":
          "%s"
                ',
        self$`http_auth`
        )},
        if (!is.null(self$`path`)) {
        sprintf(
        '"path":
          "%s"
                ',
        self$`path`
        )},
        if (!is.null(self$`resolution`)) {
        sprintf(
        '"resolution":
           [%s]
        ',
        paste(unlist(lapply(self$`resolution`, function(x) paste0('"', x, '"'))), collapse=",")
        )},
        if (!is.null(self$`segment_info`)) {
        sprintf(
        '"segment_info":
          "%s"
                ',
        self$`segment_info`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VideoDefinitionJson) {
      VideoDefinitionObject <- jsonlite::fromJSON(VideoDefinitionJson)
      self$`codec` <- VideoDefinitionObject$`codec`
      self$`codec_description` <- VideoDefinitionObject$`codec_description`
      self$`codec_mime` <- VideoDefinitionObject$`codec_mime`
      self$`host` <- VideoDefinitionObject$`host`
      self$`http_auth` <- VideoDefinitionObject$`http_auth`
      self$`path` <- VideoDefinitionObject$`path`
      self$`resolution` <- ApiClient$new()$deserializeObj(VideoDefinitionObject$`resolution`, "array[integer]", loadNamespace("tator"))
      self$`segment_info` <- VideoDefinitionObject$`segment_info`
      self
    }
  )
)
