# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VideoSpec
#' @description VideoSpec Class
#' @format An \code{R6Class} generator object
#' @field codec  character 
#'
#' @field fps  numeric 
#'
#' @field gid  character 
#'
#' @field height  integer 
#'
#' @field md5  character 
#'
#' @field media_files  \link{MediaFiles} 
#'
#' @field name  character 
#'
#' @field num_frames  integer 
#'
#' @field progressName  character [optional]
#'
#' @field section  character 
#'
#' @field thumbnail_gif_url  character 
#'
#' @field thumbnail_url  character 
#'
#' @field type  integer 
#'
#' @field uid  character 
#'
#' @field width  integer 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VideoSpec <- R6::R6Class(
  'VideoSpec',
  public = list(
    `codec` = NULL,
    `fps` = NULL,
    `gid` = NULL,
    `height` = NULL,
    `md5` = NULL,
    `media_files` = NULL,
    `name` = NULL,
    `num_frames` = NULL,
    `progressName` = NULL,
    `section` = NULL,
    `thumbnail_gif_url` = NULL,
    `thumbnail_url` = NULL,
    `type` = NULL,
    `uid` = NULL,
    `width` = NULL,
    initialize = function(`codec`, `fps`, `gid`, `height`, `md5`, `media_files`, `name`, `num_frames`, `section`, `thumbnail_gif_url`, `thumbnail_url`, `type`, `uid`, `width`, `progressName`=NULL, ...){
      local.optional.var <- list(...)
      if (!missing(`codec`)) {
        stopifnot(is.character(`codec`), length(`codec`) == 1)
        self$`codec` <- `codec`
      }
      if (!missing(`fps`)) {
        self$`fps` <- `fps`
      }
      if (!missing(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!missing(`height`)) {
        stopifnot(is.numeric(`height`), length(`height`) == 1)
        self$`height` <- `height`
      }
      if (!missing(`md5`)) {
        stopifnot(is.character(`md5`), length(`md5`) == 1)
        self$`md5` <- `md5`
      }
      if (!missing(`media_files`)) {
        stopifnot(R6::is.R6(`media_files`))
        self$`media_files` <- `media_files`
      }
      if (!missing(`name`)) {
        stopifnot(is.character(`name`), length(`name`) == 1)
        self$`name` <- `name`
      }
      if (!missing(`num_frames`)) {
        stopifnot(is.numeric(`num_frames`), length(`num_frames`) == 1)
        self$`num_frames` <- `num_frames`
      }
      if (!missing(`section`)) {
        stopifnot(is.character(`section`), length(`section`) == 1)
        self$`section` <- `section`
      }
      if (!missing(`thumbnail_gif_url`)) {
        stopifnot(is.character(`thumbnail_gif_url`), length(`thumbnail_gif_url`) == 1)
        self$`thumbnail_gif_url` <- `thumbnail_gif_url`
      }
      if (!missing(`thumbnail_url`)) {
        stopifnot(is.character(`thumbnail_url`), length(`thumbnail_url`) == 1)
        self$`thumbnail_url` <- `thumbnail_url`
      }
      if (!missing(`type`)) {
        stopifnot(is.numeric(`type`), length(`type`) == 1)
        self$`type` <- `type`
      }
      if (!missing(`uid`)) {
        stopifnot(is.character(`uid`), length(`uid`) == 1)
        self$`uid` <- `uid`
      }
      if (!missing(`width`)) {
        stopifnot(is.numeric(`width`), length(`width`) == 1)
        self$`width` <- `width`
      }
      if (!is.null(`progressName`)) {
        stopifnot(is.character(`progressName`), length(`progressName`) == 1)
        self$`progressName` <- `progressName`
      }
    },
    toJSON = function() {
      VideoSpecObject <- list()
      if (!is.null(self$`codec`)) {
        VideoSpecObject[['codec']] <-
          self$`codec`
      }
      if (!is.null(self$`fps`)) {
        VideoSpecObject[['fps']] <-
          self$`fps`
      }
      if (!is.null(self$`gid`)) {
        VideoSpecObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`height`)) {
        VideoSpecObject[['height']] <-
          self$`height`
      }
      if (!is.null(self$`md5`)) {
        VideoSpecObject[['md5']] <-
          self$`md5`
      }
      if (!is.null(self$`media_files`)) {
        VideoSpecObject[['media_files']] <-
          self$`media_files`$toJSON()
      }
      if (!is.null(self$`name`)) {
        VideoSpecObject[['name']] <-
          self$`name`
      }
      if (!is.null(self$`num_frames`)) {
        VideoSpecObject[['num_frames']] <-
          self$`num_frames`
      }
      if (!is.null(self$`progressName`)) {
        VideoSpecObject[['progressName']] <-
          self$`progressName`
      }
      if (!is.null(self$`section`)) {
        VideoSpecObject[['section']] <-
          self$`section`
      }
      if (!is.null(self$`thumbnail_gif_url`)) {
        VideoSpecObject[['thumbnail_gif_url']] <-
          self$`thumbnail_gif_url`
      }
      if (!is.null(self$`thumbnail_url`)) {
        VideoSpecObject[['thumbnail_url']] <-
          self$`thumbnail_url`
      }
      if (!is.null(self$`type`)) {
        VideoSpecObject[['type']] <-
          self$`type`
      }
      if (!is.null(self$`uid`)) {
        VideoSpecObject[['uid']] <-
          self$`uid`
      }
      if (!is.null(self$`width`)) {
        VideoSpecObject[['width']] <-
          self$`width`
      }

      VideoSpecObject
    },
    fromJSON = function(VideoSpecJson) {
      VideoSpecObject <- jsonlite::fromJSON(VideoSpecJson)
      if (!is.null(VideoSpecObject$`codec`)) {
        self$`codec` <- VideoSpecObject$`codec`
      }
      if (!is.null(VideoSpecObject$`fps`)) {
        self$`fps` <- VideoSpecObject$`fps`
      }
      if (!is.null(VideoSpecObject$`gid`)) {
        self$`gid` <- VideoSpecObject$`gid`
      }
      if (!is.null(VideoSpecObject$`height`)) {
        self$`height` <- VideoSpecObject$`height`
      }
      if (!is.null(VideoSpecObject$`md5`)) {
        self$`md5` <- VideoSpecObject$`md5`
      }
      if (!is.null(VideoSpecObject$`media_files`)) {
        media_filesObject <- MediaFiles$new()
        media_filesObject$fromJSON(jsonlite::toJSON(VideoSpecObject$media_files, auto_unbox = TRUE, digits = NA))
        self$`media_files` <- media_filesObject
      }
      if (!is.null(VideoSpecObject$`name`)) {
        self$`name` <- VideoSpecObject$`name`
      }
      if (!is.null(VideoSpecObject$`num_frames`)) {
        self$`num_frames` <- VideoSpecObject$`num_frames`
      }
      if (!is.null(VideoSpecObject$`progressName`)) {
        self$`progressName` <- VideoSpecObject$`progressName`
      }
      if (!is.null(VideoSpecObject$`section`)) {
        self$`section` <- VideoSpecObject$`section`
      }
      if (!is.null(VideoSpecObject$`thumbnail_gif_url`)) {
        self$`thumbnail_gif_url` <- VideoSpecObject$`thumbnail_gif_url`
      }
      if (!is.null(VideoSpecObject$`thumbnail_url`)) {
        self$`thumbnail_url` <- VideoSpecObject$`thumbnail_url`
      }
      if (!is.null(VideoSpecObject$`type`)) {
        self$`type` <- VideoSpecObject$`type`
      }
      if (!is.null(VideoSpecObject$`uid`)) {
        self$`uid` <- VideoSpecObject$`uid`
      }
      if (!is.null(VideoSpecObject$`width`)) {
        self$`width` <- VideoSpecObject$`width`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`codec`)) {
        sprintf(
        '"codec":
          "%s"
                ',
        self$`codec`
        )},
        if (!is.null(self$`fps`)) {
        sprintf(
        '"fps":
          %d
                ',
        self$`fps`
        )},
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`height`)) {
        sprintf(
        '"height":
          %d
                ',
        self$`height`
        )},
        if (!is.null(self$`md5`)) {
        sprintf(
        '"md5":
          "%s"
                ',
        self$`md5`
        )},
        if (!is.null(self$`media_files`)) {
        sprintf(
        '"media_files":
        %s
        ',
        jsonlite::toJSON(self$`media_files`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`name`)) {
        sprintf(
        '"name":
          "%s"
                ',
        self$`name`
        )},
        if (!is.null(self$`num_frames`)) {
        sprintf(
        '"num_frames":
          %d
                ',
        self$`num_frames`
        )},
        if (!is.null(self$`progressName`)) {
        sprintf(
        '"progressName":
          "%s"
                ',
        self$`progressName`
        )},
        if (!is.null(self$`section`)) {
        sprintf(
        '"section":
          "%s"
                ',
        self$`section`
        )},
        if (!is.null(self$`thumbnail_gif_url`)) {
        sprintf(
        '"thumbnail_gif_url":
          "%s"
                ',
        self$`thumbnail_gif_url`
        )},
        if (!is.null(self$`thumbnail_url`)) {
        sprintf(
        '"thumbnail_url":
          "%s"
                ',
        self$`thumbnail_url`
        )},
        if (!is.null(self$`type`)) {
        sprintf(
        '"type":
          %d
                ',
        self$`type`
        )},
        if (!is.null(self$`uid`)) {
        sprintf(
        '"uid":
          "%s"
                ',
        self$`uid`
        )},
        if (!is.null(self$`width`)) {
        sprintf(
        '"width":
          %d
                ',
        self$`width`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VideoSpecJson) {
      VideoSpecObject <- jsonlite::fromJSON(VideoSpecJson)
      self$`codec` <- VideoSpecObject$`codec`
      self$`fps` <- VideoSpecObject$`fps`
      self$`gid` <- VideoSpecObject$`gid`
      self$`height` <- VideoSpecObject$`height`
      self$`md5` <- VideoSpecObject$`md5`
      self$`media_files` <- MediaFiles$new()$fromJSON(jsonlite::toJSON(VideoSpecObject$media_files, auto_unbox = TRUE, digits = NA))
      self$`name` <- VideoSpecObject$`name`
      self$`num_frames` <- VideoSpecObject$`num_frames`
      self$`progressName` <- VideoSpecObject$`progressName`
      self$`section` <- VideoSpecObject$`section`
      self$`thumbnail_gif_url` <- VideoSpecObject$`thumbnail_gif_url`
      self$`thumbnail_url` <- VideoSpecObject$`thumbnail_url`
      self$`type` <- VideoSpecObject$`type`
      self$`uid` <- VideoSpecObject$`uid`
      self$`width` <- VideoSpecObject$`width`
      self
    }
  )
)
