# Tator REST API
#
# Interface to the Tator backend.
#
# The version of the OpenAPI document: v1
# 
# Generated by: https://openapi-generator.tech

#' @docType class
#' @title VideoUpdate
#' @description VideoUpdate Class
#' @format An \code{R6Class} generator object
#' @field gid  character 
#'
#' @field id  integer 
#'
#' @field media_files  \link{MediaFiles} 
#'
#' @field uid  character 
#'
#'
#' @importFrom R6 R6Class
#' @importFrom jsonlite fromJSON toJSON
#' @export
VideoUpdate <- R6::R6Class(
  'VideoUpdate',
  public = list(
    `gid` = NULL,
    `id` = NULL,
    `media_files` = NULL,
    `uid` = NULL,
    initialize = function(`gid`, `id`, `media_files`, `uid`, ...){
      local.optional.var <- list(...)
      if (!missing(`gid`)) {
        stopifnot(is.character(`gid`), length(`gid`) == 1)
        self$`gid` <- `gid`
      }
      if (!missing(`id`)) {
        stopifnot(is.numeric(`id`), length(`id`) == 1)
        self$`id` <- `id`
      }
      if (!missing(`media_files`)) {
        stopifnot(R6::is.R6(`media_files`))
        self$`media_files` <- `media_files`
      }
      if (!missing(`uid`)) {
        stopifnot(is.character(`uid`), length(`uid`) == 1)
        self$`uid` <- `uid`
      }
    },
    toJSON = function() {
      VideoUpdateObject <- list()
      if (!is.null(self$`gid`)) {
        VideoUpdateObject[['gid']] <-
          self$`gid`
      }
      if (!is.null(self$`id`)) {
        VideoUpdateObject[['id']] <-
          self$`id`
      }
      if (!is.null(self$`media_files`)) {
        VideoUpdateObject[['media_files']] <-
          self$`media_files`$toJSON()
      }
      if (!is.null(self$`uid`)) {
        VideoUpdateObject[['uid']] <-
          self$`uid`
      }

      VideoUpdateObject
    },
    fromJSON = function(VideoUpdateJson) {
      VideoUpdateObject <- jsonlite::fromJSON(VideoUpdateJson)
      if (!is.null(VideoUpdateObject$`gid`)) {
        self$`gid` <- VideoUpdateObject$`gid`
      }
      if (!is.null(VideoUpdateObject$`id`)) {
        self$`id` <- VideoUpdateObject$`id`
      }
      if (!is.null(VideoUpdateObject$`media_files`)) {
        media_filesObject <- MediaFiles$new()
        media_filesObject$fromJSON(jsonlite::toJSON(VideoUpdateObject$media_files, auto_unbox = TRUE, digits = NA))
        self$`media_files` <- media_filesObject
      }
      if (!is.null(VideoUpdateObject$`uid`)) {
        self$`uid` <- VideoUpdateObject$`uid`
      }
    },
    toJSONString = function() {
      jsoncontent <- c(
        if (!is.null(self$`gid`)) {
        sprintf(
        '"gid":
          "%s"
                ',
        self$`gid`
        )},
        if (!is.null(self$`id`)) {
        sprintf(
        '"id":
          %d
                ',
        self$`id`
        )},
        if (!is.null(self$`media_files`)) {
        sprintf(
        '"media_files":
        %s
        ',
        jsonlite::toJSON(self$`media_files`$toJSON(), auto_unbox=TRUE, digits = NA)
        )},
        if (!is.null(self$`uid`)) {
        sprintf(
        '"uid":
          "%s"
                ',
        self$`uid`
        )}
      )
      jsoncontent <- paste(jsoncontent, collapse = ",")
      paste('{', jsoncontent, '}', sep = "")
    },
    fromJSONString = function(VideoUpdateJson) {
      VideoUpdateObject <- jsonlite::fromJSON(VideoUpdateJson)
      self$`gid` <- VideoUpdateObject$`gid`
      self$`id` <- VideoUpdateObject$`id`
      self$`media_files` <- MediaFiles$new()$fromJSON(jsonlite::toJSON(VideoUpdateObject$media_files, auto_unbox = TRUE, digits = NA))
      self$`uid` <- VideoUpdateObject$`uid`
      self
    }
  )
)
